### ISSUE TITLE
Can't get the shell to launch from any path inside rootfs

### ISSUE THREAD

**Issue by sumitsahrawat** [yuk7/ArchWSL#10]
Changing the `Start in:` field of the shortcut to any directory inside `rootfs`, e.g. `C:\Arch\rootfs\root` causes the shell to start in `/` instead of `/root` as expected.

**Comment by yuk7** [comment]
@sumitsahrawat 
It's in the WSL specifications... You can't directly use the WSL rootfs directory.
Do you want to launch with Linux's default directory? I can update Launcher.

**Comment by sumitsahrawat** [comment]
I'd like to launch it in the home directory for the Linux user instead of any windows directory.
Currently it opens it `/` by default, and I have a `cd ~` at the end of my `.zshrc` to get it to appear as if it's starting in `~`.

**Comment by yuk7** [comment]
@sumitsahrawat 
Ok,I updated Launcher. [Arch.exe](https://github.com/yuk7/WSL-DistroLauncher/releases/download/18030400/Arch.exe)
Replace exe and retry please>

**Comment by sumitsahrawat** [comment]
Thanks for the prompt reply 👍 

It works well for the `root` user, but `config --default-user` doesn't work for me anymore.

**Comment by yuk7** [comment]
@sumitsahrawat 
Ok.

adn Probably,This issue(config user) is same as https://github.com/yuk7/ArchWSL/issues/7.
Please try this:
1. Please close the command prompt, wait for a while, then re-open it again.(I solved the problem in this way)
2. Reboot the computer.
Thank you for testing!

**Comment by sumitsahrawat** [comment]
Now it started working 😃

I did the following, but I don't think this changes anything:

```shell
# pacman -S zsh grml-zsh-config
# chsh -s $(which zsh)
```

You've made a fun little thing here, thanks for all the hard work 👍 
I'll close this and let the discussion continue at #7.

**Comment by sumitsahrawat** [comment]
Additionally, it's even working for non-root users.
