### ISSUE TITLE
USB stick/disk files not visible under /mnt/x

### ISSUE THREAD

**Issue by Paku-** [yuk7/ArchWSL#100]
**Describe the issue**
It seems the USB external drive  mounted under a letter f.e. 'G:' is shown as empty at /mnt/g

Edit: Very strange but after some time or WSL restart files are visible...

**To Reproduce**
Use USB stick or USB external drive

**Expected behavior**
Access the disk files

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.18363.535]
 - Security Software: buildin
 - WSL version 1/2: no idea (newest W10)
 - ArchWSL version [e.g. 19.3.7.0] ?? One of lateset
 - ArchWSL Installer type zip
 - Launcher version [e.g. 19030700] ?? No -version option

**Comment by yuk7** [comment]
Please use `mount` command.
```mount -t drvfs g: /mnt/g```

**Comment by Paku-** [comment]
Should't it be mount after WSL startup ? As other disks are.

**Comment by yuk7** [comment]
It's a WSL specification.
Removable drives are not mounted automatically.
That is to keep it removable.

**Comment by yuk7** [comment]
The fixed drive letter can be automatically mounted by describing it in fstab.

**Comment by Paku-** [comment]
ok, so how it got mounted by itself after few minutes ?

**Comment by yuk7** [comment]
`wslconfig /t Arch` in Windows cmd for restart instance

**Comment by Paku-** [comment]
Will it reset my configs or installed apps ?

**Comment by yuk7** [comment]
No

**Comment by Paku-** [comment]
I did it but nothing happened, will see.

**Comment by yuk7** [comment]
Did you write the necessary settings in fstab and wsl.conf?

https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/
fstab:
```
G: /mnt/g drvfs defaults,noatime,uid=1000,gid=1000 0 0
```

**Comment by Paku-** [comment]
Did not understand you. So the command will reload config including fstab ?
Will test it later. Thank you for assistance.

**Comment by arlllk** [comment]
For next references, this post show the process to mount USB to WSL

https://docs.microsoft.com/en-us/archive/blogs/wsl/file-system-improvements-to-the-windows-subsystem-for-linux
