### ISSUE TITLE
archlinux.org unreachable

### ISSUE THREAD

**Issue by as3ii** [yuk7/ArchWSL#101]
archlinux.org is unreachable inside arch-wsl

**To Reproduce**
`drill archlinux.org` resolve the hostname
`ping archlinux.org` doesn't work
`wget archlinux.org` doesn't work (stick on "Resolving archlinux.org...")
pinging the ip returned from drill work
using wget with the ip returned from drill return a 404 error

**Expected behavior**
archlinux.org and subdomain reachable inside arch-wsl

**Enviroment:**
 - Windows build number: 10.0.18363.535
 - Security Software: avast
 - WSL version 1/2: WSL1
 - ArchWSL version 19.7.2.0
 - ArchWSL Installer type: zip update
 - Launcher version 19070200

**Additional context**
archlinux.org is reachable from windows

**Comment by as3ii** [comment]
(now I'll try updating arch-wsl)

**Comment by as3ii** [comment]
> 
> 
> (now I'll try updating arch-wsl)

nothing changed

**Comment by Geo25rey** [comment]
Yeah, I have the same issue. All I can tell right now is that there is some kind of problem resolving hostnames, but the internet is still accessible via IP addresses.

**Comment by Geo25rey** [comment]
Try changing the contents of /etc/resolv.conf to some known good DNS servers. That fixed my issue. Before my /etc/resolv.conf was filled with non-printable characters.
Ex:
`nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 8.8.4.4`

**Comment by yuk7** [comment]
In my environment, I could not see the problem...
Are other domains ip resolved?

**Comment by Geo25rey** [comment]
Can you share the contents of `/etc/resolv.conf`? Like with `cat /etc/resolv.conf`.
