### ISSUE TITLE
Shell starts from windows user home when launching from windows terminal

### ISSUE THREAD

**Issue by dianlujitao** [yuk7/ArchWSL#103]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
Shell starts from windows user home `/mnt/c/users/$whoami` instead of linux user home `~` when launching from windows terminal's tab bar. The later one is the default behavior when launching from arch.exe.

**To Reproduce**
Install with appx image. From windows terminal, click on the "V" icon of tab bar and choose `Arch`.

**Expected behavior**
$PWD eq /home/$whoami

**Enviroment:**
 - Windows build number: 10.0.18363.535
 - Security Software: [Huorong](https://www.huorong.cn)
 - WSL version 1/2: WSL1
 - ArchWSL version: 19.11.16.0
 - ArchWSL Installer type: appx clean
 - Launcher version: 19111602

**Comment by yuk7** [comment]
Please use `run` argument.
`Arch.exe run`.

**Comment by dianlujitao** [comment]
You probably didn't get me.
When launching from this entry:
![image](https://user-images.githubusercontent.com/5774651/72214541-2947bb00-353f-11ea-80c1-cd21a2f1af3e.png)
$PWD points to `/mnt/c/users/$whoami`, but the expected path should be `~`

**Comment by arlllk** [comment]
Yea, that a Windows Terminal thing.

This is what you want
`"commandline": "wsl ~ -d Arch",`

This is an issue with windows terminal not with Arch, [as seen here](https://github.com/microsoft/terminal/issues/878)

**Comment by dianlujitao** [comment]
Thanks, a bit tricky but it works!

**Comment by boyedarat** [comment]
> Yea, that a Windows Terminal thing.
> 
> This is what you want
> `"commandline": "wsl ~ -d Arch",`
> 
> This is an issue with windows terminal not with Arch, [as seen here](https://github.com/microsoft/terminal/issues/878)

@yuk7 can we add the solution from @arlllk above to the wiki?
Thanks.
