### ISSUE TITLE
Arch.exe arguments not working

### ISSUE THREAD

**Issue by angeelgod** [yuk7/ArchWSL#106]
**Describe the issue**
exe arguments (config, run, get) not working
Returns arch: Unknown option -- default-user alessander

**To Reproduce**
run Arch.exe with any argument specified on README.md from cmd and/or powershell and/or inside Arch itself

**Expected behavior**
Should be able to set config or get info regarding wsl instance

**Enviroment:**
 - Windows build number: 10.0.18363.592
 - Security Software: McAfee LiveSafe
 - WSL version 1/2: 1
 - ArchWSL versión: ???
 - ArchWSL Installer type: appx
 - Launcher version [e.g. 19030700] (Type `Arch.exe version` at a Command Prompt): typing 'Arch.exe version' returns 'extra operand 'version''

**Additional context**

**Comment by yuk7** [comment]
If you use appx, can you update to the latest version?
[Download latest appx](https://github.com/yuk7/ArchWSL/releases/latest) and please install it...

**Comment by yuk7** [comment]
It looks you are not calling Arch.exe
Can you check which command is being called? `which arch.exe`

**Comment by sasha00123** [comment]
> **Describe the issue**
> exe arguments (config, run, get) not working
> Returns arch: Unknown option -- default-user alessander
> 
> **To Reproduce**
> run Arch.exe with any argument specified on README.md from cmd and/or powershell and/or inside Arch itself
> 
> **Expected behavior**
> Should be able to set config or get info regarding wsl instance
> 
> **Enviroment:**
> 
> * Windows build number: 10.0.18363.592
> * Security Software: McAfee LiveSafe
> * WSL version 1/2: 1
> * ArchWSL versión: ???
> * ArchWSL Installer type: appx
> * Launcher version [e.g. 19030700] (Type `Arch.exe version` at a Command Prompt): typing 'Arch.exe version' returns 'extra operand 'version''
> 
> **Additional context**

Probably, your problem is that you have something like Git Bash or any other terminal emulator installed, which has conflicting arch.exe executable in Path.
