### ISSUE TITLE
Installation Failed HRESULT:0x80370109

### ISSUE THREAD

**Issue by Hobr** [yuk7/ArchWSL#107]
**Describe the issue**
Could not install.
I have installed Ubuntu(WSL) successful.

**To Reproduce**
Print:
```bash
Installing...
ERROR:Installation Failed!
HRESULT:0x80370109
Press any key to continue...
```

**Enviroment:**
 - Windows build number: 10.0.19041.21
 - Security Software: Microsoft Defender
 - WSL version 1/2: WSL2
 - ArchWSL version 20.1.31.0
 - ArchWSL Installer type :appx
 - Launcher version: 20013100

**Comment by yuk7** [comment]
Ok. I'll test later.

**Comment by yuk7** [comment]
It seems timeouted WSL2 virtual machine.
Can you retry it?

Alternatively, there is a method of installing once with WSL1 and changing to WSL2.

**Comment by Hobr** [comment]
I thought there may any mistakes on my system......
When I install the 20.2.7.0 without administrator rights,it got 0x80004005,
with administrator rights,got 0x80071772
