### ISSUE TITLE
Ripgrep and other Rust utilities panic

### ISSUE THREAD

**Issue by Zeturic** [yuk7/ArchWSL#109]
**Describe the issue**
I've noticed this in three separate Rust utilities: ripgrep, fd, and rustup; whenever you attempt to use them, they end up noisily panicing because of an assertion error.

**To Reproduce**

All of the following will fail with the same assertion error:

```shell
$ sudo pacman -S ripgrep
$ rg -i ./ -e "foo"
```

```shell
$ sudo pacman -S fd
$ fd 
```

```shell
$ sudo pacman -S rustup
$ rustup toolchain install stable
```

**Expected behavior**
The utilities should work. For example, `fd` should be printing out all files in the cwd.

**Actual behavior**
```shell
$ fd
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`assertion failed: `(left == right)`
  left: `22`,
 right: `4`', ', src/libstd/sys/unix/thread.rssrc/libstd/sys/unix/thread.rsthread '::<unnamed>153153' panicked at ':assertion failed: `(left == right)`
  left: `22`,
 right: `4`:21', 21
src/libstd/sys/unix/thread.rs
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
:153:21
```

```shell
$ rg -i ./ -e "foo"
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:153:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:153:21
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:153:21
```

```shell
$ rustup toolchain install stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-01-30, rust version 1.41.0 (5e1a79984 2020-01-27)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
stack backtrace:
   0:     0x7f680146bb3c - <unknown>
   1:     0x7f68011440ac - <unknown>
   2:     0x7f680146b216 - <unknown>
   3:     0x7f680146ae2e - <unknown>
   4:     0x7f680146a5d3 - <unknown>
   5:     0x7f680146a14e - <unknown>
   6:     0x7f680146a0e0 - <unknown>
   7:     0x7f680143b336 - <unknown>
   8:     0x7f680143aae6 - <unknown>
   9:     0x7f680139a550 - <unknown>
  10:     0x7f680142ec47 - <unknown>
  11:     0x7f6801406d08 - <unknown>
  12:     0x7f68013f567a - <unknown>
  13:     0x7f68013da4fc - <unknown>
  14:     0x7f68013d7ae1 - <unknown>
  15:     0x7f6801096eba - <unknown>
  16:     0x7f680106f139 - <unknown>
  17:     0x7f68010ad74d - <unknown>
  18:     0x7f68010ac9c3 - <unknown>
  19:     0x7f68010523c3 - <unknown>
  20:     0x7f68010b6108 - <unknown>
  21:     0x7f6800977023 - __libc_start_main
  22:     0x7f680105110e - <unknown>
  23:                0x0 - <unknown>
thread panicked while panicking. aborting.
zsh: illegal hardware instruction (core dumped)  rustup toolchain install stable
```

Interestingly, even though `fd` and `rg` panic, they actually do what they were asked. For example, `fd` actually will print out the files as intended, just prepended with the assertion error and you have to `ctrl-c` it to get back to the prompt.

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.18362.657]
 - Security Software: Windows Defender
 - WSL version 1/2: WSL1
 - ArchWSL version: ???
 - ArchWSL Installer type: zip
 - Launcher version: wsldl, version 19111602

**Additional context**
I loaded Arch on a VM and didn't have these sorts of issues. Additionally, I installed Ubuntu on WSL and didn't have these issues there either.

Also, while I can't speak for `fd` or `rustup`, I do know that up until recently `rg` was working fine. I do see a bunch of Windows Updates that have been installed to my PC recently, so that might be related.

**Comment by BurntSushi** [comment]
Drive by idea: if you pass `-j1` to ripgrep, does the panic go away? (I don't mean this as a solution, but rather, perhaps as a temporary work-around if it does work.)

**Comment by Zeturic** [comment]
> Drive by idea: if you pass `-j1` to ripgrep, does the panic go away? (I don't mean this as a solution, but rather, perhaps as a temporary work-around if it does work.)

Yes, it goes away. I didn't think to look for settings to prevent multiple threads. Thank you.

`fd` has the same option and it fixes it there too.

**Comment by alsam** [comment]
Thanks for `ripgrep` workaround, do you happen to know the similat workaround for `rustup`? Thanks!

**Comment by alsam** [comment]
actually this helped for `rustup`, `htop`, what else
```sh
pacman -U /var/cache/pacman/pkg/glibc-2.30-3-x86_64.pkg.tar.xz
```

**Comment by Frans-Willem** [comment]
If you no longer have glibc in your pacman cache, try this instead:
```
pacman -U https://archive.archlinux.org/packages/g/glibc/glibc-2.30-3-x86_64.pkg.tar.xz
```

**Comment by yuk7** [comment]
This issue has been fixed in the Windows Insider Build.
These will work correctly from build 2004, which will be distributed this spring.

**Comment by AurevoirXavier** [comment]
> This issue has been fixed in the Windows Insider Build.
> These will work correctly from build 2004, which will be distributed this spring.

Still got this error, I'm in Win10 Pro 2004:
```
Edition Windows 10 Pro
Version 2004
OS build 19041.264
Experience Windows Feature Experience Pack 120.2202.130.0
```

**Comment by AurevoirXavier** [comment]
Any update recently?

**Comment by AurevoirXavier** [comment]
After I update to WSL2, everything works good.


```
# go to https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel
# install the kernel
wsl --set-default-version Arch 2
```

**Comment by HaleTom** [comment]
[WSL2 can't easily be used inside VMware and has performance issues](https://superuser.com/a/1578373/365890).

(I'm making [my .dotfiles](https://github.com/haletom/dotfiles) work across different platforms)

**Comment by Frans-Willem** [comment]
This issue is still present, and reverting back to glibc is no longer an option as even sudo now stops working with a glibc that old.
