### ISSUE TITLE
Change Default User does work

### ISSUE THREAD

**Issue by murphytalk** [yuk7/ArchWSL#11]
Have added the user in Linux and can su to the new user when login as root, but after change default user to the new created one as instructed, the default is still root if run Arch.exe again.

**Comment by yuk7** [comment]
@murphytalk 
Please see #7
Try this:
1. Please close the command prompt, wait for a while, then re-open it again.(I solved the problem in this way)
2. Reboot the computer.

Please give me additional information if not resolved.
Thank you.

**Comment by murphytalk** [comment]
Yes that did solve the issue. Thank you !
