### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by bitshiftnetau** [yuk7/ArchWSL#111]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**

running pacman -Syyu after a fresh install of the Arch WSL on Windows 10
error: failed retrieving file 'core.db' from mirrors.kernel.org : SSL certificate problem: certificate has expired      error: failed to update core (download library error)                                                                   error: failed retrieving file 'extra.db' from mirrors.kernel.org : SSL certificate problem: certificate has expired     error: failed to update extra (download library error)                                                                  error: failed retrieving file 'community.db' from mirrors.kernel.org : SSL certificate problem: certificate has expired error: failed to update community (download library error)                                                              error: failed to synchronize all databases  

**To Reproduce**

- Follow the instructions on the git repo
1. unzip Arch.zip
2. run Arch.exe
3. run .appx file
4. install .cer file to Trusted Root Domain or whatever it is.. 

**Expected behavior**

Expected ability to install and have no SSL certificate issues

**Screenshots**

**Enviroment:**
 - Windows build number: Version	10.0.18363 Build 18363
 - Security Software: none
 - WSL version 1/2: no idea
 - ArchWSL version: 4.4.0-18362-Microsoft 
 - ArchWSL Installer type: zip + appx
 - Launcher version: no idea

I have tried re-installing the certificate and nothing changes.

**Comment by yuk7** [comment]
It looks like the SSL certificate from edge.kernel.org is currently expired.
Use another mirror server or wait until the server has a valid SSL certificate.
mirrorlist is /etc/pacman.d/mirrorlist

**Comment by yuk7** [comment]
This issue has been fixed by the server administrator.

**Comment by bitshiftnetau** [comment]
Cool. I've never seen that before, figured it might have been an image thing. Confirmed working now. Thanks

**Comment by mariadb-MartinVladev** [comment]
The `mirrors.kernel.org` certificate has actually expired:
```
$ openssl s_client -connect mirrors.kernel.org:443

depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = FR, ST = Paris, L = Paris, O = Gandi, CN = Gandi Standard SSL CA 2
verify return:1
depth=0 CN = kernel.org
verify error:num=10:certificate has expired
notAfter=Sep 27 23:59:59 2021 GMT
verify return:1
depth=0 CN = kernel.org
notAfter=Sep 27 23:59:59 2021 GMT
verify return:1
CONNECTED(00000003)
.....
```
Edit ` /etc/pacman.d/mirrorlist` and enable another mirror
