### ISSUE TITLE
How to run arch by appx

### ISSUE THREAD

**Issue by Innei** [yuk7/ArchWSL#112]
I installed archWSL by appx, it install ok, and init completed, then it closed. I want to run arch, and open powershell, press `arch`, but it not run arch. like this.
```
PS C:\Users\yiny> arch
x86_64
PS C:\Users\yiny> Arch
x86_64
PS C:\Users\yiny> arch.exe
x86_64
PS C:\Users\yiny> where arch
PS C:\Users\yiny> where Arch
```

how to fix it.
My systemOS is `17134.rs4_release.18410-1804`, already open WSL option.

**Comment by yuk7** [comment]
Do you have mingw or msys installed on your computer?
Do you have mingw or msys installed on your computer?

**Comment by Innei** [comment]
Emm, I installed git-bash.

I try to exec `which arch`, it shows `/usr/bin/arch`. But I don't know this path in Windows.

**Comment by yuk7** [comment]
Arch.exe is usually located in `%LocalAppData%\Microsoft\WindowsApps`.

**Comment by Innei** [comment]
My solution is uninstall other wsl, and then run `wsl` into arch container.
