### ISSUE TITLE
pikaur Can't update fakeroot-tcp

### ISSUE THREAD

**Issue by rubendibattista** [yuk7/ArchWSL#115]
**Please fill out the below information:**
**Describe the issue**
When updating `fakeroot-tcp`, it does not update

**To Reproduce**
Use `pikaur` or equivalent to update `fakeroot-tcp` from AUR

**Expected behavior**
`fakeroot-tcp` gets updated correctly

**Screenshots**

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.19041.172]
 - Security Software: Windows Defender
 - WSL version: WSL2
 - ArchWSL version. 20.3.26.0
 - ArchWSL Installer type zip/appx/other clean/update: appx
 - Launcher version wsldl, version 20032600

**Additional context**
Build output: 
```
libtool: install: (cd /home/rdb/.cache/pikaur/build/fakeroot-tcp/pkg/fakeroot-tcp/usr/lib/libfakeroot && { ln -s -f libf
akeroot-0.so libfakeroot.so || { rm -f libfakeroot.so && ln -s libfakeroot-0.so libfakeroot.so; }; })
libtool: install: /usr/bin/install -c .libs/libfakeroot.lai /home/rdb/.cache/pikaur/build/fakeroot-tcp/pkg/fakeroot-tcp/
usr/lib/libfakeroot/libfakeroot.la
libtool: warning: remember to run 'libtool --finish /usr/lib/libfakeroot'
 /usr/sbin/mkdir -p '/home/rdb/.cache/pikaur/build/fakeroot-tcp/pkg/fakeroot-tcp/usr/bin'
  /bin/sh ./libtool   --mode=install /usr/bin/install -c faked '/home/rdb/.cache/pikaur/build/fakeroot-tcp/pkg/fakeroot-
tcp/usr/bin'
libtool: install: /usr/bin/install -c faked /home/rdb/.cache/pikaur/build/fakeroot-tcp/pkg/fakeroot-tcp/usr/bin/faked
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/rdb/.cache/pikaur/build/fakeroot-tcp/src/fakeroot-1.24'
make[1]: Leaving directory '/home/rdb/.cache/pikaur/build/fakeroot-tcp/src/fakeroot-1.24'
```
When using WSL2, can I use `fakeroot`? (Instead of `fakeroot-tcp`)?

**Comment by yuk7** [comment]
Yes.
WSL2 does not require fakeroot-tcp.

**Comment by codemonkey800** [comment]
@yuk7 could you update this in the wiki pls? https://github.com/yuk7/ArchWSL/wiki/Known-issues
😄

**Comment by yuk7** [comment]
@codemonkey800 
I have not confirmed this problem yet.
Did it occur in your environment?

**Comment by codemonkey800** [comment]
@yuk7 Oh no I meant about WSL 2 not requiring `fakeroot-tcp`. I had trouble installing `google-cloud-sdk` from aur because it was hanging on the `package()` stage. I came here for help and found your answer here 😄 

Reinstalling `fakeroot` fixed the problem, so it would be nice to have a note in the wiki saying WSL 2 doesn't require `fakeroot-tcp` so that people don't install it when they don't need it, and so it also prevents weird problems like mine from happening lol

**Comment by yuk7** [comment]
@codemonkey800 I see.
I'll document it later👍

**Comment by OzoneHelix** [comment]
I found a solution to issues with fakeroot
just install base-devel and it should fix issues with that
