### ISSUE TITLE
My Xfce4 Can't work 

### ISSUE THREAD

**Issue by Rekent** [yuk7/ArchWSL#116]
**Describe the issue**
My wsl version is wsl2，and now i install xfce4，and exec 'startxfce4'，it seems some problem with dbus. i google it,and  try to modify dbus to tcp localhost:0 , but didn't work.

![image](https://user-images.githubusercontent.com/20064149/78507528-0c73fa00-77b3-11ea-9af0-d30fbaaf5897.png)

**To Reproduce**
I edit bashrc like this:
![image](https://user-images.githubusercontent.com/20064149/78507568-49d88780-77b3-11ea-8ecf-fefb7d2469e0.png)

i am using vcxsrv + xfce4

**Expected behavior**
Maybe my setting is not correct,can u tell me how to fix this problem?

**Enviroment:**
 - Windows build number: 10.0.19041.172
 - Security Software ：https://www.huorong.cn/
 - WSL version 2
 - ArchWSL version 20.4.3.0
 - ArchWSL Installer type zip
 - Launcher version 20040300

**Additional context**
thx a lot

**Comment by arlllk** [comment]
This problem happens to me because the dbus daemon is not initialized because systemd can't run in WSL, one thing you can do is use [genie](https://github.com/arkane-systems/genie) that create an environment where systemd runs

**Comment by Rekent** [comment]
> This problem happens to me because the dbus daemon is not initialized because systemd can't run in WSL, one thing you can do is use [genie](https://github.com/arkane-systems/genie) that create an environment where systemd runs

Thanks a lot,It seems help me solve the dbus problem，now it seem has other problem when i exec 
'startxfce4'.

firstly, i edit my bashrc and add ：
`
export DISPLAY =172.17.240.1:0.0
`
the ip (172.17.240.1) is wsl ipv4 address i found it by ipconfig in windows powershell

and then terminal show like this :

`
[rekent@Richard-Laptop-wsl ~]$ startxfce4
/usr/bin/startxfce4: X server already running on display 172.17.240.1:0.0
xrdb: Connection timed out
xrdb: Can't open display '172.17.240.1:0.0'
Unable to init server: Could not connect: Connection refused
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
`

if u have similar problems ,please tell me how to fix it , thx

**Comment by arlllk** [comment]
I use this command in .bashrc to set the display 
`export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0`

But for the second problem it seem to be an incorrectly setup of vcxsrv, you need to configure it with **Disable access control** to make it work in WSL 2 ( reference [here](https://github.com/microsoft/WSL/issues/4106#issuecomment-502989345) )

**Comment by Rekent** [comment]
> I use this command in .bashrc to set the display
> `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0`
> 
> But for the second problem it seem to be an incorrectly setup of vcxsrv, you need to configure it with **Disable access control** to make it work in WSL 2 ( reference [here](https://github.com/microsoft/WSL/issues/4106#issuecomment-502989345) )

it works thanks u 👍

**Comment by Rekent** [comment]
firstly , close firewall :
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command " Set-NetFirewallProfile -DisabledInterfaceAliases 'vEthernet (WSL)'"
```
and append `-ac`  to start vcsrv like this

![image](https://user-images.githubusercontent.com/20064149/78642211-ef3f4880-78e4-11ea-81bd-48736900f0d6.png)

and exec `startxfce4`.
