### ISSUE TITLE
Why are the  contents of /bin /sbin /usr/bin /usr/sbin the same?

### ISSUE THREAD

**Issue by geometryolife** [yuk7/ArchWSL#118]
The commands in these folders are the same.
This should not be the case under normal circumstances.

**Comment by yuk7** [comment]
It is an Arch Linux specification.
Please read this:
https://wiki.archlinux.org/index.php/Frequently_asked_questions#Does_Arch_follow_the_Linux_Foundation

**Comment by geometryolife** [comment]
> It is an Arch Linux specification.
> Please read this:
> https://wiki.archlinux.org/index.php/Frequently_asked_questions#Does_Arch_follow_the_Linux_Foundation's_Filesystem_Hierarchy_Standard_(FHS)%3F

Thank you!
