### ISSUE TITLE
Reinstall fail in appx Package installer (0x80073D05)

### ISSUE THREAD

**Issue by Thadir** [yuk7/ArchWSL#119]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**

**To Reproduce**

Install the appx

Use windows uninstaller.

then try to reinstall.

Youl get the folwoing error:
App installation failed with error message: An internal error occurred with error 0x80073D05. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80073d05)

**Expected behavior**

You can reinstall the app if you unistalled it trough windows client.

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0

**Comment by yuk7** [comment]
If the archwsl folder exists in
`C:\Users\[user name]\AppData\Local\Packages\`
,try deleting it.

**Comment by igummie** [comment]
Same problem here. And I can't location the Arch wsl file in Packages

**Comment by yuk7** [comment]
Can you execute `wsreset.exe` in Administrator?
Doing that will reset the Windows Store cache.

**Comment by igummie** [comment]
I'm still having the same problem even after resetting the Windows store cache. I've also tried repairing the app and clearing its data. Still not working

**Comment by igummie** [comment]
I think I finally found the solution. Run `wslconfig /unregister Arch` in the Windows command prompt

**Comment by yuk7** [comment]
@igummie 
I think your issue is different from this.
Is your issue caused by the package installer?

**Comment by igummie** [comment]
@yuk7 after uninstalling through windows and trying to reinstall with the appx file it fails to launch

**Comment by yuk7** [comment]
![0x80073D05](https://user-images.githubusercontent.com/29954265/81766528-469e8d00-9511-11ea-9a96-b36d2964e979.png)
I have successfully reproduced this issue, but when I try the installation again, it succeeds...
I didn't know the cause of the issue.

**Comment by igummie** [comment]
@yuk7 
![arch](https://user-images.githubusercontent.com/25012134/81768310-a9a80980-94a8-11ea-9534-5e6082289fd9.gif)

**Comment by yuk7** [comment]
@igummie 
hmm... Can you type this command in Command Prompt?
```
Arch clean -y
Arch
```

**Comment by igummie** [comment]
@yuk7 
![image](https://user-images.githubusercontent.com/25012134/81769421-8e8ac900-94ab-11ea-930b-2fcaede55e10.png)
![image](https://user-images.githubusercontent.com/25012134/81769480-bbd77700-94ab-11ea-8413-330c5529c7ba.png)

**Comment by yuk7** [comment]
@igummie 
Ok. 
Can you try
```
wsl -d Arch
```
command?

**Comment by igummie** [comment]
@yuk7 
![image](https://user-images.githubusercontent.com/25012134/81889837-8a75ae80-9572-11ea-9fc2-5ad4bb15b66a.png)

**Comment by yuk7** [comment]
@igummie I think that errors came from WSL internal.
Can you try this on Administrator Command Prompt?:
```
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
```
and reboot the computer?

**Comment by igummie** [comment]
This is only happening with the Arch WSL
![image](https://user-images.githubusercontent.com/25012134/81890768-c14cc400-9574-11ea-97a7-3a4698af841a.png)

**Comment by Hatsune71** [comment]
I know how to fix this issue.
After Uninstalling Arch WSL search task named "init" on Task Manager 
then delete archwsl folder in  C:\Users\[user name]\AppData\Local\Packages\

**Comment by igummie** [comment]
Awesome Thank you!
