### ISSUE TITLE
Installation Failed: 0x80004005

### ISSUE THREAD

**Issue by kaynz** [yuk7/ArchWSL#12]
Hi,

running Arch.exe leads to this error:

``
Installing...
ERROR:Installation Failed!
HRESULT:0x80004005
Press any key to continue...
``

Searched for the error code and found out that the error occurs when you use a home folder with non english letters. But my home folder is full english. Also tried running with root priviliges. 

Thanks.

**Comment by Biswa96** [comment]
ArchWsl works perfect. In which folder did you in run arch.exe? Try to run it as administrator.

**Comment by kaynz** [comment]
That's what I meant with "root priviliges". C:\ArchLinux\Arch.exe.

**Comment by yuk7** [comment]
@kaynz 
hmm...
0x80004005 is unknown error.
Is WSL works correctly in your computer?

Please try Ubuntu provided in Store...

**Comment by kaynz** [comment]
Yes, Ubuntu works perfectly.

**Comment by yuk7** [comment]
Ok,
1. Did not you cancel the installation?
Please try `wslconfig /u Arch` command and retry to install...

2. Please give me additional infomation...
* Windows version(`ver` command output)
* Registry key values under `HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss` (opt.)
and others..

**Comment by kaynz** [comment]
1. `wslconfig /u Arch` and reinstall -> same error
2. Microsoft Windows [Version 10.0.16299.334]
![unbenannt](https://user-images.githubusercontent.com/12952835/38025862-3dc3d67c-328a-11e8-98ac-0024976fb581.png)

**Comment by yuk7** [comment]
@kaynz 
I still don't know reason of this problem...
3. Is the rootfs file broken?
Please re-download setup file...

**Comment by kaynz** [comment]
Aww. I know the issue.

Your installation guide says

> 2. Extract all files in zip file to same directory

Therefore I extracted everything including the rootfs.tar.gz.


# Arch.exe and rootfs.tar.gz have to be in the same folder! Do not extract rootfs.tar.gz!

**Comment by Biswa96** [comment]
One can place rootfs.tar.gz anywhere. Just you have to mention the full path in `WslRegisterDistribution()` function.
