### ISSUE TITLE
"An error occurred mounting one of your file systems. Please run 'dmesg' for more details."

### ISSUE THREAD

**Issue by hacker1024** [yuk7/ArchWSL#120]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
I just installed Arch on the WSL 2 (with the appx). Apon launching, this message is printed, however everything still works, and I can access `/mnt/c` perfectly.

**To Reproduce**
- Launch Arch.

**Enviroment:**
 - Windows build number: 10.0.19613.1000
 - Security Software: Windows Defender
 - WSL version 1/2: 2
 - ArchWSL version 20.4.3.0
 - ArchWSL Installer type zip/**appx**/other **clean**/update
 - Launcher version [e.g. 19030700] 20040300

**Additional context**
[Here's the full dmesg.](https://github.com/yuk7/ArchWSL/files/4532744/dmesg.txt) I think this line is the most relevant:
`[    0.694041] init: (1) ERROR: UtilCreateProcessAndWait:655: /bin/mount failed with status 0x`

**Comment by benglim** [comment]
I had mounted the EFI partition as a drive letter using BOOTICEX64. Just remove the drive association and the message disappeared.

**Comment by hacker1024** [comment]
My EFI partition wasn't mounted, but a reboot seems to have fixed the issue. Weird.
