### ISSUE TITLE
Vanilla Arch Linux WSL installation

### ISSUE THREAD

**Issue by ptanmay143** [yuk7/ArchWSL#121]
After using ArchWSL for a while, I can clearly see that many of the packages that are preinstalled would have not been installed if it was done using the "Installation guide" on Arch Linux Wiki. So it makes me wonder, what changes to the original Arch Linux are made to get to this working stage. I would like to understand them and perform them manually for myself. Here is a Reddit forum that I found would be useful but it is heavily outdated ( https://www.reddit.com/r/bashonubuntuonwindows/comments/5vnne8/howto_installing_arch_on_wsl_manually/ ). So to brief my issue, I would like to:

- Know the changes in ArchWSL rootfs.
- Manually perform the changes.

**Comment by yuk7** [comment]
List changes for rootfs now:
* `/etc/locale`: en_US.UTF-8 for default locale
* `/etc/pacman.d/mirrorlist`: mirrors.kernel.org for  default mirror server
* `/etc/resolv.conf`: for generate by WSL
* `fakeroot-tcp`: for use fakeroot in WSL1

List changes used in previous versions:
* /etc/profile: for inherit Windows path
* glibc-wsl: WSL patched glibc

Manually perform the changes:
* You can modify `rootfs.tar.gz`. extract and repack it.
Keep in mind that just under rootfs.tar.gz is `/`.
* You can also export rootfs with the `Arch.exe backup` command.

**Comment by yuk7** [comment]
rootfs is currently generated in the following repository now:
https://github.com/yuk7/ArchWSL-FS

**Comment by ptanmay143** [comment]
Okay, I understand the changes that you mentioned. I am going to download both, your mentioned root-fs and the official Arch Linux bootstrap fs. After comparing both the extracted filesystems, I'm going to perform the mentioned changes on the vanilla bootstrap and let you know. For now I'm closing the issue and will revert back later. Thank you for your time.

**Comment by ptanmay143** [comment]
Using an Arch Linux installation media (Live USB), you can create the bare minimum root filesystem (rootfs) used to boot Arch Linux on WSL.
NOTE: All the commands need to be run by root.
- Boot from an Arch Linux installation media.
- Use the pre-installed pacstrap command to create a Arch Linux root at /mnt.
`pacstrap -c /mnt`
Here, the -c option is used to get the packages from the local media instead of downloading from the internet.
- Edit the file /etc/resolv.conf so that it has only the following line in it.
`echo "# This file was automatically generated by WSL. To stop automatic generation
  of this file, remove this line." > /mnt/etc/resolv.conf`
- Convert into a tarball with gzip compression so that wsldl (Arch.exe) can take it as a rootfs input.
`cd /mnt && tar -zcpf ../rootfs.tar.gz *`
- Copy the rootfs.tar.gz to a location other than the installation media as the installation media does not have persistence.
- Paste the rootfs.tar.gz in a folder with Arch.exe and run the file which will install into WSL.

You can also use an existing Arch Linux installation to perform the same steps. You will need to install the package arch-install-scripts to access the pacstrap command.

- The only change this root filesystem and a normal Arch Linux installation root is to the file '/etc/resolv.conf'. 
- Follow the official installation guide ( https://wiki.archlinux.org/index.php/installation_guide ). I will post the necessary steps from the guide in the next comment.

**Comment by ptanmay143** [comment]
Post Installation Steps:

- Set the time zone.
`# ln -sf /usr/share/zoneinfo/_Region_/_City_ /etc/localtime`

- Edit /etc/locale.gen and uncomment en_US.UTF-8 UTF-8 and other needed locales. Then generate the locales. Set it as default locale.
`# sed -i -e "s/#en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen
# locale-gen
# echo "LANG=en_US.UTF-8" > /etc/locale.conf`

- Create the hostname file.
`# echo "_myhostname_" > /etc/hostname`

- Add matching entries to /etc/hosts file.

> 127.0.0.1	localhost
> ::1		        localhost
> 127.0.1.1	myhostname.localdomain	myhostname

If the system has a permanent IP address, it should be used instead of 127.0.1.1.

- Complete the pacman initialization.
`# pacman-key --init && pacman-key --populate archlinux`

- Install other required packages.
`# pacman -Syu _mypackagename_`
Install _base-devel_ package group if you want to install AUR packages too.
Install a text editor such as _nano_, _vim_, _neovim_.

- Create a normal user account.
`# useradd -m -G wheel _myusername_`

- Set passwords for both root and myusername.
`# passwd
# passwd myusername`

- Edit the /etc/sudoers file and uncomment the following line.

> # %wheel        ALL=(ALL)       ALL

**Comment by ptanmay143** [comment]
While using makepkg to install an AUR package, the following error occurs.
```
==> Entering fakeroot environment...
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```
I know this issue is caused due to fakeroot and can be solved by installing fakeroot-tcp which I got from ( https://github.com/yuk7/arch-prebuilt/releases ) 18082100 release assets. How do I make sure that the normal fakeroot package does not overwrite this fakeroot-tcp?

**Comment by yuk7** [comment]
Please edit /etc/pacman.conf
```
IgnorePkg   = fakeroot
```

**Comment by ptanmay143** [comment]
That totally worked. Thanks for all your time.
