### ISSUE TITLE
htop won't open

### ISSUE THREAD

**Issue by jfernandz** [yuk7/ArchWSL#124]
**Describe the issue**
I cannot open `htop`; it keeps a black background

**To Reproduce**
* Install `htop` with `sudo pacman -S htop`
* Run `htop`
* You should get a black background until you stop the process with `ctrl + c`

**Expected behavior**
`htop` runs as usually.

**Screenshots**
![image](https://user-images.githubusercontent.com/4059108/81475925-5b2c0e00-920f-11ea-916f-eb7b5ea1d63f.png)

**Enviroment:**
 - Windows build number: `10.0.18363.778`
 - Security Software: Windows Defender
 - WSL version 1/2: I don't know because `wsl -l -v` just shows the same than `wsl --help` so I guess the WSL1
 - ArchWSL version 20.4.3.0
 - ArchWSL Installer type zip/appx/other clean/update I'd say via `appx` but I don't remember right now
 - Launcher version `wsldl, version 20040300`

**Comment by yuk7** [comment]
I think this issue comes from glibc.
Probably,you can run this command to temporary fix this:
```
pacman -U https://archive.archlinux.org/packages/g/glibc/glibc-2.30-3-x86_64.pkg.tar.xz
```

**Comment by WyRe** [comment]
apparently it has been fixed after upgrade to WSL2

**Comment by evertonstz** [comment]
> 
> 
> apparently it has been fixed after upgrade to WSL2

I can confirm the problem persists on WSL2.

**Comment by Hkyx** [comment]
keep the problem with glibc but can't downgrade:

sudo pacman -U https://archive.archlinux.org/packages/g/glibc/glibc-2.30-3-x86_64.pkg.tar.xz
# sudo: /usr/lib/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/sudo/libsudo_util.so.0)

**Comment by AirManH** [comment]
`htop` works fine on my ArchWSL, and I'm using:

1. `WSL1`
2. `glibc 2.32-5`
3. `htop 3.0.2-1`
4. `uname -r`: `4.4.0-19041-Microsoft`
5. Windows build number: `10.0.19041.572`
6. Launcher version: `20040300`

**Comment by 1player** [comment]
Can't reproduce on WSL2, htop-3.0.2-1, glibc 2.32-5. Perhaps it's been fixed upstream?

**Comment by snowman** [comment]
> keep the problem with glibc but can't downgrade:
> 
> sudo pacman -U [archive.archlinux.org/packages/g/glibc/glibc-2.30-3-x86_64.pkg.tar.xz](https://archive.archlinux.org/packages/g/glibc/glibc-2.30-3-x86_64.pkg.tar.xz)
> 
> # sudo: /usr/lib/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/sudo/libsudo_util.so.0)

# Run following is enough
$ pacman -S glibc
