### ISSUE TITLE
Incompatibility with LTSC

### ISSUE THREAD

**Issue by ghost** [yuk7/ArchWSL#125]
**Describe the issue**
The application isn't compatible with LTSC version of Windows 10 (unlike official WSL distros).

There are few possible scenarios I tested.

1) Without Windows Store installed
- Installing with 'the zip method' the Arch.exe immediately exits without any error notices.
- Installing the appx with PowerShell is successful but the application isn't usable. The rootfs gets created in the location of the original appx (desktop in my case) and Arch.exe immediately exits.

2) With Windows Store installed
- Installing with 'the zip method' the Arch.exe exits with error HRESULT: 0x80070057
- The appx can be installed normally and the application behaves normally, expect any configuration (Arch.exe config --args) leads to the same error HRESULT: 0x80070057

**Expected behavior**
Official WSL distros allow installation without the need for Microsoft Store, either with PowerShell _Add-AppxPackage_ or by extracting the appx contents and using the contained exe directly. See documentation for manual install and server install.
https://docs.microsoft.com/en-us/windows/wsl/install-manual
https://docs.microsoft.com/en-us/windows/wsl/install-on-server

**Enviroment:**
Windows 10 Enterprise N LTSC 2019 (1809, build 17763)
WSL 1
ArchWSL 20.4.3.0
Clean zip and appx

**Additional context**
I'm not expecting a fix since this a very edge use case. More of an FYI that might be worth adding to known issues.

**Comment by yuk7** [comment]
Hmm...
It worked fine on My Windows Server 2019 Build 17763 with `Add-AppxPackage`.
I don't have a Enterprise LTSC testing environment, sorry.

**Comment by 5t-RawBeRry** [comment]
It works in LTSC.
![SoN8zK2girm3JLT.png](https://i.loli.net/2020/05/15/SoN8zK2girm3JLT.png)

**Comment by ptanmay143** [comment]
Usually error HRESULT: 0x80070057 meant that I forgot to enable the [Windows Subsystem for Linux on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10) before running the `Arch.exe`. Since you are on LTSC which is based on Windows 10 build 1809, you won't be able to use the WSL2 version. Use the instructions for WSL1.
