### ISSUE TITLE
Arch not starting after changing the path of the folder

### ISSUE THREAD

**Issue by MariusLedig** [yuk7/ArchWSL#126]
When I double click on my arch.exe a terminal start and close instantly.

I have installed arch and used it, but my folder was big so I decided to move to another disk.

When I wanted to start arch got an error (that he can't find the Arch.exe to the old path) and it tells me that he will change the path of the new installation.
But when I wanted to start my Arch again got the error and if I move my folder to the old path I got the same error.

It should have change the path of the new installation and worked again.

https://i.imgur.com/CTCl6nQ.gifv

Environment:
 - Microsoft Windows [version 10.0.18363.815]
 - Windows Security disabled
 - WSL1
 - ArchWSL version 20.4.3.0
 - version 20040300

**Comment by yuk7** [comment]
The distro cannot be moved to another disk.
WSL1 uses the extended attributes of the file system, which a normal copy(= move across disk) loses.

**Comment by MariusLedig** [comment]
Ok but now I moved the folder where it was before but got the same problem. Is there any way to fix it ?

**Comment by yuk7** [comment]
Unfortunately, extended attributes have been lost by copying, so I think it's difficult to fix.
