### ISSUE TITLE
WSL2 Improvements

### ISSUE THREAD

**Issue by ktmriki** [yuk7/ArchWSL#128]
Correct me if I'm wrong, but doesn't WSL2's better kernel integration enable the use of systemd? WSL2 can already be used via the Windows Insider program.

**Comment by ktmriki** [comment]
Nevermind, I'm an idiot and didn't read the wiki beforehand. At this point you could basically make a separate WSL2 version though, because it enables so many features.

**Comment by yuk7** [comment]
Thank you for your suggestion.
I'm also interested in a WSL optimized distribution.
But now it's difficult because I don't have enough time to commit to it...

I can provide a support script, but I don't think there is much improvement.

**Comment by yuk7** [comment]
I started creating ArchWSL2,includes systemd integration.
It is a prototype version.
https://github.com/yuk7/ArchWSL2

**Comment by enihcam** [comment]
Is it able to run Linux GUI apps?

https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/#wsl-gui

**Comment by yuk7** [comment]
@enihcam 
Maybe it's yes.
But I don't know at the moment.
