### ISSUE TITLE
ALSA/PulseAudio Broken For Anyone else?

### ISSUE THREAD

**Issue by PhilDim1** [yuk7/ArchWSL#132]
I doubt this is an ArchWSL issue and is probably more of a general WSL issue, but is ALSA and PulseAudio broken for anyone else? I had this working beautifully until it suddenly stopped working, probably from a new-ish Insider build.

I even tried this on Ubuntu, same thing. Anyone figure it out?

pdimor@DESKTOP-LLMQEP1 ~> mocp
Can't load plugin libaac_decoder: file not found
Can't load plugin libffmpeg_decoder: file not found
Can't load plugin libmodplug_decoder: file not found
Can't load plugin libmusepack_decoder: file not found
Can't load plugin libspeex_decoder: file not found
Can't load plugin libwavpack_decoder: file not found
Running the server...
Trying JACK...
Trying ALSA...
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
Trying OSS...

FATAL_ERROR: No valid sound driver!

FATAL_ERROR: Server exited!

**Comment by yuk7** [comment]
It is a WSL specification. 
If you want to use PulseAudio, please run PulseAudio server on Windows and communicate with TCP.

https://www.freedesktop.org/wiki/Software/PulseAudio/Ports/Windows/Support/

**Comment by PhilDim1** [comment]
I'm not even sure how I ended up getting this to work in the end, but it works fine. I don't think it was ever an issue with Arch, possibly not even WSL but most likely me goofing something trivial.
