### ISSUE TITLE
Unable to compile 32 bit packages on 64 bit architecture.

### ISSUE THREAD

**Issue by heller390** [yuk7/ArchWSL#134]
A simple c program when compiled gcc -m32 is not getting executed. Gives binary format error . Installed multilib-devel packages already. Having this issue on WSL arch only. 

https://del.dog/apunofidim.txt

**Comment by yuk7** [comment]
WSL doesn't have 32bit support.
I think it works with WSL2.

**Comment by heller390** [comment]
> 
> 
> WSL doesn't have 32bit support.
> I think it works with WSL2.

Is it a limitation or can be added in future?

**Comment by yuk7** [comment]
That is technically limitation.
It cannot be fixed by anyone other than Microsoft.

https://docs.microsoft.com/en-us/windows/wsl/faq#what-processors-does-wsl-support

**Comment by heller390** [comment]
> 
> 
> That is technically limitation.
> It cannot be fixed by anyone other than Microsoft.
> 
> https://docs.microsoft.com/en-us/windows/wsl/faq#what-processors-does-wsl-support

https://github.com/microsoft/wsl/issues/2468#issuecomment-374904520
Is this still plausible in arch?

**Comment by yuk7** [comment]
You can also use qemu for emulation.
but Arch Linux uses systemd for manage binfmt,there isn't update-binfmts command.
