### ISSUE TITLE
[resolved-ish] default-user HRESULT:0x80004005

### ISSUE THREAD

**Issue by BananaLoaf** [yuk7/ArchWSL#137]
**Issue**
Executing ```.\Arch.exe config --default-user almighty``` results in
```
ERROR
HRESULT:0x80004005
Press any key to continue...
```
Run as Administrator doesn't help

**Enviroment:**
 -Microsoft Windows [Version 10.0.18363.836]
 - Security Software: Win Defender
 - WSL 1
 - ArchWSL 20.4.3.0
 - ArchWSL Installer type: zip and appx, both give that error
 - Launcher version 20040300

**Comment by BananaLoaf** [comment]
I guess I had to create a user myself?

**Comment by yuk7** [comment]
Yes.  You must create the user yourself.
