### ISSUE TITLE
Don't suggest placing the certificate "Trusted Root Certification Authorities"

### ISSUE THREAD

**Issue by ghost-of-turek** [yuk7/ArchWSL#138]
https://github.com/yuk7/ArchWSL/wiki/Install-Certificate#4-select-trusted-root-certification-authorities-and-ok

Installation of packaged apps doesn't require the certificate to be stored in "Trusted Root Certification Authorities". The certificate should be instead placed in "Trusted Packaged App Installation Authorities" to minimize potential risks.

**Comment by yuk7** [comment]
Thank you!
I'll correct the document later.

**Comment by colwellkr** [comment]
I'm not sure if it's a root CA issue or the store, but placing the cert in the "Trusted Packaged App Installation Authorities" store resulted in this error when I tried to install.

![image](https://user-images.githubusercontent.com/8947323/87168729-ede33a80-c29c-11ea-8e03-8628e4d0ec4e.png)
(0x800B0109)
