### ISSUE TITLE
Arch has stopped echoing after calls to the executable

### ISSUE THREAD

**Issue by ComfyVolcel** [yuk7/ArchWSL#141]
**Describe the issue**
The executable has stopped responding to calls to it; leaving the powershell calls looking like this:
```
PS C:\WINDOWS\system32> arch.exe
PS C:\WINDOWS\system32>_
```
or just exits out of the window if opened from the documents bar.

The only output that looks like an error/indication message is:
```
PS C:\WINDOWS\system32> wsl.exe -u root Arch
/bin/bash: Arch: command not found
```
(with normal -u {default-user} calls leading to said issue);
or:
```
PS C:\WINDOWS\system32> arch.exe config --default-user {username}
ERROR
HRESULT:0x80004005
Press any key to continue...h
PS C:\WINDOWS\system32>
```
There are also (not screenshotted/easily documentable) outputs of /bin/bash/ not existing errors when i edited/set my ``passwd``.

**To Reproduce**
The only aberrations i could note about the process is that I may have needlessly went through the issue #7 fixes from the wiki; I have also not set up pacman because the issue arose before i could address it.

**Expected Behaviour**
There is an output from the console or the executable window and a /bin/bash file folder in the appx/tar files.

**Enviroment:**

    Windows build number: V1903 , B18362.418
    Security Software: None
    WSL version 1/2: WSL1
    ArchWSL version: 20.4.3.0
    ArchWSL Installer type zip/appx/other clean/update: zip
    Launcher version [e.g. 19030700] (Type Arch.exe version at a Command Prompt): 20040300

**Additional Context:**
It may also be a possibility that Git is interfering with Arch's pathing; there is no /bin/bash/ file folder to speak of and i have no idea whether this error will be solved with a file folder as i tried that with the ``passwd`` errors that i didnt log in ``ctrl+v`` to notes and a similar error was still echoed to console.

**Comment by yuk7** [comment]
Please try `wsl.exe -u root -d Arch` for login to wsl in root.
Is the passwd setting really correct?
Can you show me your /etc/passwd?

**Comment by ComfyVolcel** [comment]
/etc/passwd/ :
```
root:x:0:0::/root:/bin/bash
bin:x:1:1::/:/usr/bin/nologin
daemon:x:2:2::/:/usr/bin/nologin
mail:x:8:12::/var/spool/mail:/usr/bin/nologin
ftp:x:14:11::/srv/ftp:/usr/bin/nologin
http:x:33:33::/srv/http:/usr/bin/nologin
nobody:x:65534:65534:Nobody:/:/usr/bin/nologin
dbus:x:81:81:System Message Bus:/:/usr/bin/nologin
systemd-journal-remote:x:982:982:systemd Journal Remote:/:/usr/bin/nologin
systemd-network:x:981:981:systemd Network Management:/:/usr/bin/nologin
systemd-resolve:x:980:980:systemd Resolver:/:/usr/bin/nologin
systemd-timesync:x:979:979:systemd Time Synchronization:/:/usr/bin/nologin
systemd-coredump:x:978:978:systemd Core Dumper:/:/usr/bin/nologin
uuidd:x:68:68::/:/usr/bin/nologin
{username}:x:1000:1000::/home/{username}:/bin/bash/
```
also; the set-up of pacman-key yielded some errors when i tried and successfully logged into root from ``wsl.exe -u root -d Arch`` (i realise now that i missed the ``-d`` flag) which may be related to this but i do not know.

**Comment by yuk7** [comment]
I think last row of passwd is wrong.
/bin/bash is not a directory.
Please edit:
```
{username}:x:1000:1000::/home/{username}:/bin/bash/
```
↓
```
{username}:x:1000:1000::/home/{username}:/bin/bash
```

**Comment by ComfyVolcel** [comment]
it works now; thanks!
