### ISSUE TITLE
"fakeroot is in IgnorePkg/IgnoreGroup" warning when setting up AUR in WSL2

### ISSUE THREAD

**Issue by lackovic** [yuk7/ArchWSL#142]
Using ArchWSL on WSL2 and following the [getting started](https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started) steps in AUR wiki, I get the following warning on:

```
$ sudo pacman -S --needed base-devel
:: fakeroot is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
```

I noticed there is a [Customized Arch Linux for WSL2](https://github.com/yuk7/ArchWSL2) but it is still under developing and testing. For the time being, can I safely answer yes to this question or is there any other recommended way to setup AUR?

**Comment by yuk7** [comment]
If you use WSL2,WSL does not necessarily require fakeroot-tcp.
Edit `/etc/pacman.conf` and remove fakeroot from conf's IgnorePkg and `sudo pacman -S fakeroot` to replace fakeroot-tcp with fakeroot.

**Comment by yuk7** [comment]
You can also answer N to that (Install anyway?) question.
The function of fakeroot is provided by the built-in fakeroot-tcp.
