### ISSUE TITLE
makepkg -si throws a build error due to missing permissions to rename a file

### ISSUE THREAD

**Issue by coldspark29** [yuk7/ArchWSL#145]
**Please fill out the below information:**
**Describe the issue**
I was trying to build yay and I got a message related to go, that it couldn't rename a file. This happens every time I try to run makepkg. Thus I can't use the AUR, which is problem. Is this a known issue? How can I fix this?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Enviroment:**
 - Windows 1803
 - Security Software: McAfeeSuite
 - WSL version 1/2: WSL1
 - ArchWSL version: I downloaded the one form here and performed a full upgrade
 - ArchWSL Installer type zip
 - Launcher version: Doesn't give me the version when I type Arch.exe

**Comment by ntaraujo** [comment]
I think I had the same problem.
Try `pacman -Syu`.

**Comment by yuk7** [comment]
The permissions cannot be changed when the command is executed on the Windows directory(/mnt/*).
Execute the command in the Linux directory(e.g. /home/*)
