### ISSUE TITLE
using SysVinit instead of systemd

### ISSUE THREAD

**Issue by VPraharsha03** [yuk7/ArchWSL#148]
Is it a possible thing to replace systemd with sysvinit ? If it is possible, please provide the right procedure. I'm unable to connect to the XFCE desktop via RDP. 

I've tried enabling and starting `xrdp-sesman.service` and `xrdp.service` services several times... the xrdp window opens up but [fails to connect](https://wtf.roflcopter.fr/pics/FZhEXYRx/0k587WGj.jpg)

I'm on WSL1

If i'm missing any additional steps with xrdp, please guide me

**Comment by VPraharsha03** [comment]
Please delete the issue

**Comment by marad** [comment]
@VPraharsha03 Have you had any luck with starting xrdp?
