### ISSUE TITLE
Skipped reloading System Manager Configuration

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [yuk7/ArchWSL#150]
**Describe the issue**
When I install packages using pacman, it skips reloading the SystemManager Configuration. The reason being `Current root is not booted.` I can very easily ignore this because it has not caused any problems as of yet.

**To Reproduce**
I don't exactly know which packages cause this problem, but the packages that have something to do with the system cause this issue. 

**Expected behaviour**
It should refresh the System Manager Configuration.

**Enviroment:**
 - Windows build number: 10.0.19042.450
 - Security Software: NA
 - WSL version 1/2: WSL 2
 - ArchWSL version 20.4.3.0
 - ArchWSL Installer type zip clean
 - Launcher version 20040300

**Comment by nisarg-ujjainkar** [comment]
I moved to ArchWSL2 and this issue is not present there so I am closing this issue.

**Comment by TobiTenno** [comment]
Could you link to ArchWSL2? I'm still on this one and haven't found a migration path.

**Comment by Erven2016** [comment]
I have same problem like you when I am installing package via pacman:

```txt
erven2016@DESKTOP-14AL006 ~ $ sudo pacman -S openssh
[sudo] password for erven2016:
warning: openssh-9.0p1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) openssh-9.0p1-1

Total Installed Size:  4.19 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                           [########################################] 100%
(1/1) checking package integrity                                         [########################################] 100%
(1/1) loading package files                                              [########################################] 100%
(1/1) checking for file conflicts                                        [########################################] 100%
:: Processing package changes...
(1/1) reinstalling openssh                                               [########################################] 100%
:: Running post-transaction hooks...
(1/3) Reloading system manager configuration...
  Skipped: Current root is not booted.
(2/3) Creating temporary files...
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
(3/3) Arming ConditionNeedsUpdate...
```
