### ISSUE TITLE
cant run systemcl services

### ISSUE THREAD

**Issue by sentakuhm** [yuk7/ArchWSL#152]
when run a systemd command like:
`$sudo systemctl start mariadb.service` 
output:
`System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down`

**Comment by eNV25** [comment]
https://github.com/yuk7/ArchWSL/wiki/Known-issues#systemdsystemctl

**Comment by dobedobedo** [comment]
ginie-systemd in AUR has been removed for some reason.

**Comment by arlllk** [comment]
[The issue on the genie repo](https://github.com/arkane-systems/genie/issues/82)
[The PKGBUILDs](https://gist.github.com/arlllk/7001c521de601f01735af5ca440f03ae)
[And the very dumb reason](https://lists.archlinux.org/pipermail/aur-requests/2020-September/044860.html)
