### ISSUE TITLE
Opens as login

### ISSUE THREAD

**Issue by GilReiter** [yuk7/ArchWSL#155]
**Describe the issue**
When I open a terminal it defaults to a `login shell`.

**To Reproduce**
Open a terminal instance

**Expected behavior**
An interactive shell is instantiated and my `~/.bashrc` script is run.

**Environment:**
 - Windows build number: 10.0.20206.1000
 - WSL version: 2
 - ArchWSL version: 20.4.3.0
 - ArchWSL Installer type: zip
 - Launcher version: press on exe / create `Arch` tab in wt

**Additional context**
I mainly just want the `~/.bashrc` to be run, for now, I'll just put the code into `~/.bash_profile`

**Comment by avail** [comment]
add `[[ -f ~/.bashrc ]] && . ~/.bashrc` to your .bash_profile
