### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by BLucky-gh** [yuk7/ArchWSL#158]
**Describe the issue**
When I run Arch.exe from explorer, no matter if I run it as Admin or not I get this in the window:

```
Installing...
ERROR:Installation Failed!
HRESULT:0xc03a001a
Press any key to continue...
```

**To Reproduce**
Run Arch.exe?

**Expected behavior**
I expect it to just install and that's it

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.19041.572]
 - Security Software: Windows Defender
 - WSL version 1/2: WSL2
 - ArchWSL version 20.10.31.0
 - ArchWSL Installer type zip clean
 - Launcher version wsldl, version 20100500

**Comment by yuk7** [comment]
The cause may be that the folder is compressed or encrypted.
Please disable compression in the properties of Explorer.

**Comment by BLucky-gh** [comment]
Thanks! that turned out to be the issue. Do I only need to disable compression on the arch installer or any other folders?

**Comment by yuk7** [comment]
Yes.
Disable compression the Arch folder.
Also, the folder must be granted full access.
