### ISSUE TITLE
Genie-systemd doesn't exist in AUR, but is recommended in the Known Issues page

### ISSUE THREAD

**Issue by BLucky-gh** [yuk7/ArchWSL#159]
**Please fill out the below information:**
genie-systemd which is linked in the known issues page of this repo does not exist in the AUR anymore (https://aur.archlinux.org/packages/genie-systemd)

**To Reproduce**
Check https://aur.archlinux.org/packages/genie-systemd

**Expected behavior**
The known issues page links to an existing repo

**Comment by yuk7** [comment]
Ok.
I'll replace it.

**Comment by BLucky-gh** [comment]
Thanks, and please let me know when you do.

**Comment by arlllk** [comment]
I was the maintainer of the packages, they where took down for being WSL exclusive, the last version of the PKGBUILD are [here](https://gist.github.com/arlllk/7001c521de601f01735af5ca440f03ae), the git version and the last released version.

**Comment by yuk7** [comment]
@arlllk Thank you!

**Comment by BLucky-gh** [comment]
Oh, I wasn't aware of that. Thanks for the link., but don't you need the tarball to install the package or am I wrong?

**Comment by yuk7** [comment]
I updated wiki page.
