### ISSUE TITLE
Can't listen on tcp port

### ISSUE THREAD

**Issue by nadoo** [yuk7/ArchWSL#16]
Install and run glider:
```
pacman -S glider
glider -verbose -listen :8443
```
it  will listen on both tcp and udp port 8443.

then check it in windows command line:
```
netstat -an | findstr 8443
  UDP    0.0.0.0:8443           *:*
  UDP    [::]:8443              *:*
```
the tcp port 8443 was not opened.

**Comment by yuk7** [comment]
Probably this issue same as https://github.com/Microsoft/WSL/issues/1554.
that issue was solved in newest insider builds...

**Comment by nadoo** [comment]
Thanks! I'll follow that issue to get the newest info.

**Comment by yuk7** [comment]
Ok,Thank you for your report.
