### ISSUE TITLE
Wiki change request: minor info change about `arch install`

### ISSUE THREAD

**Issue by escape0707** [yuk7/ArchWSL#160]
> This is not a bug/issue report.

Today I tried to test whether `scoop-extras` latest changes to the `manifest.json` provided a safe way to update archwsl. And when I need to restore my original archwsl's `backup.tar.gz`, I found that only supply a full absolute path will work, and [the relative path showed in wiki](
https://github.com/yuk7/ArchWSL/wiki/How-to-Use(for-Installed-Instance)#how-to-backup-instance-image) simply do nothing.

I think it might be better to clarify this in the wiki, too, but I have no authority to edit that page.

( I got stucked by this during the test phase for about 30 minutes. Dumb as me, Orz...)

**Comment by yuk7** [comment]
I have set the wiki to be editable.
Thank you for your contribution.

**Comment by escape0707** [comment]
Edited in wiki. Love your work, please accept my appreciation~

**Comment by yuk7** [comment]
I have created an Organization for a project related to this.
If you continue to contribute to the documentation, can I invite you to the team?
Thanks.

**Comment by yuk7** [comment]
@escape0707 
I have created an Organization for a project related to this.
I plan to move the document repository there.
If you continue to contribute to the documentation, can I invite you to the team?

**Comment by escape0707** [comment]
Of course! Why not! I'd like to help with documenting and also developing and testing if there are things that I'm capable of!

（実は今、日本語を勉強しています……

**Comment by yuk7** [comment]
Thank you so much!
I sent invite mail to you. 

(ありがとう..! そうなんですね、それはすごいです!
よかったらまた日本語で話しましょうねヽ(。ゝω・)ノ

**Comment by escape0707** [comment]
いいですね！これからお世話になります。どうぞよろしくお願いします。
