### ISSUE TITLE
pacman -Syyu gives errors in arch WSL

### ISSUE THREAD

**Issue by IIWare** [yuk7/ArchWSL#161]
Is there any solution?

`:: Synchronizing package databases...`
`error: failed retrieving file 'core.db' from mirrors.kernel.org : Could not resolve host: mirrors.kernel.org`
`error: failed to update core (invalid url for server)`
`error: failed retrieving file 'extra.db' from mirrors.kernel.org : Could not resolve host: mirrors.kernel.org`
`error: failed to update extra (invalid url for server)`
`error: failed retrieving file 'community.db' from mirrors.kernel.org : Could not resolve host: mirrors.kernel.org`
`error: failed to update community (invalid url for server)`
`error: failed to synchronize all databases`

It would be nice if you know the solution. thanks.

**Comment by yuk7** [comment]
Can other software in ArchWSL connect to the Internet?

Try `ping mirrors.kernel.org`

**Comment by IIWare** [comment]
@yuk7 

`ping: mirrors.kernel.org: Temporary failure in name resolution`

**Comment by yuk7** [comment]
hmm...
So what about `ping 8.8.8.8`?

**Comment by IIWare** [comment]
@yuk7 I closed and reopened the WSL Arch and tried `ping mirrors.kernel.org`, here is the result:
`PING mirrors.pdx.kernel.org (198.145.21.9) 56(84) bytes of data.`
`64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=1 ttl=44 time=321 ms`
`64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=3 ttl=44 time=294 ms`
`64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=4 ttl=44 time=295 ms`
`64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=5 ttl=44 time=278 ms`
`64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=6 ttl=44 time=278 ms`
`64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=7 ttl=44 time=265 ms`

>hmmm...
>So what about `ping 8.8.8.8` ?

`PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.`
`64 bytes from 8.8.8.8: icmp_seq=1 ttl=113 time=67.4 ms`
`64 bytes from 8.8.8.8: icmp_seq=2 ttl=113 time=46.1 ms`
`64 bytes from 8.8.8.8: icmp_seq=3 ttl=113 time=74.3 ms`

**Comment by IIWare** [comment]
I also reopened arch wsl and tried `pacman -Syyu`

`:: Synchronizing package databases...`
`error: failed retrieving file 'core.db' from mirrors.kernel.org : Failed to connect to mirrors.kernel.org port 443: Connection timed out`
`error: failed to update core (download library error)`
`error: failed retrieving file 'extra.db' from mirrors.kernel.org : Failed to connect to mirrors.kernel.org port 443: Connection timed out`
`error: failed to update extra (download library error)`
`error: failed retrieving file 'community.db' from mirrors.kernel.org : Failed to connect to mirrors.kernel.org port 443: Connection timed out`
`error: failed to update community (download library error)`
`error: failed to synchronize all databases`

**Comment by yuk7** [comment]
It looks like the DNS resolver wasn't working.
Try pacman again.

**Comment by yuk7** [comment]
Ok.

**Comment by yuk7** [comment]
You can also choose to use another mirror server.
Try commenting out a mirror server near you in /etc/mirrorlist`

**Comment by IIWare** [comment]
I will try

**Comment by IIWare** [comment]
sorry for no response, I ran into issues that's not related to this topic, Now I will try

**Comment by IIWare** [comment]
now I can try

**Comment by IIWare** [comment]
I forgot to mention that the pacman error is gone, however I deleted the arch wsl and then re downloaded it (not appx) but I ran into another error, when I start arch.exe it says "The system cannot find the file specified." so I will now make another issue.

**Comment by sheeepdev** [comment]
I tried to close and change the mirrors but it does not work. Also, I sometimes get errors like that when installing packages on pacman, for example, I got an error "Connection too slow" and more and I don't know how to fix them.

**Comment by escape0707** [comment]
@sheeepdev do you mean that you are experiencing the same problem as OP?

**Comment by sheeepdev** [comment]
> @sheeepdev do you mean that you are experiencing the same problem as OP?

Yes

**Comment by escape0707** [comment]
It sounds like a pure Pac-Man confit problem. You should post your error log first. Andy maybe try some other mirrors. Guide can be found in ArchWiki.

**Comment by sheeepdev** [comment]
Pacman on ArchWSL in general is sometimes buggy and gives me random errors, 404, 403, and this and more

**Comment by escape0707** [comment]
@sheeepdev I'd really likely to suggest you to first try some other mirrors like those hosted by your local / contries' universities. Did you do that?

**Comment by sheeepdev** [comment]
> @sheeepdev I'd really like to suggest you to first try some other mirrors like those hosted by your local / contries' universities. Did you do that?

Yes.

**Comment by escape0707** [comment]
@sheeepdev And you tried ping the mirror you chose?
Please paste more log (pacman, ping) to enable people to help you identifying what's the problem.
