### ISSUE TITLE
pacman Issue: SSL certificate problem

### ISSUE THREAD

**Issue by danielcherubini** [yuk7/ArchWSL#162]
**Describe the issue**
Looks like SSL certificate issues
```
➜ sudo pacman -Syu
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from mirrors.kernel.org : SSL certificate problem: unable to get local issuer certificate
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from mirrors.kernel.org : SSL certificate problem: unable to get local issuer certificate
error: failed to update extra (download library error)
error: failed retrieving file 'community.db' from mirrors.kernel.org : SSL certificate problem: unable to get local issuer certificate
error: failed to update community (download library error)
error: failed to synchronize all databases
```

Looking at this error, it seems others have resolved it by disabling ipv6.. however I cannot find any kernel modules to disable this, and it seems that it's ignoring systemd networking  (i haven't installed any systemd workaround)

**To Reproduce**
run pacman

**Expected behavior**
pacman to work

**Enviroment:**
 - Windows build number: 1909 18363.1198
 - Security Software: ZScaler
 - WSL version 1/2: 2
 - ArchWSL version 20.10.31.0
 - ArchWSL Installer type zip/appx/other clean/update [e.g. appx update] appx
 - Launcher version 20100500

**Comment by danielcherubini** [comment]
What's interesting is my other pc, with windows 20H2 doesn't have these issues.. I backed up it's copy of arch, and installed it over this one, and still the issue persists.

**Comment by danielcherubini** [comment]
Just uninstalled arch and reinstalled, same issue.

**Comment by danielcherubini** [comment]
i installed ubuntu, and found the same issue, this time with curl..., i installed the curl .pem and ran `update-ca-certificates` which doesn't exist in arch, i found `update-ca-trust` but it didn't work

**Comment by danielcherubini** [comment]
I changed my mirror, looks like something was wrong with mirrors.kernel.org's certs

**Comment by yuk7** [comment]
Ok
Thank you for your info.

**Comment by yuk7** [comment]
Thank you for your info.

But are you using ZScaler's TLS inspection?
Please try other https communication.

**Comment by yuk7** [comment]
The TLS-inspected communication is re-encrypted with another CA certificate.

**Comment by danielcherubini** [comment]
Thanks, yeah it's a work computer, and I don't have access to any of the zscaler configs.. however, I've seen another thread elsewhere, where someone noted disabling his firewall solved the issue.

I have something to now go to our security team with... Thanks :D I'll update this if disabling tls inspection on zscaler solves the issue.

**Comment by yuk7** [comment]
Ok.
If necessary, please refer to the link below.
https://wiki.archlinux.org/index.php/User:Grawity/Adding_a_trusted_CA_certificate#System-wide_–_Arch,_Fedora_(p11-kit)

**Comment by yuk7** [comment]
Ok.

However, there was something I forgot to say.

Apparently, `update-ca-certificates` doesn't apply in Arch.
If necessary, please refer to the link below.
https://wiki.archlinux.org/index.php/User:Grawity/Adding_a_trusted_CA_certificate#System-wide_–_Arch,_Fedora_(p11-kit)

**Comment by danielcherubini** [comment]
That last bit solved the issues when I used the corp certs!

closing

**Comment by yuk7** [comment]
I'm glad to hear that.

I thought it should be documented.
