### ISSUE TITLE
Discrepancies in kernel version

### ISSUE THREAD

**Issue by tigerjack** [yuk7/ArchWSL#163]
**Describe the issue**
Discrepancies between `uname -r` and `linux-headers`. This prevents the usage of, f.e., `modprobe` or the standard `uname -r` in scripts that generates kernel modules.

**To Reproduce**
```
$>uname -r
4.19.128-microsoft-standard
$>pacman -Q --info linux-headers
pacman -Q --info linux-headers
Name            : linux-headers
Version         : 5.9.8.arch1-1
```
**Expected behavior**
Arch should correctly detect/overwrite the used kernel.

**Enviroment:**
 - Windows build number: 10.0.20262.1
 - Security Software: ?
 - WSL version 1/2:  WSL2
 - ArchWSL version: 20.10.31.0
 - ArchWSL Installer type zip/appx/other clean/update: scoop
 - Launcher version: wsldl, version 20100500

**Comment by yuk7** [comment]
Since the WSL2 instance is a container, modprobe will not work.
You can change kernel vmlinux file with `%USERPROFILE%\.wslconfig`.
