### ISSUE TITLE
Error trying to open an SSH_AUTH_SOCKET with socat in WSL2

### ISSUE THREAD

**Issue by ferrazpedro** [yuk7/ArchWSL#165]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
I'm trying to use the solution proposed by https://github.com/rupor-github/wsl-ssh-agent to use socat and npiperelay to open a socket to use my ssh keys directly in my ArchWSL instance. It does work with both Ubuntu and Fedora Remix on WSL, but if I try to use it with ArchWSL it says "RTNETLINK answers: Invalid argument" and then operation invalid.

**To Reproduce**
Add this to your .bashrc:

export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock
ss -a | grep -q $SSH_AUTH_SOCK
if [ $? -ne 0   ]; then
    rm -f $SSH_AUTH_SOCK
    ( setsid socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"$HOME/winhome/.wsl/npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork & ) >/dev/null 2>&1
fi

**Expected behavior**
It should give acess to my ssh keys from Windows openssh inside ArchWSL.

**Screenshots**

**Enviroment:**
 - Windows build number: Microsoft Windows [version 10.0.19042.630]
 - Security Software: Windows Defender
 - WSL version 1/2: WSL2
 - ArchWSL version 20.10.31.0
 - ArchWSL Installer type Clean appx
 - Launcher version 20100500

**Additional context**

**Comment by carpenike** [comment]
I have the same problem. It's the ss command:

```
set -x SSH_AUTH_SOCK $HOME/.ssh/agent.sock
#ss -a | grep -q $SSH_AUTH_SOCK
if [ $status != 0 ]
  rm -f $SSH_AUTH_SOCK
  setsid nohup socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:/c/tools/wsl-ssh-pageant/wsl2-ssh-pageant.exe >/dev/null 2>&1 &
end

set -x GPG_AGENT_SOCK $HOME/.gnupg/S.gpg-agent
#ss -a | grep -q $GPG_AGENT_SOCK
if [ $status != 0 ]
  rm -rf $GPG_AGENT_SOCK
  setsid nohup socat UNIX-LISTEN:$GPG_AGENT_SOCK,fork EXEC:"/c/tools/wsl-ssh-pageant/wsl2-ssh-pageant.exe --gpg S.gpg-agent" >/dev/null 2>&1 &
end
```

**Comment by carpenike** [comment]
And, in particular, the grep part of the command... which seems strange.

**Comment by danielwagn3r** [comment]
I also tried my prior to wsl-ssh-pageant use tool, https://github.com/vuori/weasel-pageant and it doesn't work as well.

**Comment by danielwagn3r** [comment]
I've tested weasel-pageant (https://github.com/vuori/weasel-pageant) and this works, however it's unmaintained currently.

**Comment by judemille** [comment]
Also experiencing this issue.

**Comment by ferrazpedro** [comment]
This error has stopped happening recently, so i'm closing this issue.
