### ISSUE TITLE
Arch Linux exited when multiple shell instance exists

### ISSUE THREAD

**Issue by Asiimoviet** [yuk7/ArchWSL#166]
I run Arch LInux WSL using Windows Terminal: 
![image](https://user-images.githubusercontent.com/66727875/100088929-e0b19b80-2e8b-11eb-9279-656d6bb5aae5.png)
However when I create multiple tabs of Arch Linux, the terminal crashes.

I tried a few troubleshoot, including changing the shell from zsh back to bash, and changing default user back to root, none of them get the issue fixed.

Trigger: Multiple Tabs (from 2 to 3)

Expected Situation: Terminal Crashes

Environment: 
- Windows Build: 10.0.19041.630
- Security Software: N/A
- WSL version: WSL1
- ArchWSL version: 20.10.31.0
- Installer: appx
- Launcher vversion: 20100500

**Comment by yuk7** [comment]
It's a mystery. 
Do other WSL distributions have the same issue?

**Comment by Asiimoviet** [comment]
I'mma try to install other WSLs to see if there are similar reasons.
BTW: I remembered that there was a repository for Arch Linux running WSL2, but I cannot find it now.

**Comment by Asiimoviet** [comment]
Solved: I changed my config file and let it run arch.exe to create new shell instance
![image](https://user-images.githubusercontent.com/66727875/100091935-430c9b00-2e90-11eb-865f-2da0723ec723.png)

make sure that you have set arch.exe config --default-term default instead of wt, because that will cause your windows terminal to bootloop (took me a while to delete the process)

**Comment by yuk7** [comment]
I'm glad I solved it for the time being.
I think bootloop is a bug.  I'll fix it.
