### ISSUE TITLE
Where is the WSL2 Version?

### ISSUE THREAD

**Issue by Asiimoviet** [yuk7/ArchWSL#167]
I couldn't find a WSL2 version of ArchWSL

After downloading the latest release (appx) and installed it, it is still wsl1.

**Comment by yuk7** [comment]
ArchWSL also works with WSL2.
run `wsl --set-version Arch 2` in shell

**Comment by Asiimoviet** [comment]
@yuk7 I ran this command and here comes an error :(

![image](https://user-images.githubusercontent.com/66727875/100098666-5708ca80-2e99-11eb-8a42-fad405ef0a6b.png)
Error: 0x80041002

**Comment by yuk7** [comment]
Make sure the Windows virtualization platform and Intel-VT/AMD-V are enabled.

**Comment by Asiimoviet** [comment]
It's already enabled @yuk7

**Comment by yuk7** [comment]
hmm...
Could you run `msinfo32.exe` and show me the related items of Hyper-V in System Summary?

**Comment by Asiimoviet** [comment]
@yuk7 sure thing

processor: intel core i7 9700

summary:
名称	Hyper-V RAW	
无连接服务	否	
保证送达	是	
保证顺序	是	
最大地址大小	36 字节	
最大消息大小	0 字节	
面向消息	否	
最小地址大小	36 字节	
面向虚拟流	否	
支持广播	否	
支持连接数据	否	
支持断开连接数据	否	
支持加密	否	
支持加速数据	否	
支持特权关闭	是	
支持保证的带宽	否	
支持多播	否	
(do i need to set my system to english so that it can display terms in english?)

**Comment by yuk7** [comment]
Don't worry.
Changing the settings is troublesome, so you can leave it as it is.
I'm Japanese and can read a little Chinese characters.

**Comment by yuk7** [comment]
Probably,It's another page. 
The System Summary is at the top of the left sidebar.

**Comment by Asiimoviet** [comment]
@yuk7 do you mean these terms?

基于虚拟化的安全性	正在运行
安全属性要求基于虚拟化的安全性	
安全属性可使用基于虚拟化的安全性	基本的虚拟化支持, DMA 保护, UEFI 代码只读, SMM Security Mitigations 1.0, 基于模式的执行控制
已配置基于虚拟化的安全服务	
正在运行基于虚拟化的安全服务	
设备加密支持	设备自动加密失败的原因: TPM 不可用, 不支持 PCR7 绑定, 硬件安全测试界面失败，设备未处于现代待机模式, 检测到不允许使用的具有 DMA 功能的总线/设备, TPM 不可用
已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。

**Comment by yuk7** [comment]
yes.
It seems that those items are hidden...
I couldn't see the information I wanted.

**Comment by Asiimoviet** [comment]
@yuk7 what information do you want? I can find it for ya

**Comment by escape0707** [comment]
@Asiimoviet please look at [this issue](https://github.com/microsoft/WSL/issues/5329).
And please try to avoid communicate using Chinese on GitHub... Maybe you should consider switch your Windows display language to English for English troubleshooting info.
既然您再用WSL，相信也是有此实力的！❤

**Comment by escape0707** [comment]
I'm running a ArchWSL on WSL2 and this is what I get from `msinfo32.exe`, just for your infomation:

```
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
```

**Comment by yuk7** [comment]
yep.
I thought I could see the status of Hyper-V&Virtualization from there, but it was my mistake.

**Comment by Asiimoviet** [comment]
@escape0707 I tried and did not work. I completely shut down windows defender and firewall. Quitted all my proxy.

@yuk7 btw i enabled the virtualmachineplatform feature through this command 
``` shell
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```
and tried that again. Unfortunately that did not work. Still getting the same 0x80041002 error.

**Comment by escape0707** [comment]
Are you sure you tried everything people suggested there? Like check whether port 53 is free and backup you WSL 1 Arch - uninstall - completely disable WSL feature and re-enable - reinstall and recover from backup?

**Comment by Asiimoviet** [comment]
![image](https://user-images.githubusercontent.com/66727875/100305956-377aba80-2fdd-11eb-89e3-c6494e977d54.png)
@escape0707 I set the default version of wsl to 2 and uninstalled arch. after then, re installing it using arch.exe and the same error popped out.

**Comment by escape0707** [comment]
https://github.com/microsoft/WSL/issues/5329#issuecomment-638982097
https://github.com/microsoft/WSL/issues/5329#issuecomment-639146874

**Comment by Asiimoviet** [comment]
@escape0707 I have read through that issue page and found out that most of them are having problem with that COMODO firewall. Unfortunately I don't have that installed. Interestingly, one of the post mentioned that the comodo firewall is having problem with something called the loopback problem. I am using clash for windows as my proxy and it has that problem as well (that makes my UWP apps unable to connect to the internet). I tried shutting down and completely uninstalled clash but that didn't work even after a reboot of my system.

About the 2 comment you posted:
1. I tried running that command but it turns out that there is nothing occupying my 53 port:
``` shell 
Get-NetUDPEndpoint: No MSFT_NetUDPEndpoint objects found with property 'LocalPort' equal to '53'.  Verify the value of the property and retry.
Get-Process: Cannot bind argument to parameter 'Id' because it is null.
```
2. I took the WSL log from Windows Feedback, hoping that might help:
https://aka.ms/AAaf293

**Comment by escape0707** [comment]
@Asiimoviet Well, I'm not a Microsoft employee so I don't have the authority to view your feedback, you should check " Save a local copy of xxxx" 
![image](https://user-images.githubusercontent.com/11014745/100406730-99045d00-30a1-11eb-925a-c4d31153f720.png)
and attach that log file here. 

By the way, there should be 3 `.etl` file in it and you can [download Windows Performance Analyzer](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiL4LOm4aHtAhXr_mEKHVx-AdAQFjABegQIAhAC&url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fp%2Fwindows-performance-analyzer%2F9n0w1b2bxgnz&usg=AOvVaw2x6fOWXmihc4B0AA5SNU09) to inspect it.

Talking about Clash For Windows, I have it on my device, too and it seems not causing any WSL problem. But you can try to remove all app's loopback restriction anyway since you also experienced UWP app proxy failure. The CFW proxy software has already included a utility to do this.

**Comment by Asiimoviet** [comment]
@escape0707 appx

**Comment by escape0707** [comment]
I used scoop and zip. Maybe you want to give zip installation a try?

**Comment by Asiimoviet** [comment]
![image](https://user-images.githubusercontent.com/66727875/100410854-e0dbb200-30aa-11eb-9980-6f30d3fe285a.png)
![image](https://user-images.githubusercontent.com/66727875/100410856-e507cf80-30aa-11eb-8ace-92e470e43869.png)
omg, just encountered a situation which neither of wsl and arch.exe is responsive.

**Comment by Asiimoviet** [comment]
There are so many of those folders. I reran the capture and took the folder that is closest to the time i was doing the test.
See if this could help @escape0707 

[Critical_{1B96BCC2-1B1B-4_ce5eb7b0111624146853d1dedaaa1f66bf82b7ea_00000000_cab_d3331430-10c8-4b0d-8b81-841ffd9d92e1.zip](https://github.com/yuk7/ArchWSL/files/5606177/Critical_.1B96BCC2-1B1B-4_ce5eb7b0111624146853d1dedaaa1f66bf82b7ea_00000000_cab_d3331430-10c8-4b0d-8b81-841ffd9d92e1.zip)

**Comment by Asiimoviet** [comment]
I just tried the zip install and it doesn't work as well
![image](https://user-images.githubusercontent.com/66727875/100416655-f7d5d080-30b9-11eb-835d-fe4885e3cd7a.png)

**Comment by escape0707** [comment]
Oof, sorry, completely my bad: WSL team updated their `CONTRIBUTION.md` so that the original instruction to capture a shorter `.etl` log has been removed and they're recommending people to use the Feedback Hub app... I didn't realize that...
The original method to capture a log and some people identify the source of their problem is in [the older version of the `CONTRIBUTION.md`](https://github.com/microsoft/WSL/blob/2cb110aba644d0bb3ff8d6445448d4e08e11df78/CONTRIBUTING.md#8-detailed-logs). Sorry for not checking that by myself first and the waste of your time.
See if we can find something suspicious following the original way they tried.

**Comment by Asiimoviet** [comment]
![image](https://user-images.githubusercontent.com/66727875/100428046-5d33bc80-30ce-11eb-8fad-4211b69afc58.png)
Turns out other distro has the same issue. Imma go open a new issue in their wsl repo. thx for your help 👍 
@escape0707 @yuk7

**Comment by escape0707** [comment]
@Asiimoviet you should send these info into the issue I first referred before.

**Comment by Gako358** [comment]
WSL 2 requires an update to its kernel component I get when I try to update, both using the
```
wsl --set-version Arch 2
```
```
wsl --set-default-version 2
```

Both gives same error. Have turned on everything. I just dont get it.

**Comment by Gako358** [comment]
Never mind, had to man download kernel update. Working now wsl2

**Comment by mrbeardad** [comment]
What is the difference between WSL2 version in this repository and original ArchWSL2 in  [yuk7/container-systemd-init-tool](https://github.com/yuk7/container-systemd-init-tool/releases)
