### ISSUE TITLE
How to change default Arch path

### ISSUE THREAD

**Issue by tigerjack** [yuk7/ArchWSL#168]
I previously installed Arch on WSL2 using scoop. For disk-space issues, I decided to duplicate the arch installation to another partition with the `wsl export` and `wsl import` commands. In the near future, the idea is to delete the old wsl copy and use the new one. The procedure seems to have worked fine. The only problem is that `Arch.exe` still run the old installation. 

Is there any way I can modify the path in which the binary takes the default system? One of the main reason for that is that all the commands, including `Arch.exe config --default-user` can't be executed on the new system.

**Comment by yuk7** [comment]
The ArchWSL launcher (wsldl) uses the name of the exe as the instance name.
For example, if you import the name "Arch2" like this:
```
wsl --import Arch2 /path/to/inst exported.tar
```
You can run it by renaming the exe to "Arch2.exe".

**Comment by tigerjack** [comment]
Hey @yuk7, thanks for the quick reply. By analysing the files used by scoop, I made some additional changes. I'll leave them here as a reference. Assuming your `scoop` directory is `SCOOPDIR` (default `%USERPROFILE%\scoop`):

1. copied all `SCOOPDIR\shims\arch.{exe,ps1,shim}` into `SCOOPDIR\shims\arch2.{exe,ps1,shim}`.
2. copied `SCOOPDIR\apps\archwsl\current\arch.exe` into `SCOOPDIR\apps\archwsl\current\arch2.exe`
3. modified `SCOOPDIR\shims\arch2.{ps1,shim}` to point to the new location of point 2.

If you think there are no drawbacks with this, you can close the issues.
Thanks again for your help.

**Comment by yuk7** [comment]
Manipulating the Scoop directory directly is not recommended as it may cause unintended problems.
Scoop automatically generates shims and ps1.

I recommend copying only the exe to another directory and using it.

**Comment by tigerjack** [comment]
Noted. For now I'll just go with it and see what happens. In case of problems I'll try to put just the exe file in my bin dir.

**Comment by yuk7** [comment]
Ok.
