### ISSUE TITLE
Vhdx deleted with any update via scoop

### ISSUE THREAD

**Issue by 0m3rta13** [yuk7/ArchWSL#169]
**Describe the issue**
Everything works 100% fine. But if there is an update for archwsl in scoop the vhdx file is deleted and replaced with a new one.  I put the package on Hold so as to not update.
I saw there was a fix mentioned an update or two ago mentioning this problem. I avoided updating but when I tried it today it deleted my vhdx again

**To Reproduce**
Use everything as per normal. If an update is available on scoop in extras bucket then update it. Upon update completion the vhdx is gone and a new one in its place

**Expected behavior**
Doesnt delete my Vhdx file

**Enviroment:**
 - Windows build number: [20201]
 - Security Software: [Windows Defender]
 - WSL version 1/2: [e.g. WSL2]
 - ArchWSL version [20.11.25.0]
 - ArchWSL Installer type: Soop

**Comment by escape0707** [comment]
I bet you upgraded from 20.10.31.0 right?
I feel sorry for the inconvenience  happened to you, but:
First this is purely a `scoop extras bucket` side problem and...
Secondly, I [mentioned that the PR](https://github.com/lukesampson/scoop-extras/pull/5048#issuecomment-723789410) that PR which fix the update problem is not a perfect solution.
Please take a look.
Anyway, if you have made a backup you can try to [recovery from it](https://wsldl-pg.github.io/ArchW-docs/How-to-Use/).

**Comment by yuk7** [comment]
It's possible that an unintended installation of the script was performed.
Data may not be created in persist if it is a (re-)installation after a failed initial setup in Scoop or after using clean command.

**Comment by 0m3rta13** [comment]
Hi. Thank you for your reply!

Sorry I should've mentioned that I did make a backup before I did the update so I didn't actually lose anything so there was no inconvenience caused at all. I simply switched out the new vhdx that was created with the one I'd backed up and I was back to normal. 

I mostly just posted this issue just to let you know it happened and cos I didn't see any other issue mentioning it. So if anyone is looking they might be sure to make backups first. 

Again, thank you for the response and also thank you for your work on this. Being able to use Arch within WSL has been such a lifesaver in so many ways and I am very appreciative of your efforts!

**Comment by yuk7** [comment]
I posted the patch to scoop-extra.
https://github.com/lukesampson/scoop-extras/pull/5224

**Comment by 0m3rta13** [comment]
> I posted the patch to scoop-extra.
> [lukesampson/scoop-extras#5224](https://github.com/lukesampson/scoop-extras/pull/5224)

wow that was quick.
I will give it a test over the weekend. 

I am going to close this issue for now, primarily because as you said it isn't exactly a fault with ArchWSL but with scoop (even though you are providing a workaround).

Will reply with an update after I've checked it out

Thanks again for your hard work @yuk7
