### ISSUE TITLE
directory /run/user/1000 does not exist

### ISSUE THREAD

**Issue by wang1zhen** [yuk7/ArchWSL#170]
Hi,

I was trying to run spacemacs with ArchWSL, and there goes an error message:

`File error: Creating directory, Permission denied, /run/user/1000`

Thus I looked into the /run/user directory, and find out that the /run/user/1000 does not exist, which is not understandable to me:

```shell
❯ whoami
wang1zhen
❯ ls -ali /run/user
total 0
24346 drwxr-xr-x 2 root root  40 Dec  4 11:47 .
24340 drwxr-xr-x 8 root root 160 Dec  4 11:47 ..
```

I'm currently running on WSL2, wondering if this could be an issue of WSL2 version?

```shell
PS C:\WINDOWS\system32> wsl -l -v
  NAME    STATE           VERSION
* Arch    Running         2
```

**Comment by wang1zhen** [comment]
After switching to WSL1 the issue remains. I guess there is nothing to do with WSL2.

**Comment by escape0707** [comment]
@wang1zhen I definitely should grab some operating system bible/textbook and drill through it, but...
https://unix.stackexchange.com/questions/162900/what-is-this-folder-run-user-1000
For what I can learn from Google search, this folder is "created by pam_systemd" and `pam_systemd` is for " Register user sessions in the systemd login manager". But both WSL1 and WSL2 don't come with `systemd` by default, so I think you might have to take some workaround with that first.
I personally think that VSCode with WSL remote connection is a good alternative if you don't want to spend time figuring out how to get `systemd` work.

**Comment by escape0707** [comment]
Take a look at [this part of the docs](https://wsldl-pg.github.io/ArchW-docs/Known-issues/#systemdsystemctl) please.

**Comment by wang1zhen** [comment]
Thanks, I will close this issue.
