### ISSUE TITLE
Curl and pacman broken after latest upgrade

### ISSUE THREAD

**Issue by tigerjack** [yuk7/ArchWSL#173]
**Describe the issue**
Yesterday I launched a full system upgrade, which installed the latest curl (7.74). From then, every time I try to use pacman, I get
`pacman: error while loading shared libraries: /usr/lib/libcurl.so.4: file too short`

Indeed, this is the state of the library files

```bash
>ls -Al /usr/lib/libcurl.so*
lrwxrwxrwx 1 root root 16 Dec  9 10:19 /usr/lib/libcurl.so -> libcurl.so.4.7.0
lrwxrwxrwx 1 root root 16 Dec  9 10:19 /usr/lib/libcurl.so.4 -> libcurl.so.4.7.0
-rwxr-xr-x 1 root root  0 Dec  9 10:19 /usr/lib/libcurl.so.4.7.0
```
Note the 0 size. This is true also for other packages installed yesterday
```bash
>ll /usr/lib/liblz4.so*
lrwxrwxrwx 1 root root 15 Dec  8 17:35 /usr/lib/liblz4.so -> liblz4.so.1.9.3
lrwxrwxrwx 1 root root 15 Dec  8 17:35 /usr/lib/liblz4.so.1 -> liblz4.so.1.9.3
-rwxr-xr-x 1 root root  0 Dec  8 17:35 /usr/lib/liblz4.so.1.9.3
```

The [log file](https://pastebin.com/tmfJ7R9K) from pacman does not show anything relevant

Indeed, by checking the files in `/var/cache/pacman/pkg/`, I have this
```bash
-rw-r--r-- 1 root root     0 Dec 10 21:04 archlinux-keyring-20201210-1-any.pkg.tar.zst
-rw-r--r-- 1 root root     0 Dec  9 10:24 curl-7.74.0-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root     0 Dec 10 23:03 imagemagick-7.0.10.48-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root     0 Dec  8 17:35 lz4-1:1.9.3-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root     0 Dec 10 20:37 plocate-1.1.2-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root     0 Dec 10 20:18 python-cryptography-3.3.1-1-x86_64.pkg.tar.zst
```

I managed to somehow make the system work again using the steps described in [arch forum](https://bbs.archlinux.org/viewtopic.php?pid=1943395), but I was wondering if this is a generic Arch bug or it's only related to the WSL installation.

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.20262.1010]
 - WSL version 1/2: WSL2
 - ArchWSL version: /don't know how to check/
 - ArchWSL Installer type zip/appx/other clean/update: zip
 - Launcher version: wsldl, version 20112500

**Comment by escape0707** [comment]
If you mean `curl-7.74.0-1`, I've just did a full system upgrade, too, but pacman is still functioning.
WSL2 w/ Windows 10.0.19042.685
Btw, @yuk7 do we have some formal way to check current ArchWSL version? I couldn't find any info either.

**Comment by tigerjack** [comment]
yep, that's exactly it. So I guess that it's just a general problem with Arch itself. Thanks for your help.

**Comment by yuk7** [comment]
@escape0707 
I don't provide a way to find out the version other than appx...
It seems better to enclose a file that describes version info.
