### ISSUE TITLE
Where is the Arch.exe installed to?

### ISSUE THREAD

**Issue by vcapra1** [yuk7/ArchWSL#174]
Today when i tried to open Arch in WSL2 (as I do almost every day), I get this error:

```
The system cannot find the path specified.

[process exited with code 4294967295]
```

Where is Arch.exe installed, and where is the VHDX for the filesystem located?  I also have Ubuntu and Kali installed, I find their executables in `%LOCALAPPDATA%\Microsoft\WindowsApps`, but Arch is not there.  I also went to `\\wsl$` and saw the others, but not Arch.  Did it just spontaneously delete itself?

**Comment by vcapra1** [comment]
I found it, apparently ArchWSL installed to my Downloads folder (???) and when I cleaned up my downloads today I removed it.  Closing this issue

**Comment by escape0707** [comment]
I have a stupid but quick method to find the VHDX path for zip installation. Just refer to `arch --help`, and you can find an option to backup only the registry entries. You can then find the path to VHDX file.
