### ISSUE TITLE
Arch.exe "The system cannot find the file specified."

### ISSUE THREAD

**Issue by IIWare** [yuk7/ArchWSL#176]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Docs](https://git.io/arch-doc) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
When I start Arch.exe, an error "The system cannot find the file specified." occurs.

**To Reproduce**
1. Delete the current arch folder
2. re-download the arch folder from the releases
3. start Arch.exe and see error.

**Expected behavior**
Arch.exe starts to the terminal.

**Screenshots**

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.19041.630]
 - Security Software: Avast
 - WSL version 1/2: WSL1
 - ArchWSL version 20.11.25.0
 - ArchWSL Installer type zip/appx/other clean/update: Zip, Update (I updated by deleting the arch folder, installing the newer zip and extracted the newer arch zip)
 - 
 - Launcher version [e.g. 19030700] wsldl, version 20112500

**Additional context**

**Comment by yuk7** [comment]
Run this command to delete previous installation:
```
arch.exe clean
```

**Comment by IIWare** [comment]
@yuk7 Thanks for telling me how, it's well appreciated.

**Comment by Brndest** [comment]
> Run this command to delete previous installation:
> 
> ```
> arch.exe clean
> ```

thanks!
