### ISSUE TITLE
Add support for WSL 1

### ISSUE THREAD

**Issue by barfin** [yuk7/ArchWSL#183]
WSL1 can work without enabling hyper-v which can be useful because hyper-v often conflicts with other virtualization apps like long-term supported versions of virtualbox and android game emulators like tencent's gameloop emulator

**Comment by yuk7** [comment]
What your Windows build version?
I have confirmed that Arch works on WSL1 on Windows 10 2004.

P.S.
By using "Windows Hypervisor Platform", you can use Virtualbox and Hyper-V at the same time.

**Comment by barfin** [comment]
> 
> 
> Thank you for your reporting~
> What your Windows build version?
> I have confirmed that Arch works on WSL1 on Windows 10 2004.
> 
> P.S.
> By using "Windows Hypervisor Platform", you can use Virtualbox and Hyper-V at the same time.

![image](https://user-images.githubusercontent.com/37030489/105028015-b6ccbd80-5a65-11eb-8c60-9702d1c3c957.png)

**Comment by yuk7** [comment]
Ok.
I think that error code is WSL2's.
Could you check default wsl v?
`wsl --set-default-version 1`

**Comment by barfin** [comment]
>  `wsl --set-default-version 1`

that worked ty

**Comment by chenyidao110** [comment]
> 
> 
> Ok.
> I think that error code is WSL2's virtualization.
> Could you check default wsl v?
> `wsl --set-default-version 1`

Excuse,  your arch dic currently support WSL1?
