### ISSUE TITLE
pacman更新失败

### ISSUE THREAD

**Issue by chenyidao110** [yuk7/ArchWSL#185]
1、环境：
windows 10 2004 WSL2
最新的Arch.zip，解压以管理员身份安装
2、问题：
安装之后运行pacman -Syy
failed retrieving file 'core.db' from mirrors.kernel.org，后发现/etc/resolve.conf文件中被写入自动生成的nameserver,是无法ping通的，修改/etc/wsl.conf禁止自动生成并更新nameserver为 192.168.1.1，还是会报上述错误，换成国内源也是报类似的问题

**Comment by escape0707** [comment]
Please use English to report issue.

**Comment by escape0707** [comment]
As for your issue, I think it might relates to #161.

**Comment by escape0707** [comment]
What's in your `/etc/resolve.conf` and what does running `ip route` give you?

For me, my `/etc/resolve.conf` contains:

```
nameserver 172.29.240.1
```

... which is the same as which `ip route` gives:

```
$ ip route
default via 172.29.240.1 dev eth0
...
```

And I can ping my LAN gateway `192.168.1.1` and the WSL2 VM's gateway `172.29.240.1`[in a **admin shell** successfully ([non-privileged shell will get `ping: socket: Operation not permitted`](https://github.com/microsoft/WSL/issues/18#issuecomment-222017700)).

**Comment by chenyidao110** [comment]
> ip route

[root@DESKTOP-NJOHTE8 xiaobai]# ip route
default via 172.18.144.1 dev eth0
172.18.144.0/20 dev eth0 proto kernel scope link src 172.18.152.139

**Comment by escape0707** [comment]
Interesting, see https://github.com/microsoft/WSL/issues/4171. E.g try `ping microsoft.com`.

**Comment by chenyidao110** [comment]
> 
> 
> Interesting, see [microsoft/WSL#4171](https://github.com/microsoft/WSL/issues/4171). E.g. try `ping microsoft.com`.

Thank you .
I will try later, and reply result

**Comment by escape0707** [comment]
Is the problem fixed? Please post how's it going for future reference. If it's not, it's okay to keep it open so that we could have an eye on it.

**Comment by chenyidao110** [comment]
> 
> 
> Is the problem fixed? Please post how's it going for future reference. If it's not, it's okay to keep it open so that we could have an eye on it.
Not fixed, delete it ,use https://github.com/sileshn/ManjaroWSL
