### ISSUE TITLE
no more spams

### ISSUE THREAD

**Issue by 33Syvan** [yuk7/ArchWSL#188]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Docs](https://git.io/arch-doc) before creating the issue.

**Please fill out the below information:**
**Describe the issue**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Enviroment:**
 - Windows build number: [e.g. 10.0.17134.228] (Type `ver` at a Command Prompt)
 - Security Software: [e.g. ESET Internet Security]
 - WSL version 1/2: [e.g. WSL1]
 - ArchWSL version [e.g. 19.3.7.0]
 - ArchWSL Installer type zip/appx/other clean/update [e.g. appx update]
 - Launcher version [e.g. 19030700] (Type `Arch.exe version` at a Command Prompt)

**Additional context**

**Comment by 33Syvan** [comment]
Windows build number: [e.g. 10.0.17134.228] (Type ver at a Command Prompt)
Security Software: [e.g. ESET Internet Security]
WSL version 1/2: [e.g. WSL1]
ArchWSL version [e.g. 19.3.7.0]
ArchWSL Installer type zip/appx/other clean/update [e.g. appx update]
Launcher version [e.g. 19030700] (Type Arch.exe version at a Command Prompt

**Comment by yuk7** [comment]
This is spam, right?
