### ISSUE TITLE
Windows build number: [e.g. 10.0.17134.228] (Type ver at a Command Prompt)

### ISSUE THREAD

**Issue by 33Syvan** [yuk7/ArchWSL#189]
Windows build number: [e.g. 10.0.17134.228] (Type ver at a Command Prompt)
Security Software: [e.g. ESET Internet Security]
WSL version 1/2: [e.g. WSL1]
ArchWSL version [e.g. 19.3.7.0]
ArchWSL Installer type zip/appx/other clean/update [e.g. appx update]
Launcher version [e.g. 19030700] (Type Arch.exe version at a Command Prompt

_Originally posted by @33Syvan in https://github.com/yuk7/ArchWSL/issues/188#issuecomment-777774250_

**Comment by 33Syvan** [comment]
https://github.com/yuk7/ArchWSL/issues/188#issue-https://github.com/yuk7/ArchWSL/issues/188#issue-806721654 @
#
- [ ] delete #188 

> [](url)

**Comment by yuk7** [comment]
We need informations!
