### ISSUE TITLE
How can I install two Arch WSL Linux on one Windows system

### ISSUE THREAD

**Issue by langonginc** [yuk7/ArchWSL#191]
I want to install two Arch WSL subsystems on a Windows system.

1. First I creat the 1st arch WSL
2. Second I downloaded a new ZIP file and run .\Arch.exe to creat the 2nd arch WSL.

But in the step 2, it loaded into WSL 1st, when I type .\Arch.exe

How can I creat them?

**Comment by Ca1seMonika** [comment]
Change the name of Arch.exe, the name of exe file is the name of subsystem.

**Comment by langonginc** [comment]
> Change the name of Arch.exe, the name of exe file is the name of subsystem.

Thanks for your help!
