### ISSUE TITLE
[ISSUE] i Can't install: error 0x80370102

### ISSUE THREAD

**Issue by linuxmobile** [yuk7/ArchWSL#198]
Using: C:\Program Files\WindowsApps\yuk7.archwsl_20.11.25.0_x64__35zwpb4sx6e50\rootfs.tar.gz
Installing...
ERROR:Installation Failed!
HRESULT:0x80370102
Press any key to continue...

**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Docs](https://git.io/arch-doc) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
The arch shortcut created when i installed the .appx, don't install... 

**To Reproduce**
Running arch from anywhere (shortcut, exe)

**Expected behavior**
Launch and get working easy.

**Screenshots**
![Sin título](https://user-images.githubusercontent.com/10554636/112529929-9af6d800-8d84-11eb-91f8-d364544a11ea.png)

**Enviroment:**
 - Microsoft Windows [Versión 10.0.19043.844]
 - Security Software: Win Defender
 - WSL version 2
 - ArchWSL version 20.11.25
 - ArchWSL Installer .appx and .exe (same results)

**Comment by correabuscar** [comment]
I guess this got completed via https://github.com/yuk7/ArchWSL/issues/93#issuecomment-727081132
