### ISSUE TITLE
Customizable TargetName and user

### ISSUE THREAD

**Issue by Nik-mmzd** [yuk7/ArchWSL#2]
Is it possible to create arguments to change Target name, defalut user and to create launch installed instance shortcut in Start menu?

**Comment by yuk7** [comment]
Thank you for your testing and comment!
Installed Instance Launcher is added on new arch.exe build.
replace old exe and create shortcut please(non arguments support yet. just launch only)
https://github.com/yuk7/ArchWSL/releases/download/17101900/arch.exe

**Comment by yuk7** [comment]
Change target name is important for multi Instance support.
and changable default user too...
I want to work it... Thank you for your suggestion.

If you want it,you can change installed distribution name and default user from Registory
HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss
sub keys

Thanks!

**Comment by yuk7** [comment]
Thank you for your testing and comment!
I built new version [Arch.exe](https://github.com/yuk7/ArchWSL/releases/download/17101901/Arch.exe)
It can customize the Instance name and can launch Instance directly(no args support. just launch only...).
To launch from the start menu,please download new [Arch.exe](https://github.com/yuk7/ArchWSL/releases/download/17101901/Arch.exe) file and create a shortcut to start menu.
and you can rename Arch.exe to install with custom name.

**Comment by yuk7** [comment]
The change function of default user has not been implemented yet.
it is very important.  I'm going to work for it quickly.

If you want to change default user you can also change it from the registry.
please set linux uid to
HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss\{(LxUID)}\DefaultUID  (DEX)

**Comment by Nik-mmzd** [comment]
I asked not for me, but for others =)
I already changed what I want in registry and created a shortcut (wsl.exe {LxUID} ~)

**Comment by yuk7** [comment]
Ok. no problem:)

and I added default uid changer in the update.
I think that the problem was solved.
so I'll close this issue.
