### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by hxse** [yuk7/ArchWSL#200]
**Describe the issue**
```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted
[hxse@DESKTOP-52TNC8V hxse]$ krita
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted
```
**To Reproduce**
1. pacman -S krita
2. krita

**Expected behavior**
nnormal run krita.

**Enviroment:**
 - Windows build number: win10 19042.867
 - Security Software: 
 - WSL version 1/2: WSL 2
 - ArchWSL version :
 - ArchWSL Installer type :click exe
 - Launcher version  :20112500

**Comment by justforlxz** [comment]
You need to install xserver on windows, refer to https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242

**Comment by justforlxz** [comment]
the new info: https://www.zdnet.com/article/new-windows-10-test-build-adds-first-preview-of-linux-gui-apps-on-wsl/

**Comment by justforlxz** [comment]
I test the krita.

![image](https://user-images.githubusercontent.com/12298476/115659059-9108ca80-a36c-11eb-8fa3-2119313e88af.png)

**Comment by escape0707** [comment]
OMG, X server on Windows officially, another spicy🌶 move by Microsoft.
