### ISSUE TITLE
[Question] Can I remove rootfs.tar.gz after a successful Arch install and setup?

### ISSUE THREAD

**Issue by ianpan870102** [yuk7/ArchWSL#205]
This is **not** a bug report. I'm just curious whether I can safely remove the rootfs.tar.gz file after I successfully installed and set up Arch.
I installed using the "zip file" method, and obviously Arch.exe and ext4.vhdx are super important -- but what exactly does rootfs.tar.gz do (with a size > 3GB)? Excuse my ignorance, I'm rather new to manually installing distros with WSL2. 
Thanks for the help.

**Comment by escape0707** [comment]
It's an archive / snapshot of a working Arch Linux's file system. You can create your own, too. 

If you can be sure that you won't need to install from the ground up again, you can remove it, create backup for your current Arch WSL, and only use that afterwards.
