### ISSUE TITLE
What is the difference with using lxrunoffline install -n ArchLinux -f X:/where/is/archlinux-bootstrap-{yyyy.mm.dd}-x86_64.tar.gz -d D:/WSL/ArchLinux -r root.x86_64

### ISSUE THREAD

**Issue by dyingsu** [yuk7/ArchWSL#206]
Sorry to interrupt.

But what is the difference between this release and using lxrunoffline install -n ArchLinux -f X:/where/is/archlinux-bootstrap-{yyyy.mm.dd}-x86_64.tar.gz -d D:/WSL/ArchLinux -r root.x86_64?

**Comment by KyleJKC** [comment]
I also want to know

**Comment by yuk7** [comment]
When I created ArchWSL, WSL-DistroLauncher didn't exist and LxRunOffline didn't support the new API.
I don't think both are much different now.
but we have a launcher exe, appx packages and older wsl dns resolver config.
