### ISSUE TITLE
ping: socket: Operation not permitted

### ISSUE THREAD

**Issue by iantriggs** [yuk7/ArchWSL#210]
**Describe the issue**
Ping now requires root to run.  Running ping under a normal user account results in 'ping: socket: Operation not permitted'. Tested on a regular Arch bare metal install, ping still runs as per normal.

**To Reproduce**
ping to any IP address eg. ping 1.1.1.1:

```
[ian@PCX ~]$ ping 1.1.1.1
ping: socket: Operation not permitted

[ian@PCX ~]$ sudo ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=51 time=16.5 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=51 time=16.8 ms
^C
--- 1.1.1.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 16.494/16.638/16.782/0.144 ms
[ian@PCX ~]$
```

**Expected behavior**
Pings should be sent.

**Screenshots**

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.18363.1500]
 - Security Software: None
 - WSL version 1/2: WSL2
 - ArchWSL version [e.g. 19.3.7.0]: unsure how to check
 - ArchWSL Installer type zip/appx/other clean/update: zip
 - Launcher version: wsldl, version 20040300

**Additional context**
[ian@PCX ~]$ pacman -Q iputils
iputils 20210202-1

**Comment by LeonGr** [comment]
You can use `sudo chmod 4711 /usr/bin/ping` to fix this. 
source: https://www.incredigeek.com/home/how-to-fix-ping-socket-operation-not-permitted/

**Comment by Hazmi35** [comment]
You can reinstall the package it belongs to
```bash
$ pacman -Qo ping
/usr/bin/ping is owned by iputils 20210202-1
```
then
```bash
pacman -S iputils
```

**Comment by 7k5x** [comment]
> Even better, You can reinstall the package it belongs to and let pacman do it's permissions thingy
> 
> ```shell
> $ pacman -Qo ping
> /usr/bin/ping is owned by iputils 20210202-1
> ```
> 
> then
> 
> ```shell
> pacman -S iputils
> ```

That didn't fix it for me.. Doesn't really matter much since I ust need to use `sudo`, but still pretty annoying sometimes.

**Comment by Hazmi35** [comment]
> > Even better, You can reinstall the package it belongs to and let pacman do it's permissions thingy
> > ```shell
> > $ pacman -Qo ping
> > /usr/bin/ping is owned by iputils 20210202-1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then
> > ```shell
> > pacman -S iputils
> > ```
> 
> That didn't fix it for me.. Doesn't really matter much since I ust need to use `sudo`, but still pretty annoying sometimes.

Have you used the original solution above my comment?

**Comment by 7k5x** [comment]
@Hazmi35 Yes I did, hmm maybe it's because I put the user inside another wheel

**Comment by sharpjs** [comment]
I find that ping works for a few days after installing ArchWSL, then reverts to the behaviour described in this issue.  This is on Windows 11.  I think it's being broken by WSL "system distribution" updates or Docker Desktop's internal distribution updates.

**Comment by sharpjs** [comment]
What does resolve it for me, at least temporarily, is:

```
sudo setcap cap_net_raw+p $(which ping)
```
