### ISSUE TITLE
Unable to launch KDE Plasma/无法启动KDE Plasma

### ISSUE THREAD

**Issue by xuangeyouneihan** [yuk7/ArchWSL#213]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Docs](https://git.io/arch-doc) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
There is nothing in the X Server window except a KDE cursor/X服务器的窗口里除了一个KDE的光标之外什么都没有

**To Reproduce**
1.Start X Server and terminal/启动X服务器和终端
2.Type `startplasma-x11` in the terminal/在终端里输入`startplasma-x11`

**Expected behavior**
KDE Plasma is started and run successfully without any error/成功启动并运行KDE Plasma，不出现任何错误

**Screenshots**
https://user-images.githubusercontent.com/50788434/119856869-a3ff5380-bf45-11eb-91f4-d225604daba4.mp4

**Enviroment:**
 - Windows build number: 10.0.19043.985(Type `ver` at a Command Prompt)
 - Security Software: Windows Defender
 - WSL version 1/2: WSL2
 - ArchWSL version 20.11.25.0
 - ArchWSL Installer type zip/appx/other clean/update [e.g. appx update]
 - Launcher version 2011250 (Type `Arch.exe version` at a Command Prompt)

**Additional context**

**Comment by KaranKad** [comment]
For arch you need to type `dbus-launch startplasma-x11`.

**Comment by Lapis-Apple** [comment]
Does it happen in MS Official WSL(s)? / 在 MS 官方那些 WSL 里有这个问题吗？

**Comment by xuangeyouneihan** [comment]
> Does it happen in MS Official WSL(s)? / 在 MS 官方那些 WSL 里有这个问题吗？

No, I found that I have input the wrong command. The right command for Arch is `dbus-run startplasma-x11` / 没这事，我发现是我搞错了，对于 Arch 应该输入 `dbus-run startplasma-x11`

**Comment by xuangeyouneihan** [comment]
> Does it happen in MS Official WSL(s)? / 在 MS 官方那些 WSL 里有这个问题吗？

参见你楼上的大神
