### ISSUE TITLE
warning: Public keyring not found; have you run 'pacman-key --init'? error: keyring is not writable

### ISSUE THREAD

**Issue by mick-p1982** [yuk7/ArchWSL#215]
I don't know if this can be fixed in the image but just to index it online, out of the gate this (https://mycomputernest.wordpress.com/2020/10/20/when-pacman-says-error-required-key-missing-from-keyring/) problem comes up (not my blog). Note, I don't expect this to be Closed unless it's fixed in the image or a bold warning is added to the Readme.MD here. I'm writing this so others can find a solution.

```
:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                           [########################################] 100%
warning: Public keyring not found; have you run 'pacman-key --init'?
downloading required keys...
error: keyring is not writable
error: required key missing from keyring
error: failed to commit transaction (could not find or read file)
Errors occurred, no packages were upgraded.
```

**Comment by PhyX-Meow** [comment]
Did you tried just RUN 'pacman-key --init'

**Comment by mick-p1982** [comment]
I'm new to Arch, so unfamiliar with packman, but `pacman-key --init` is part of the provided link's solution. (Personally I probably tried it naturally, because it says `warning: Public keyring not found; have you run 'pacman-key --init'`. It's one of those things where if it were so simple then that would be automatic.)

**Comment by yuk7** [comment]
Wrote to document, close.
