### ISSUE TITLE
"FATAL: kernel too old" 

### ISSUE THREAD

**Issue by yeahai** [yuk7/ArchWSL#219]
wsl 2 or 1 to－d arch ，I cant success.
alert FATAL: kernel too old" 
so,how solve it.

**Comment by seasonyuu** [comment]
Same here

**Comment by yeahai** [comment]
I only play subsystem linux ,but this is so defficulty.

**Comment by tilda** [comment]
see #190

**Comment by yuk7** [comment]
ArchWSL is now only support WSL2
