### ISSUE TITLE
Installation failed, but distro seems to be working

### ISSUE THREAD

**Issue by git-commit** [yuk7/ArchWSL#22]
I tried installing the latest release and got this error message when installing
```
PS C:\Users\u\Downloads\Arch> .\arch.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x0
Press any key to continue...
```

However running arch.exe results in a working shell and uname -a gives the following output:
```
PS C:\Users\u\Downloads\Arch> .\arch.exe run uname -a
Linux XPS15 4.4.0-17134-Microsoft #81-Microsoft Sun May 20 01:14:00 PST 2018 x86_64 GNU/Linux
```

**Comment by yuk7** [comment]
oh,,sorry...!
probably that issue from new Launcher program...

Please wait as soon as I fix it...

**Comment by yuk7** [comment]
Or I think that it will be fine if you use an older version.

https://github.com/yuk7/ArchWSL/releases/tag/18030400

**Comment by yuk7** [comment]
sorry,
It seems there was a mistake in the program code.
I'll fix.
thanks.

**Comment by yuk7** [comment]
I fixed launcher program and published it.
I think this issue was solved

**Comment by git-commit** [comment]
Getting a different error:
`PS C:\dev\arch> .\arch.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x80070005
Press any key to continue...`

**Comment by yuk7** [comment]
I think this error is not the same.
`0x80007005` is unknown error.

please try these:
1. reboot computer (Windows 1803's WSL Service is unstable)
2. run `wslconfig /u Arch` command for full uninstall instance.
3. run in eleveted-shell.

**Comment by yuk7** [comment]
Yes,that HRESULT is E_ACCESSDENIED.
UNKNOWN is 0x80004005.
I was misunderstanding.

**Comment by yuk7** [comment]
I tested newer installer on 1803,
but it works...
hmm...

**Comment by git-commit** [comment]
Retried today. Everything is working as expected now. Thanks :)
