### ISSUE TITLE
Is there gonna be GUI support

### ISSUE THREAD

**Issue by dogukanoksuz** [yuk7/ArchWSL#220]
Hi, I wonder there is gonna be a implementation of GUI support that introduced with Windows 11.
Thanks.

**Comment by tilda** [comment]
I believe it's already supported in the current Windows insider builds

**Comment by yuk7** [comment]
You can already use wslg.

**Comment by sirianni** [comment]
Can you take a few minutes to describe how to use wslg?  I ran
```
$ export DISPLAY=$(grep nameserver /etc/resolv.conf | awk '{print $2}'):0.0
$ glxgears
```

I don't see any errors, but no graphical windows are launched.  I am running wsl2
```
PS C:\Users\erics> wsl -l -v
  NAME    STATE           VERSION
* Arch    Running         2
```

**Comment by tilda** [comment]
you don't need to export `$DISPLAY`, it should just work

**Comment by sirianni** [comment]
It works now with `DISPLAY=:0`.  

I'm not sure what changed other than I installed the standard WSL Ubuntu distro to check if it worked there.  🤷‍♂️
