### ISSUE TITLE
arch: unknown option -- default-user

### ISSUE THREAD

**Issue by YuanfengZhang** [yuk7/ArchWSL#221]
```
  Arch.exe config --default-user justinzhang
arch: unknown option -- default-user
Try '/usr/bin/arch --help' for more information.
```

**Expected behavior**
That should be no warning or error message and do it successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/71358306/123554157-56c70980-d7b1-11eb-9d21-fa0529c2e329.png)

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.19043.1081]
 - Security Software: Huorong
 - WSL version 1/2: WSL2
 - ArchWSL version: 20.11.25.0_x64
 - ArchWSL Installer: appx
 - Launcher version: arch (GNU coreutils) 8.32

**Additional context**
![image](https://user-images.githubusercontent.com/71358306/123554284-d5bc4200-d7b1-11eb-8662-ad872d863c94.png)

I changed the default location for new apps. Nothing else special.

**Comment by YuanfengZhang** [comment]
To testify this, i have tried some cmdline in docs.
(1) Arch.exe run uname -r
![image](https://user-images.githubusercontent.com/71358306/123554537-0e105000-d7b3-11eb-9b46-281aeba5009d.png)
(2) Arch.exe runp echo C:\Windows\System32\cmd.exe
![image](https://user-images.githubusercontent.com/71358306/123554567-2c764b80-d7b3-11eb-8f8f-0b54de81b789.png)
(3) Arch.exe get --default-uid
![image](https://user-images.githubusercontent.com/71358306/123554597-4a43b080-d7b3-11eb-9eef-3e86199d6ecc.png)

**Comment by YuanfengZhang** [comment]
To make sure that is not caused by git bash or mingw64 as mentioned in #106,
>dir Arch.exe
![image](https://user-images.githubusercontent.com/71358306/123554878-d3a7b280-d7b4-11eb-9e4e-e39107239d63.png)
The result shows this Arch.exe is what i want.

**Comment by YuanfengZhang** [comment]
GOD DM IT... It's still #106 problem.

cd to the abs dir and type arch.exe won't help, bcz Win10 still search it from PATH and that's under git bash.
**The right way is**
`.\Arch.exe config --default-user {username}`

_How funny i missed the basic stuff!_
As this imperceptible problem is likely to make people having git bash on their computers confused, I suggest add it to the README.md.

**Comment by tapebysea** [comment]
You're my hero
