### ISSUE TITLE
Error: Could not read registry key

### ISSUE THREAD

**Issue by violetrose16** [yuk7/ArchWSL#224]
I downloaded Arch.zip then export to C:\wsl\Arch then installed Arch.exe also installed ArchWSL-AppX_20.11.25.0_x64.appx and certificate. Log in my username (Arch.exe). It's message: "ERROR:[2] Could not read registry key"  How I can fix it?

**Enviroment:**
 - Windows build number: Version 10.0.22000.51 but Windows 11 Dev Insider preview
 - WSL version 1/2: WSL 2

**Comment by yuk7** [comment]
Thank you for your reporting.
This issue merges with https://github.com/yuk7/wsldl/issues/98.
