### ISSUE TITLE
FATAL : Kernel too old

### ISSUE THREAD

**Issue by Shiven-saini** [yuk7/ArchWSL#228]
When I finished installing the arch WSL through .appx package I launched it in terminal. And I got this error Fatal : Kernel Too old
Any solution?
![image](https://user-images.githubusercontent.com/65594832/126031812-c8b4146a-042d-4d89-ac4f-8fe2662b6248.png)

**Comment by yuk7** [comment]
Could you use WSL2?
ArchWSL only supports WSL2.
