### ISSUE TITLE
how to update to new version?

### ISSUE THREAD

**Issue by mealayaria** [yuk7/ArchWSL#23]
I'm in ver 18030400, how can I update to new version without delete the old one because I don't want to install packages and configure them again.

**Comment by yuk7** [comment]
Just update launcher?
please download icon.zip from my WSL-DistroLauncher release and extract Arch.exe and replace installed one.
https://github.com/yuk7/WSL-DistroLauncher/releases/latest

**Comment by yuk7** [comment]
ArchLinux adopts rolling release.
Normally,rootfs update is not necessary.

**Comment by mealayaria** [comment]
got it. thanks!

**Comment by roachsinai** [comment]
@yuk7 So you mean after installed `ArchWSL`, I can even remove `rootfs.tar.gz`, and it is no need anymore. What need to do is just copy the new `Arch.exe` and override old one, when you release a new version?

**Comment by yuk7** [comment]
@roachsinai
Yes,that's true.
rootfs.tar.gz is only used during installation.
However, if you update Arch.exe, you can receive bug fixes, etc. for the launcher.
I regularly pack and distribute fresh packages.

**Comment by roachsinai** [comment]
Got it. Thanks, and think it will be better to tell how to update it, as make me very confused at the beginning.

**Comment by yuk7** [comment]
@roachsinai I got it. thanks.

**Comment by yuk7** [comment]
added to README in 4dff2f49

**Comment by mhqmarques** [comment]
I'm sorry for put my question in a issue closed, but i don't found up other with same theme so.. How to check version of my ArchWSL ?
