### ISSUE TITLE
build 21.8.22.1 installation error 4294967295

### ISSUE THREAD

**Issue by scheckley** [yuk7/ArchWSL#240]
Error during installation:

Executing Arch.exe returns:

`Using: C:\Arch\rootfs.tar.gz
Installing...
ERR: exit status 4294967295
Press enter to exit...`

The status code seems non-specific. The WSL instance appears to boot regardless of the error. Is there any way to diagnose this, or has anybody else experienced this?

thanks.

**Comment by yuk7** [comment]
What is your Windows version?

**Comment by T41US** [comment]
I am on 20H2, build 19042.631

**Comment by T41US** [comment]
strange, after a full day attempting to reinstall via appx allows for a working install, I can't seem to replicate the issue

**Comment by scheckley** [comment]
20H2, build 19042.1110 here. I ran the WSL instance for a couple of days now and it seems to be fine despite the error code during installation.

**Comment by mlizbeth** [comment]
I am also having this issue with 21H1, build 19043.1165

**Comment by sammko** [comment]
Same error on 22449.1000, although the instance seems to work fine.

**Comment by yuk7** [comment]
Okay...
I think this is a difference due to the environment settings.
and the latest version no longer executes instructions that may be causing it during installation.

I would appreciate it if you could tell me the edition.(home,pro,enterprise,server etc.)

**Comment by sammko** [comment]
I encountered the error on Windows 11 Enterprise (22449.1000)

**Comment by yuk7** [comment]
Enterprise... okay

**Comment by mlizbeth** [comment]
So if it helps, I believe it installed fine on 20H2 (Enterprise), or 2004 (Enterprise) but was having issues with 21H1 Enterprise.

My home computer is on 20H2 pro with no issues, my work computer was on 20H2 but after having to reinstall windows and going with 21H1 the installer came up with that error. WSL does work though

**Comment by mlizbeth** [comment]
Another issue, which may presumably relate to this error, or it could be a 21H1 (possibly Enterprise only) specific issue:

Default starting directory is the location of the WSL.exe, for example the shell starts in `/mnt/users/C/username/ArchWSL` for me.

I have tried adding 
`"startingDirectory": "//wsl$/ArchWSL/home/username"` to **preset.json** without success.

My workaround was to install Windows Terminal, add the `startingDirectory` string to the **settings.json,** file for Windows Terminal, then change the default GUID to my WSL identifier. So now it starts in `/home/username` but only in Windows Terminal, and not the actual ArchWSL.exe (which is what I named my executable)
I can't seem to find any documentation that is not specific to Windows Terminal for changing the start directory.

Hope this helps!

**Comment by sileshn** [comment]
Error is caused by [this](61d64cba9e3be5973363f44dd02f061dd95c1811) commit. I had it on ManjaroWSL as well. Didn't show up after i reverted it.

**Comment by beni69** [comment]
I made a couple of scripts for automatically creating custom rootfs tarballs for the installer by installing with defaults, doing some things in the wsl machine and running `Arch.exe backup` and they run fine on my own pc but when I try doing this on github actions I get this exact error code when it runs the backup command.
