### ISSUE TITLE
Setting Default User

### ISSUE THREAD

**Issue by redxtech** [yuk7/ArchWSL#25]
I created a new user with `useradd` & tried to set it as default with `Arch.exe --default-user redxtech` but that didn't do anything. I can confirm that I typed it out properly. I haven't rebooted my PC yet but I don't think that should have an impact. I'll give that a shot when I'm able to but at the moment is there something that I could do?

**Comment by yuk7** [comment]
Settings will not be reflected until the LxssManager service is restarted.
To get default user uid,please excute`Arch.exe get --default-uid`.

**Comment by elswerky** [comment]
i created  new user and set as defaut ,,rebooted and it is not the default but  no folder created for it in /home ,,,also it is powerless it can't mkdir or do anything ,,what is the problem and why no path created for new user in /home ??? 

also i want to change defaut path to new user home 

any idea what's wrong ??

**Comment by elswerky** [comment]
rebbot

**Comment by basswaver** [comment]
Can confirm that this is still not working.

`sc stop LxssManager` and `sc start LxssManager` both run without an issue (with and without an admin command line) and those changes are not reflected in the Arch WSL

**Comment by im-AMS** [comment]
Doing `Arch config --default-user <username>` does the trick

**Comment by ppskmg** [comment]
> `.\Arch config --default-user <username>`
