### ISSUE TITLE
Add support for mesa-d3d12?

### ISSUE THREAD

**Issue by TrT-TOT** [yuk7/ArchWSL#252]
The mesa-d3d12 is originally supported by Ubuntu on WSL2.
However, if one directly install mesa on ArchWSL, the default renderer is still llvmpipe. Any way to fix it ?

**Comment by TrT-TOT** [comment]
Have you tried to run OpenGL apps such as gxlgears. What I get is a black window but the FPS output is normal.

Besides, I'm using Intel UHD630 GPU, so maybe the condition is different?

**Comment by TrT-TOT** [comment]
> If you upgrade from an arch install from win10, the symlinks to .X11-Unix isn't automatically created. But a fresh install works fine out of the box.

So is there any suggestion if I don't want to re-install the arch? What's important is that even if I create a soft link of .X11-unix to wslg, the problem still exists...

**Comment by dyharlan** [comment]
In my case, I didn't need to. I just did `ln -s /mnt/wslg/.X11-Unix
/.tmp/.X11-Unix`

**Comment by roachsinai** [comment]
> > If you upgrade from an arch install from win10, the symlinks to .X11-Unix isn't automatically created. But a fresh install works fine out of the box.
> 
> So is there any suggestion if I don't want to re-install the arch? What's important is that even if I create a soft link of .X11-unix to wslg, the problem still exists...

Could you find a ext4.vhdx in your current archwsl instance directory? If so another method is you,

1. reinstall a new ArchWSL instance
2. copy your ext4.vhdx of your current archwsl to the new instance direcotry
3. run `Archg.exe install ext4.vhdx`

should be work, and make sure you rename Arch.exe to other name like Archg.exe according the docs

> As a side note, the executable name is what is used as the WSL instance name. If you rename it, you can have multiple installs.

**Comment by TrT-TOT** [comment]
> > > If you upgrade from an arch install from win10, the symlinks to .X11-Unix isn't automatically created. But a fresh install works fine out of the box.
> > 
> > 
> > So is there any suggestion if I don't want to re-install the arch? What's important is that even if I create a soft link of .X11-unix to wslg, the problem still exists...
> 
> Could you find a ext4.vhdx in your current archwsl instance directory? If so another method is you,
> 
> 1. reinstall a new ArchWSL instance
> 2. copy your ext4.vhdx of your current archwsl to the new instance direcotry
> 3. run `Archg.exe install ext4.vhdx`
> 
> should be work, and make sure you rename Arch.exe to other name like Archg.exe according the docs
> 
> > As a side note, the executable name is what is used as the WSL instance name. If you rename it, you can have multiple installs.

I've tried to but it seems not work. Here is how I did:
1. Download Arch.zip
2. unpack it and change the name of Arch.exe to Archg.exe
3. run Archg.exe
4. Replace the newly generated ext4.vhdx with the previous one
5. 'Archg.exe install ext4.vhdx' not work which says already installed
6. I can normally login the system but /tmp/.X11-unix remains not linked to wslg

**Comment by roachsinai** [comment]
@TrT-TOT but that's all what I did.

**Comment by TrT-TOT** [comment]
https://github.com/microsoft/wslg/issues/482

Seems a common problem for intel UHD graphics card or wslg. I'd like to close the issue and wait for the resolution from wslg developers.
