### ISSUE TITLE
Arch.exe config returns "ERROR HRESULT:0x80004005" and Arch.exe is not in $PATH

### ISSUE THREAD

**Issue by dmitrij-drandarov** [yuk7/ArchWSL#26]
When running any Arch.exe config configuration I get an error:

```
PS C:\Users\username\folder\Arch> .\Arch.exe config --append-path off
ERROR
HRESULT:0x80004005
```

Using CMD/PS with or without admin rights does not matter.

Also `arch.exe get --append-path` tells me `on`, but it isn't actually in my PATH.

**Comment by yuk7** [comment]
Thank you for your reporting.
I'll fix program error.

but PATH operation is correct.
--append-path adds Windows %PATH% environment to Linux $PATH.
The path of Arch.exe is not added.

**Comment by dmitrij-drandarov** [comment]
Thanks for looking at the error.
So I understand correcly that I need to add `Arch.exe` to Windows $PATH manually to use it like 
`ubuntu.exe` or `debian.exe`, which are in $PATH through "C:\Users\dmitr\AppData\Local\Microsoft\WindowsApps", right? Just making sure that this is the intended way.

**Comment by fbigun** [comment]
```
arch config --default-user xxxx
ERROR
HRESULT:0x80004005
Press any key to continue...
```

After performing the operation, I get the same error.


-------------
Also for reference:
Windows 10 Pro, 1803, OS build 17134.112

**Comment by yuk7** [comment]
@fbigun No.
This isn't same error.

**Comment by yuk7** [comment]
I fixed Launcher.
Please download icons.zip from my WSL-DistroLauncher release, extract Arch.exe and replace installed one with it.
https://github.com/yuk7/WSL-DistroLauncher/releases/latest

**Comment by yuk7** [comment]
@dmitrij-drandarov 
Yes.
You can add Arch.exe to Windows %PATH% manually.

**Comment by dmitrij-drandarov** [comment]
Okay, so running that Arch.exe uninstalled ALL my WSL-Distros: ubuntu, debian and arch.
I had to reinstall the others, but can't install Arch. exe anymore:
```
Error: 0x80070040
Press any key to continue...
```

**Comment by yuk7** [comment]
Please excute `wslconfig /u Arch` to full uninstall instance and re-install.

**Comment by dmitrij-drandarov** [comment]
Edited my first response. I basically did this and now it works with WSLDistroLauncher Arch.EXE. :)

**Comment by dmitrij-drandarov** [comment]
Just tried the new release, works great. Thanks! :)
I still believe that adding arch.exe to $PATH should be the default behaviour.

**Comment by yuk7** [comment]
This isn't adopt the AppX package, it can not add PATH automatically.
Thanks.

**Comment by fbigun** [comment]
@yuk7 
```
arch config --default-user xxx
ERROR
HRESULT:0x80004005
Press any key to continue...
```
The latest version was downloaded, but the same error has occurred.（18062100）

**Comment by fbigun** [comment]
I made a mistake, originally need to enter the system to create a new account, and then exit archLinux. ```arch config --default-user xxx```

**Comment by rescenic** [comment]
Same for me. config --default-user broken.
