### ISSUE TITLE
I got a ext4.vhdx where I install Arch, any idea about what it is?

### ISSUE THREAD

**Issue by JerryZhongJ** [yuk7/ArchWSL#260]
I find that the folder I placed Arch.exe has a new file named "ext4.vhdx", I wonder if it's the file system storing Arch.

**Comment by JerryZhongJ** [comment]
If it is, it may be a trouble, because that folder isn't the right place.

**Comment by yuk7** [comment]
Yeah, It is the file system storing Arch.
That is the default specification.

**Comment by JerryZhongJ** [comment]
> Yeah, It is the file system storing Arch. That is the default specification.

Can I move it? I just randomly picked a folder when I installed.... How can wsl find the file system after I move it away?

**Comment by JerryZhongJ** [comment]
I have found the solution, thanks.
