### ISSUE TITLE
Cannot install yay from git 

### ISSUE THREAD

**Issue by zamostny** [yuk7/ArchWSL#261]
I did not see yay installed. Tried installing yay from the yay github instructions but when I try to makepkg -si: 
Note, I have changed root pw, added new default user as well per ArchWSL documentation. 

```[me@MDBA100500 yay]$ makepkg
==> Making package: yay 11.0.2-1 (Mon 29 Nov 2021 04:48:56 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
chmod: changing permissions of '/mnt/c/Users/jeromeza/yay/src': Operation not permitted

==> ERROR: An unknown error has occurred. Exiting...
User defined signal 1

**Comment by yuk7** [comment]
You cannot change permissions within a mounted Windows directory.(e.g. /mnt/~)
I think you can try it in a directory inside the WSL virtual disk. (e.g. /home/~)

```
mv /mnt/c/Users/jeromeza/yay/src /~/yay/src
cd /~/yay/src
makepkg -si
```

**Comment by zamostny** [comment]
Perfect. I had to make a few changes to the directions. I couldnt run the first mv command as the dir didnt exist. I made a src dir and them moved things. Seems to work so far! Thank you for your help! This is awesome!

**Comment by ohk2kt3t4** [comment]
Sorry if this is a stupid question, but what possible reasons could there be for this to work under the standard Ubuntu WSL image but not in the Arch one?

Both appear to be mounted the exact same way according to the output of `mount -l`:

Output of `mount -l` in Ubuntu container:
```ini
C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
D:\ on /mnt/d type 9p (rw,noatime,dirsync,aname=drvfs;path=D:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
```

Output of `mount -l` in Arch container:
```ini
C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=0;gid=0;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
D:\ on /mnt/d type 9p (rw,noatime,dirsync,aname=drvfs;path=D:\;uid=0;gid=0;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
```

**Comment by SonaliBendre** [comment]
@yuk7 https://github.com/yuk7/ArchWSL/issues/261#issuecomment-983392292

@ohk2kt3t4 Have you found any solutions?

**Comment by ohk2kt3t4** [comment]
It's actually working for me now, but I cannot remember what (or if) I did to fix it, and nothing obvious in shell history either :(
If I remember I will update.

**Comment by ohk2kt3t4** [comment]
@SonaliBendre I think I solved it by changing the user/group for the mounts from `uid=0;gid=0` to`uid=1000;gid=1000`, as that is what my `mount -l` shows now and I vaguely remember doing something like that.
