### ISSUE TITLE
cannot open gui apps in archwsl

### ISSUE THREAD

**Issue by ruxiliang** [yuk7/ArchWSL#262]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Docs](https://git.io/arch-doc) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
I cannot use gui apps in ArchWsl, and I have already set the version to 2.

**To Reproduce**
enter the command in terminal

**Expected behavior**
I can use gui apps in gui mode.

**Screenshots**
<img width="339" alt="image" src="https://user-images.githubusercontent.com/91934643/146363409-63befcdb-c1d0-47d2-bb7a-bff3157ff40f.png">

**Enviroment:**
 - Windows build number: 10.0.22518.1000
 - Security Software: 火绒
 - WSL version 1/2: WSL 2
 - ArchWSL version [e.g. 19.3.7.0]
 - ArchWSL Installer type zip
 - Launcher version wsldl2, version 21082800  (amd64)

**Additional context**

**Comment by yuk7** [comment]
Are you using WSLg for GUI?

Can you try to install installer msi from here: https://github.com/microsoft/wslg/releases/latest
and change DISPLAY variable to `:0`?
```
export DISPLAY=:0
```

**Comment by ruxiliang** [comment]
Thanks, I tried those methods and they all helped me in the end!
________________________________

**Comment by SonaliBendre** [comment]
is there scoop package of wslg?
