### ISSUE TITLE
[Noob help] The file exists

### ISSUE THREAD

**Issue by MrComexs** [yuk7/ArchWSL#263]
So I delete the the folder that hold all the files in it and I re-downloaded the zip to start over but every time I try to launch arch.exe it close after 1 second. Then I rename the arch file to arch2.exe but then it says The file exists what is doesn't so how to I fix this mess.

Steps
upzip arch.zip
run arch.exe
delete arch folder
download and unzip arch
crashs after running arch.exe

![image](https://user-images.githubusercontent.com/57308435/147370633-94bb8552-1962-48fe-a55a-f447422f5748.png)

[Version 10.0.22000.376]
Kaspersky
Windows subsytme for linux preview
 ArchWSL 21.8.28.0

**Comment by yuk7** [comment]
Thank you for reporting.

Did you unzip the zip in right way?
Do *not* unpack the contents of `rootfs.tar.gz`.

**Comment by MrComexs** [comment]
I didn't unpack the contents of rootfs.tar.gz and I unzip Arch.zip with 7zip and windows both did the same error.

**Comment by yuk7** [comment]
hmm...

Could you try it in a directory inside your C drive  and uninstall the instance and retry it?
cmd:
```
wslconfig /u Arch
```

**Comment by MrComexs** [comment]
Thanks yuk7, I just need to uninstall the instance.
