### ISSUE TITLE
ArchWSL hangs

### ISSUE THREAD

**Issue by akuropka** [yuk7/ArchWSL#267]
**System:**
Microsoft Windows [Version 10.0.22000.376]
Linux 5.10.74.3-microsoft-standard-WSL2+
ArchWSL 21.8.28.0 appx

**Issue:**
ArchWSL starts fine and works in the open window(s) but after some time the wsl.localhost\Arch share is not available anymore and I am not able to start new instances of Arch. After closing the working window or shutting down WSL I am not getting into Arch as well. After rebooting everything works fine for the time being.

On the other hand Ubuntu from store continues working and can be started after shutdown of WSL.

**Screenshots:**
![20220107_104953_Arch](https://user-images.githubusercontent.com/22570574/148526585-7fef87bb-13ea-4e99-abba-fc83e8743a20.png)
![20220107_105047_explorer](https://user-images.githubusercontent.com/22570574/148526617-8b9d7809-23f8-4679-8893-f0a43dc4063c.png)

**Comment by ruizlenato** [comment]
Same problem.

**Comment by mencargo** [comment]
Hi guys, I just had a similar issue and my problem was WSL from MS Store.
So if you have it (open MS Store, search for Windows Subsystem for Linux Preview), uninstall it and install it the "normal" way, from an admin power shell:
```
wsl.exe --shutdown
Get-AppxPackage -Name MicrosoftCorporationII.WindowsSubsystemforLinux | Remove-AppxPackage
wsl.exe --update
```

Reboot.

**Comment by akuropka** [comment]
Yes, that helps as it is equivalent to downgrading to an older version.
Only the msixbundle (store version) is updated and in development.

**Comment by mencargo** [comment]
Still decent and working with WSLg
This is not an ArchWSL problem, so this should be closed.

You can add / research about it at:
https://github.com/microsoft/WSL/issues/7883

**Comment by akuropka** [comment]
Thanks for reference, never experienced with a distributor from store, though…
