### ISSUE TITLE
can't upgrade system

### ISSUE THREAD

**Issue by ebrocoli** [yuk7/ArchWSL#268]
so i was trying this wsl distro for the first time
i install some packages
i run my first system upgrade with `sudo pacman -Syu`
and it was fine
and then the second run after i reboot my wsl
i got this

`# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra                                                        1563.2 KiB  1954 KiB/s 00:01 [####################################################] 100% community is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (68) archlinux-keyring-20211028-1  argon2-20190702-4  audit-3.0.6-5  bash-5.1.012-1  brotli-1.0.9-7  ca-certificates-mozilla-3.74-1
              coreutils-9.0-2  cryptsetup-2.4.2-3  curl-7.81.0-1  device-mapper-2.03.14-2  e2fsprogs-1.46.5-1  expat-2.4.2-1  file-5.41-1
              filesystem-2021.12.07-1  gawk-5.1.1-1  gcc-libs-11.1.0-3  glib2-2.70.2-1  gnupg-2.2.32-2  gpgme-1.16.0-3  gpm-1.20.7.r38.ge82d1a6-4
              grep-3.7-1  gzip-1.11-1  iana-etc-20211203-1  icu-70.1-1  iproute2-5.15.0-2  iputils-20211215-1  json-c-0.15-2  krb5-1.19.2-2
              libarchive-3.5.2-2  libcap-2.62-1  libcap-ng-0.8.2-6  libelf-0.186-2  libffi-3.4.2-4  libgcrypt-1.9.4-1  libgpg-error-1.43-1
              libldap-2.6.0-2  libnftnl-1.2.1-1  libnghttp2-1.46.0-1  libp11-kit-0.24.0-2  libseccomp-2.5.3-3  libssh2-1.10.0-1  libtasn1-4.18.0-1
              libxcrypt-4.4.27-1  libxml2-2.9.12-6  nano-6.0-1  ncurses-6.3-1  openssl-1.1.1.m-1  p11-kit-0.24.0-2  pacman-6.0.1-3
              pacman-mirrorlist-20211212-1  pam-1.5.2-1  pambase-20211210-1  pcre2-10.39-1  pinentry-1.2.0-1  popt-1.18-2  sqlite-3.37.2-1
              sudo-1.9.8.p2-3  systemd-250.1-1  systemd-libs-250.1-1  systemd-sysvcompat-250.1-1  tzdata-2021e-1  util-linux-2.37.2-5
              util-linux-libs-2.37.2-5  vim-8.2.3890-1  vim-runtime-8.2.3890-1  xz-5.2.5-2  zlib-1:1.2.11-5  zstd-1.5.1-2

Total Download Size:     0.68 MiB
Total Installed Size:  397.86 MiB
Net Upgrade Size:        3.16 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 pam-1.5.2-1-x86_64                                            572.6 KiB  1272 KiB/s 00:00 [####################################################] 100% pinentry-1.2.0-1-x86_64                                       126.1 KiB  1051 KiB/s 00:00 [####################################################] 100% Total (2/2)                                                   698.8 KiB  1075 KiB/s 00:01 [####################################################] 100%
(68/68) checking keys in keyring                                                           [####################################################] 100%
(68/68) checking package integrity                                                         [####################################################] 100%
error: pam: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /var/cache/pacman/pkg/pam-1.5.2-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: pinentry: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /var/cache/pacman/pkg/pinentry-1.2.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.`

help me guys

**Comment by yuk7** [comment]
Thank you for your reporting.
Could you try this command and retry it?
```
sudo pacman-key --init
sudo pacman-key --populate
sudo pacman -Syy archlinux-keyring
```

https://wsldl-pg.github.io/ArchW-docs/How-to-Setup/#initialize-keyring

**Comment by t-taylor** [comment]
I came across this issue just now installing for the first time. I solved it after setting up `/etc/pacman.d/mirrorlist` to local mirrors and runing the commands that yuk7 has written above. Note [this post](https://bbs.archlinux.org/viewtopic.php?id=255890) of the archlinux forums

**Comment by Sir-Photch** [comment]
try running 
`pacman-key --refresh-keys`

solved the issue for me

**Comment by el1-x** [comment]
I had the same issue. 
Can confirm that adding the archlinux-keyring package solved the issue.

**Comment by akuropka** [comment]
> Thank you for your reporting. Could you try this command and retry it?
> 
> ```
> sudo pacman-key --init
> sudo pacman-key --populate
> sudo pacman -Syy archlinux-keyring
> ```
> 
> https://wsldl-pg.github.io/ArchW-docs/How-to-Setup/#initialize-keyring

This is not a WSL-related issue, however maybe it helps adding `sudo pacman -Syy archlinux-keyring` to your docs since only the first two commands are mentioned.

**Comment by Geffers** [comment]
> Thank you for your reporting. Could you try this command and retry it?
> 
> ```
> sudo pacman-key --init
> sudo pacman-key --populate
> sudo pacman -Syy archlinux-keyring
> ```
> 
> https://wsldl-pg.github.io/ArchW-docs/How-to-Setup/#initialize-keyring

That worked for me, thanks.

Geoff
