### ISSUE TITLE
ArchWSL is not working on a freshly installed Windows 10 1803 installation with error 0x80070005

### ISSUE THREAD

**Issue by mcilloni** [yuk7/ArchWSL#27]
```shell
PS C:\Users\marco_o4lnkyr> D:\Arch.exe
Installing...
Installation Complete!
Press any key to continue...
PS C:\Users\marco_o4lnkyr> D:\Arch.exe
Error: 0x80070005
Press any key to continue...
PS C:\Users\marco_o4lnkyr> debian.exe
marco@DESKTOP-UV23V55:~$
```

I have trouble launching ArchWSL under Windows 10 build 1803. Debian installed from the store works fine, as you can see from the snippet I posted, while Arch.exe installs without errors and then fails to launch the shell with error 0x80070005. I have tried to uninstall it, disable and reenable WSL, reboot, without any change.

**Comment by yuk7** [comment]
WSL instance can install to C: drive only.
Please move Arch.exe and rootfs.tar.gz to C:

**Comment by mcilloni** [comment]
Thank you, it works now.
