### ISSUE TITLE
Do I need to update appx?

### ISSUE THREAD

**Issue by jfdtse** [yuk7/ArchWSL#270]
**Describe the issue**
I have Arch running and updated, installed with ArchWSL-AppX_21.8.28.0_x64.appx
Now, I see a new release is pushed ArchWSL-AppX_22.2.9.0_x64.appx
Do I need to execute the new appx to update? Will I keep my current rootfs? Or doing pacman -Syu is enough?

**Enviroment:**
 - Windows build number: [10.0.19042.1466]]
 - WSL version 2
 - ArchWSL version 21.8.28.0
 - ArchWSL Installer type appx
 - Launcher version wsldl2, version 21082800  (amd64)

**Comment by yuk7** [comment]
You can download `ArchWSL-AppX_22.2.9.0_x64.appx` or `ArchWSL_Online-AppX_22.2.9.0_x64.appx` and double-click to update.

Includes bug fixes and more for Windows side.
The filesystem data will not be lost by the update.

**Comment by jfdtse** [comment]
Thank you! For now it seems fine.
