### ISSUE TITLE
Can't install from scoop. Scoop package isn't working

### ISSUE THREAD

**Issue by SonaliBendre** [yuk7/ArchWSL#273]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Docs](https://git.io/arch-doc) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
I tried to install archwsl in wsl2 in Windows 11 with scoop but its not installing
**To Reproduce**
1. run `scoop install archwsl`
2. Get error in installation
3. run `scoop uninstall archwsl`
4. get error while uninstalling
**Expected behavior**
Install silently
**Screenshots**
![image](https://user-images.githubusercontent.com/73757361/154796661-951ac4d5-e081-4d98-8520-16a36805d4ff.png)

**Enviroment:**
 - Windows build number: [e.g. 10.0.22000.527] (Type `ver` at a Command Prompt)
 - Security Software: Windows default defender Anitvirus shit
 - WSL version 1/2: 2
 - ArchWSL version 22.2.10.0
 - ArchWSL Installer type zip/appx/other clean/update Clean install. SCOOP
 - Launcher version wsldl2, version 22020900  (amd64)
https://git.io/wsldl  (Type `Arch.exe version` at a Command Prompt)

**Additional context**

```
Installing 'archwsl' (22.2.10.0) [64bit]
Loading Arch.zip from cache
Checking hash of Arch.zip ... ok.
Extracting Arch.zip ... done.
Linking ~\scoop\apps\archwsl\current => ~\scoop\apps\archwsl\22.2.10.0
Creating shim for 'Arch'.
Creating shortcut for Arch Linux (Arch.exe)
Persisting data
Running post-install script...
ERROR Exit code was 1!
WARN  DO NOT KILL THE PROCESS. Installation is still running!
ERROR Exit code was -2147024452!
ERROR ArchWsl installation failed!
'archwsl' (22.2.10.0) was installed successfully!
Notes
-----
Even when you are logging in as 'root', some operations (like service command) require Windows administrator privileges
```

scoop uninstall archwsl

```
Uninstalling 'archwsl' (22.2.10.0).
Running uninstaller script...
ERROR Exit code was 1!
ERROR ArchWsl is not registered!
Removing shim 'Arch.exe'.
Removing shim 'Arch.shim'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Arch Linux.lnk
Unlinking ~\scoop\apps\archwsl\current
'archwsl' was uninstalled.
```

**Comment by yuk7** [comment]
Thank you for reporting.
But I'm sorry, I'm not the maintainer of the Scoop package, so I'm not sure if I can help.


Could you check if you have enabled WSL and installed the WSL2 kernel package, again?
https://aka.ms/wsl2kernel

And If you are using other VM software (VMWare, VBox, etc.), it is possible that the Hyper-V function required by WSL2 cannot be used due to this.

**Comment by SonaliBendre** [comment]
> Thank you for reporting. But I'm sorry, I'm not the maintainer of the Scoop package, so I'm not sure if I can help.
> 
> Could you check if you have enabled WSL and installed the WSL2 kernel package, again? https://aka.ms/wsl2kernel
> 
> And If you are using other VM software (VMWare, VBox, etc.), it is possible that the Hyper-V function required by WSL2 cannot be used due to this.

Thanks for the fast reply. 
Updated my issue comment with system details

I run `wsl` in terminal and its working. I think its wsl2 since my build version is 220000
Yes I use WindowsSubsystemForAndroid

**Comment by SonaliBendre** [comment]
WSA is official product of microsoft

**Comment by SonaliBendre** [comment]
Please check Environment. I edited it

**Comment by SonaliBendre** [comment]
![image](https://user-images.githubusercontent.com/73757361/154797261-ae943559-e0f9-46d0-8a61-f4b5716b0ac9.png)
![image](https://user-images.githubusercontent.com/73757361/154797262-1fcd83d4-439a-4efe-afbd-360b6771d08f.png)

**Comment by SonaliBendre** [comment]
wsl2 is installed right?

**Comment by yuk7** [comment]
Thank you very much for filling environment infos.
Your WSL is enabled correctly. thank you.
But I'm not sure if your WSL2 is working.

Could you to install this package and try again?
https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**Comment by SonaliBendre** [comment]
OK.


BTW I had installed WindowsSubsystemForAndroid from https://github.com/LSPosed/MagiskOnWSA for rooting. Does it cause any problem?

**Comment by SonaliBendre** [comment]
thank you @yuk7 for the fix, ArchWSL started sucessfully but I got a one line error again :(((((
I afraid it may break my WSL setup :(((( I can't see scoop log so no idea what's the error is actually

see

```
Installing 'archwsl' (22.2.10.0) [64bit]
Loading Arch.zip from cache
Checking hash of Arch.zip ... ok.
Extracting Arch.zip ... done.
Linking ~\scoop\apps\archwsl\current => ~\scoop\apps\archwsl\22.2.10.0
Creating shim for 'Arch'.
Creating shortcut for Arch Linux (Arch.exe)
Persisting data
Running post-install script...
ERROR Exit code was 1!
WARN  DO NOT KILL THE PROCESS. Installation is still running!
'archwsl' (22.2.10.0) was installed successfully!
Notes
-----
Even when you are logging in as 'root', some operations (like service command) require Windows administrator privileges
```

**Comment by SonaliBendre** [comment]
![image](https://user-images.githubusercontent.com/73757361/154805698-441b2671-4a60-48fd-a9cb-2387452e9d03.png)

**Comment by SonaliBendre** [comment]
FIXED: `wsl --update`

**Comment by lxl66566** [comment]
I encountered the same error message. 
After a while, I [realized](https://github.com/microsoft/WSL/issues/4951) that the Hyper-V Windows feature was not enabled. Once I enabled it, the issue resolved.
