### ISSUE TITLE
Distribute ArchWSL through the `choco` package manager

### ISSUE THREAD

**Issue by Jarmos-san** [yuk7/ArchWSL#277]
**Describe the issue**
I'm aware ArchWSL is distributed through `scoop` but is it possible to distribute ArchWSL through [Chocolatey](https://chocolatey.org/)? I don't mind sharing a helping hand to package it for distribution through `choco`.

**Comment by Smart123s** [comment]
Duplicate of https://github.com/yuk7/ArchWSL/issues/104
