### ISSUE TITLE
Arch.exe not opening.

### ISSUE THREAD

**Issue by TheAwesomeGuy47** [yuk7/ArchWSL#278]
**Describe the issue**
Just extracted the Arch.zip folder, and tried opening Arch.exe, however it opens and closes immediately.

**To Reproduce**
Download latest release of ArchWSL. Extract Arch.zip and run Arch.exe.

**Expected behavior**
ArchWSL installer to open.

**Enviroment:**
 - Windows build number: 10.0.19043.1586
 - Security Software: AVG Antivirus Free, Malwarebytes Free
 - WSL version 1/2: 2
 - ArchWSL version: 22.3.18.0 
 - ArchWSL Installer type zip/appx/other clean/update: zip
 - Launcher version: 22020900

**Comment by rffontenelle** [comment]
If you run Arch.exe from a command-line interface (Command Prompt, PowerShell, Windows Terminal, etc.), can you tell if any message presented to you?

**Comment by JayBeavers** [comment]
Here is my experience using Arch installed via Scoop on Win11:

```
PS C:\Users\Jay\scoop\apps\archwsl\current> .\Arch.exe
Using: rootfs.tar.gz
Installing...
ERR: The system cannot find the file specified.
HRESULT: 0x80070002
Press enter to exit...
```

**Comment by JayBeavers** [comment]
In my case it was because I didn't have the wsl2 kernel update applied.  After applying this and uninstall/reinstall, worked fine.

**Comment by Quorsor** [comment]
Same thing happens to me. First install of mine worked fine but did some things and GLIBC problem happened so I tried reinstalling to fix and now I can't open Arch on Terminal or Exe.
