### ISSUE TITLE
Error 0x80072746

### ISSUE THREAD

**Issue by FelipeSavazii** [yuk7/ArchWSL#279]
```
Using: C:\Program Files\WindowsApps\yuk7.archwsl_22.3.18.0_x64__35zwpb4sx6e50\rootfs.tar.gz                             
Installing...                                                                                                           
ERR: Uma ligação existente foi forçada a fechar pelo anfitrião remoto.                                                  
HRESULT: 0x80072746                                                                                                     
Press enter to exit... 
```

How to fix it?

**Comment by lukesnc** [comment]
This is most likely because your install is placed under `C:\Program Files`
The ArchWSL documentation says "For example, `C:\Program Files` cannot be used since the rootfs cannot be modified there."
More on that [here](https://wsldl-pg.github.io/ArchW-docs/How-to-Setup/)

**Comment by lukesnc** [comment]
I'd recommend placing your install at the root of your C drive or somewhere else. I just made a folder at C:\Arch\ and put everything in there

**Comment by FelipeSavazii** [comment]
Oh, thank u
