### ISSUE TITLE
Supports Windows 10 April 2018 Update?

### ISSUE THREAD

**Issue by 0xBADDCAFE** [yuk7/ArchWSL#28]
ArchWSL works fine on Windows 10 1709. But update Windows from 1709 to 1803 (April 2018 Update), it doesn't work and get below output:

```
このディストリビューションの Linux ファイル システム用 Windows サブシステムのワンタイム アップグレードを実行しています...
エラー: 0x80070005
```

So I execute `Arch clean` and `Arch` to reinstall, but can't and get below output:

```
Installing...
ERROR:Installation Failed!
HRESULT:0x800700b7
```

I tried to install Ubuntu distro from store to check only the WSL works, and it works correctly. After I tried once to launch ArchWSL, but can't.

ArchWSL does not support Windows 10 April 2018 Update yet?

**Comment by yuk7** [comment]
I'm running ArchWSL on April Update.
ArchWSL is supporting April Update...

**Comment by 0xBADDCAFE** [comment]
Thanks. I'll check my environment again.

**Comment by 0xBADDCAFE** [comment]
I tried again this issue after closing, and find to lack these operation:

- Erase old rootfs and temp dir after uninstall for reinstalling.
- Run Arch.exe __as Administrator__ to Extract rootfs and Register to WSL (sorry, I forgot it when create this issue)

After these, ArchWSL works fine in my Windows.
