### ISSUE TITLE
[Outdated] C function `clock_getres` does not return zero in WSL1

### ISSUE THREAD

**Issue by horror-proton** [yuk7/ArchWSL#289]
**Describe the issue**
C function `clock_getres` does not return zero for monotonic clock in WSL1.

**To Reproduce**
- Install ArchWSL as WSL1 and install glibc-linux4 aur package as mentioned in docs; 
- Write a simple C program trying to get the resolution of monotonic clock with clock_getres function. e.g. 
  ```c
  #include <time.h>
  int main() {
      struct timespec t;
      return clock_getres(CLOCK_MONOTONIC, &t);
  }
  ```
- Compile (with gcc) and run, it returns 38 instead of 0; 

**Expected behavior**
The function should return 0. 

**Screenshots**

**Enviroment:**
 - Windows build number: 10.0.19044.1706
 - Security Software: nothing but Windows Defender
 - WSL version 1/2: WSL1
 - ArchWSL version 22.3.28.0
 - ArchWSL Installer type zip clean
 - Launcher version 22020900

**Additional context**
- glibc-linux4 version: 2.35-2
- gcc version: 12.1.0
- This may crash python script that use python asio module, ref. [source of cpython](https://github.com/python/cpython/blob/main/Modules/timemodule.c#L325).

**Comment by horror-proton** [comment]
The problem no longer exist since [glibc-linux4](https://aur.archlinux.org/packages/glibc-linux4) package were updated to 2.36-1, so perhaps it is an issue of glibc? 🤔 
@Heptazhou

**Comment by Toby222** [comment]
The problem seems to have been caused by the AUR package.
Feel free to close the issue if it's done

**Comment by Heptazhou** [comment]
@horror-proton
https://github.com/0h7z/aur/commit/11f0f33e3d7e6fc12c4d75bab953d002e3257361#diff-c13dbcca92f9ff12cd26ecce958be3f9ee8563baace04f7a463a6d2dd4252e0bR51-R52
🙂

**Comment by horror-proton** [comment]
> 

😨~~Oh great, I annoyed the upstream maintainer~~ I should have look through the upstream repository before asking. 😿
So in previous version, the function is returning `ENOSYS` by design, while in the latest version of PKGBUILD, the patch is not applied by default. 
Thanks for attention, the glibc-linux4 package helped us a lot.

**Comment by horror-proton** [comment]
Outdated
