### ISSUE TITLE
Docker Desktop WSL Integration not working: `[2304] Error loading Python lib ...`

### ISSUE THREAD

**Issue by sigurdo** [yuk7/ArchWSL#291]
Docker Desktop WSL Integration: I am not able to run `docker-compose` from the ArchWSL command line interface. Instead I get the following error:

```
[sigurd@Omar ~]$ docker-compose
[2304] Error loading Python lib '/tmp/_MEIdqNm0Y/libpython3.7m.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory
```

**To Reproduce**
- Install Docker Desktop in Windows
- Install ArchWSL
- Initialize keyring like described [here](https://wsldl-pg.github.io/ArchW-docs/How-to-Setup/#initialize-keyring)
- Upgrade all packages with `pacman -Syyu`
- Enable the Docker integration for Arch in Docker Desktop (Settings>Resources>WSL Integration)
- Run `docker-compose` in the ArchWSL command line

**Expected behavior**
The normal help output for the docker-compose command

**Enviroment:**
 - Windows build number: 10.0.22000.739
 - Security Software: Windows Defender
 - WSL version: WSL2
 - ArchWSL version: 22.3.18.0
 - ArchWSL Installer type: zip
 - Launcher version: 22020900

**Worthy mentions:**

The issue does not occur before you upgrade packages, so if you omit that step the docker-compose command would work nicely, but that is obviously not a good solution. I e.g. had to do this to get a good enough version of GLIBC for several other tools I need to use.

**Comment by sigurdo** [comment]
My current solution is to not use Docker Desktop for Windows, but rather natively install docker and docker-compose in Arch WSL. This is a little hassle, since you will have to set up a systemd alternative as specified [in the docs](https://wsldl-pg.github.io/ArchW-docs/How-to-Setup/#install-systemctl-alternative-optional) to start the docker daemon.

**Comment by bvolkmer** [comment]
It is solved by installing `libxcrypt-compat` in Arch

**Comment by sigurdo** [comment]
Wow, thanks, it works perfectly!
