### ISSUE TITLE
i cannot delete Arch

### ISSUE THREAD

**Issue by neondev27** [yuk7/ArchWSL#292]
i cannot delete .vhdx file, i tried delete it but it not be deleted.

**Comment by Toby222** [comment]
[This](https://github.com/yuk7/ArchWSL#exe-usage) lists a `clean` command to uninstall an instance.
Otherwise, make sure your WSL is shut down and nothing else is accessing the file?

**Comment by neondev27** [comment]
thx, i removed it before you write.

**Comment by rffontenelle** [comment]
Solved? If yes, please close the issue to keep this tracker cleaner. Thanks!

**Comment by neondev27** [comment]
ok
