### ISSUE TITLE
Latest release broke the pacman and keys

### ISSUE THREAD

**Issue by mulfyx** [yuk7/ArchWSL#299]
**Describe the issue**
Latest release ([22.10.2.0](https://github.com/yuk7/ArchWSL/releases/tag/22.10.2.0)) broke the pacman and keys

**To Reproduce**
1. Download [Arch_Online.zip](https://github.com/yuk7/ArchWSL/releases/download/22.10.2.0/Arch_Online.zip)
2. Extract archive
3. Run "Arch.exe"
4. Wait for download rootfs.tar.gz
5. Press "Enter"
6. Run "Arch.exe" again
7. Run "sudo pacman-key --init"

**Expected behavior**
Should be executed without errors

**Screenshots**
<img width="860" alt="image" src="https://user-images.githubusercontent.com/34765569/193957776-9f9335ff-2ce3-4c94-bedd-5f5d0aba2511.png">

**Enviroment:**
 - Windows build number: 10.0.22621.607
 - Security Software: -
 - WSL version 1/2: WSL2
 - ArchWSL version: 22.10.2.0
 - ArchWSL Installer type: zip, online
 - Launcher version: 22020900

**Comment by yuk7** [comment]
I confirmed this issue. I'll fix it.
Thank you.

**Comment by yuk7** [comment]
I fixed this issue in new release!
