### ISSUE TITLE
Cannot install base-devel, fakeroot already installed

### ISSUE THREAD

**Issue by ShayBox** [yuk7/ArchWSL#3]
A problem I've noticed is that fakeroot is installed but the system doesn't know it so it tries to install it but the files are already there and it fails, I've deleted the files manually and reinstalled the package but you should fix that ;)

**Comment by yuk7** [comment]
@ShayBox 
Thank you for your reporting.

Official fakeroot package is using SysV IPC call but WSL isn't support it.
Installed fakeroot-tcp package is using TCP IPC call,this can work in WSL. 
I don't recommend to install official fakeroot package.

If you uninstall installed faketoot-tcp package to run`pacman -R fakeroot-tcp`.

**Comment by yuk7** [comment]
@ShayBox 
and
I'll add fakeroot to conflict package.

Thanks.

**Comment by yuk7** [comment]
@ShayBox 
I released [new build](https://github.com/yuk7/ArchWSL/releases/latest) with new [fakeroot-tcp](https://github.com/yuk7/arch-prebuilt/releases/tag/17121600) package.

This problem has probably been fixed. I'll close this issue...
