### ISSUE TITLE
Openssl 3.x makes ArchWSL corrupt

### ISSUE THREAD

**Issue by Sheey11** [yuk7/ArchWSL#305]
**Describe the issue**
Installing `openssl 3.x` will make ArchWSL corrupt.
This package is a dependency of `base-devel`(`base-devel -> sudo -> openssl`), which is required to build an AUR.

**To Reproduce**
```
$ sudo pacman -Sy openssl
Packages (1) openssl-3.0.7-2
[===installing===]

$ pacman
pacman: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Enviroment:**
 - Windows build number: `10.0.22621.819`
 - Security Software: `Windows Defender`
 - WSL version 1/2: `WSL2`
 - ArchWSL version: `22.10.16.0`
 - ArchWSL Installer type: `appx`
 - Launcher version: `22020900`

**Comment by Toby222** [comment]
That's not beacuse of ArchWSL, that's just the consequences of a partial update.
openssl updated and a lot of things along with it, which now expect the new version.
Either download the libcrypto.so.1.1 and temporarily place it in /usr/lib manually, or, if available, install an older version cached by pacman and update all relevant packages at once

**Comment by Sheey11** [comment]
Acctually, I was encountered this issue when installing `base-devel`, which carries `pacman`, `sudo`, and some other base-level packages depends on `openssl`, so it's not a partial update. And most important, after pacman finishes installing `openssl`, all post-transaction were failed because they cannot found `libcrypto.so.1.1`, also validates this is not be a partial update issue.  
Btw, I tested `sudo 1.9.12p1-1` on an Arch VM, it works well with `libcrypto.so.3`.

---

Test again with a fresh installed ArchWSL:
```
$ sudo pacman -Sy sudo
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
resolving dependencies...
looking for conflicting packages...

Packages (2) openssl-3.0.7-2  sudo-1.9.12.p1-1

Total Download Size:    6.79 MiB
Total Installed Size:  17.79 MiB
Net Upgrade Size:       3.46 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 sudo-1.9.12.p1-1-x86_64                  1765.2 KiB  3.08 MiB/s 00:01 [#######################################] 100% openssl-3.0.7-2-x86_64                      5.1 MiB  4.06 MiB/s 00:01 [#######################################] 100% Total (2/2)                                 6.8 MiB  5.23 MiB/s 00:01 [#######################################] 100%
(2/2) checking keys in keyring                                         [#######################################] 100%
(2/2) checking package integrity                                       [#######################################] 100%
(2/2) loading package files                                            [#######################################] 100%
(2/2) checking for file conflicts                                      [#######################################] 100%
:: Processing package changes...
(1/2) upgrading openssl                                                [#######################################] 100%
(2/2) upgrading sudo                                                   [#######################################] 100%
ldconfig: Can't link /usr/lib/wsl/lib/libnvoptix_loader.so.1 to libnvoptix.so.1
ldconfig: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

:: Running post-transaction hooks...
(1/3) Reloading system manager configuration...
systemd-detect-virt: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
  Skipped: Current root is not booted.
(2/3) Creating temporary files...
/usr/bin/systemd-tmpfiles: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
error: command failed to execute correctly
(3/3) Arming ConditionNeedsUpdate...
```

**Comment by Toby222** [comment]
What you showed is just updating openssl, after which the things dependant on openssl 1.1 break, since you just uninstalled that.
A full system update `pacman -Syu` should fix this.

**Comment by horror-proton** [comment]
I think it **is** a partial update, you've just updated `openssl` by running pacmam with `-Sy` but other packages depending on `openssl` were not updated, so the shared library dependencies were broken.

If pacman and sudo also broken, you may login as root (maybe with `wsl.exe -d Arch -u root`) and download `pacman-static` manually as a workaround
```
wget https://pkgbuild.com/~morganamilo/pacman-static/x86_64/bin/pacman-static
chmod a+x pacman-static
./pacman-static -Syu
```
or install `openssl-1.1` first and then `pacman -Syu`.

Always remember: 
>  **In practice, do not run pacman -Sy package_name instead of pacman -Syu package_name, as this could lead to dependency issues.**[^1]

[^1]: https://wiki.archlinux.org/title/Pacman#Installing_packages

**Comment by Sheey11** [comment]
@horror-proton You're right, `-Syu` do fix this. A reason I hate `-Syu` is because last time it sabotaged ArchWSL's `glibc`(an ancient ArchWSL version which even carries `systemd`), and I spent lot of time fixing that. So I bearly using `-Syu` on ArchWSL. I see ArchWSL is stable now. Appreciate ur help.
