### ISSUE TITLE
After pacman update I see no files at all

### ISSUE THREAD

**Issue by nursoda** [yuk7/ArchWSL#318]
A couple of days ago, I started and updated my ArchWSL on my T14, as I did many times before. Nothing special. I shut down Windows, dual-booted to native Arch, my default work environment. Worked on Linux natively.

Today, I dual-booted to Windows to do updates. After finishing Windows updates, I started ArchWSL. I got an error:

```
$ pacman -Suy
pacman: error while loading shared libraries: /usr/lib/libnghttp2.so.14: file too short
```
I got root to investigate whether library linking got broken during the last update. Strange thing is: I cannot list ANY files inside the ArchWSL, although filename-completion DOES work:

```
# ls -la /
# cat /etc/os-release
```

Both commands yield no output, but bash doesn't see an error upon execution:

```
# echo $?
0
```

**To Reproduce**

I have no idea how to reproduce this.

**Expected behavior**

Well, clearly I'd expect files to be visible and accessible.

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.22621.1555]
 - Security Software: just the default Microsoft Defender
 - WSL version 1/2: WSL 2
 - ArchWSL version: How to list that?
 - ArchWSL Installer type: probably rootfs tarball, don't know exactly, quite a while ago. I did not update the ArchWSL installer knowingly.
 - Launcher version: 22020900

**Comment by jfdtse** [comment]
If you can, reinstall libnghttp2 and see if the issue was during the installation:

pacman -Sy libnghttp2

**Comment by nursoda** [comment]
The point I'm trying to make is that it's not about this specific library. There's nothing to reinstall here, the ACCESS to files, or the READING of them is broken way deeper in the system.

![grafik](https://user-images.githubusercontent.com/8425483/233748739-1f506029-2988-4867-bf7a-b024bc53051e.png)

**Comment by nursoda** [comment]
I did not try to replace binaries since the system seemed corrupt altogether. It was a playground, so I discarded it. Sclosing since noone else seems to have seen the same issue.
