### ISSUE TITLE
Can I set custom host name instead of using of using the same host name with Windows?

### ISSUE THREAD

**Issue by onlyice** [yuk7/ArchWSL#32]
Hi yuk7,

I use [yadm](https://github.com/TheLocehiliosan/yadm) to manage my dot files and configurations. Yadm provides [ability](https://thelocehiliosan.github.io/yadm/docs/alternates) to symlink different files for different host names.

It'll be convenient to support setting custom host name for WSL instance.

**Comment by yuk7** [comment]
Hi.
I think you can add `sudo hostname ***`
to bashrc...

**Comment by onlyice** [comment]
OK... It works. 👍 💯

**Comment by alenpaul2001** [comment]
Is there any other workaround other than using that command in bashrc?
