### ISSUE TITLE
error 0x8007003

### ISSUE THREAD

**Issue by pjkasper** [yuk7/ArchWSL#33]
Had the same experience as others earlier  with the April update
BUT Running wslconfig /u Arch:

Unregistering...
Error: 0x80070003   <- still there!

Then it Worked!

**Comment by pjkasper** [comment]
Ok, not an issue anymore, still some might learn, thank you, Throstur

regards /pjkasper

**Comment by TheMulti0** [comment]
I still encounter this error after 'unregistering' arch multiple times. Please tell me if there's a solution to that.
