### ISSUE TITLE
Default user don't work

### ISSUE THREAD

**Issue by SurPaul** [yuk7/ArchWSL#34]
I made a shortcut in the Start menu with the following option:
> "C:\Users\SurPa\AppData\Roaming\Arch Linux\Arch.exe" config --default-user surpaul

But when I click on this shortcut, cmd opens and closes immediately. When I try to run the same thing from a command line, nothing happens either.

![image](https://user-images.githubusercontent.com/1708881/42755727-6cad2a5c-890a-11e8-9c01-51788bff89fe.png)

**Comment by yuk7** [comment]
Could you try reboot computer?
Please see issue #7

**Comment by SurPaul** [comment]
Sorry, did not see the closed issues.
This command should be entered once, after that the profile will be loaded by default? For some reason, I thought that I need to open each time with these arguments.

Thanks for ArchWSL and help!
