### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by kilbith** [yuk7/ArchWSL#35]
```
C:\Users\Jean-Patrick\Downloads\Arch>Arch.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x8007019e
Press any key to continue...
```

Cmd.exe admin of course
Windows 10 Pro, 1803, OS build 17134.112

**Comment by yuk7** [comment]
Is the Windows Subsystem for Linux optional component enabled? 
Please enable it and try again.

**Comment by kilbith** [comment]
Stupid me. Sorry.
