### ISSUE TITLE
Arch_Online.zip uses very old rootfs

### ISSUE THREAD

**Issue by Ivoz** [yuk7/ArchWSL#352]
It seems the `preset.json` file is hardcoded to download the `22101600` version of rootfs. I'd think it would want to download like a '24 version. Maybe, for ease of future maintance, you want to remove this method, or remove  `preset.json` being distributed by default; if its missing, then Arch_Online just tries to download a latest release rootfs. Just suggestions.

**Comment by yuk7** [comment]
Thank you for creating this issue.🙏
I'll work to fix this issue.

**Comment by yuk7** [comment]
Fixed!
