### ISSUE TITLE
Issues loading libQt5Core.so

### ISSUE THREAD

**Issue by sergeken** [yuk7/ArchWSL#36]
Hi,
Thanks for the effort to provide this utility to use ArchLinux on WSL.
I did face an issue when using qtcreator and after some digging I found the issue is know and that there is a workaround & fix.  I even believe you know that one too.  If not here is the reference: [chroot-fixups/qt5-core-abi.sh: make libQt5Core.so.5 load on el7 kernel](https://github.com/kdudka/csmock/commit/96a4a759a7de39f8da109202f4fa14c76a0ae68f).

Could you maybe document this workaround on the main page?

And as a side question.  Why do you use faketoot-tcp in stead of the main one?

**Comment by yuk7** [comment]
Hi.
1. I added link to Wiki in main page.
Could you use it? I'd like to write about this issue there...
2. fakeroot is need by building AUR packages.
but official one isn't work on WSL.(because ICP syscall missing)

**Comment by yuk7** [comment]
I wrote about it on wiki.
https://github.com/yuk7/ArchWSL/wiki/Known-issues#qt5
Please check it.

**Comment by sergeken** [comment]
Looks good to me.
Maybe it is also good to add a reference to the ICP syscall issue (fakeroot).  It could bite users are other places.
All in all, I like WSL so far performance and usability wise.
