### ISSUE TITLE
Windows Defender reports Trojan from release 24.3.31.0

### ISSUE THREAD

**Issue by leonardoAtma** [yuk7/ArchWSL#361]
# Too Funny:

I've been using this distro for quite some time. However, in the latest version, during installation, Windows Defender flagged Win32/Vigorf.A.
![image](https://github.com/yuk7/ArchWSL/assets/149166387/2771931f-55d3-438b-8284-ed09808e2b23)

In version 24.3.11.0, there were no reports from Windows Defender. 
![image](https://github.com/yuk7/ArchWSL/assets/149166387/2855a1d1-e581-4bd5-bd29-6864015369ef)

**Comment by tendertree** [comment]
same thing,
try to install again. it warning again

**Comment by yuk7** [comment]
I think it's a false positive and I'll look into it later

**Comment by yuk7** [comment]
Yesterday I released a new build.
I have confirmed that 24.3.31.0 is falsely detected by Defender in my environment.
The newly released 24.4.26.0 does not seem to have this problem.
This issue will be marked as resolved and closed.
