### ISSUE TITLE
How Do i uninstall

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [yuk7/ArchWSL#368]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Docs](https://git.io/arch-doc) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
I just want to reinstall it

**To Reproduce**
1.Download the exe and set it up

**Expected behavior**
to be able to uninstall

**Screenshots**

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.22631.3527]
 - Security Software: Windows Defender
 - WSL version 1/2: WSL2
 - ArchWSL version 2
 - ArchWSL Installer type zip
 - Launcher version 24.4.28.0

**Additional context**

**Comment by yuk7** [comment]
Hi,
Have you tried the `Arch.exe clean` command?

**Comment by GuestSneezeOSDev** [comment]
no i havent thank you
