### ISSUE TITLE
Can't run without Admin rights

### ISSUE THREAD

**Issue by ShinobiWPS** [yuk7/ArchWSL#37]
As the title says, I set it with the User setting entry, instead of `bash.exe` but it just hangs.

Also, since Arch Wsl need to be run by Admin everytime I wonder if this thing will ever work.

**Comment by sergeken** [comment]
AFAIK you don't need admin anymore with the Windows 10 April 2018.
The only issue I do face is that after booting it takes a while before WSL "sees" Arch Linux.

**Comment by ShinobiWPS** [comment]
If I don't run it with Admin rights I get the popular `Error 0xNumbersNumbers`memory error.


Have you tried using Arch.exe as Shell for VS Code?

**Comment by sergeken** [comment]
No, I haven't used with VS code.  I use vs-code for linux under the WSL and
a windows X-server.

**Comment by ShinobiWPS** [comment]
Sadly, the issue then remains open .

**Comment by yuk7** [comment]
Hi. Thank you for reporting
but I tried it in VSCode internal terminal but It seems work...
![37](https://user-images.githubusercontent.com/29954265/43894117-1c5459e4-9c0c-11e8-9aec-473a9a7377d2.png)

Could you check this:
Do you have write permission of Installed folder? For example, it may not work properly in 'Program Files',etc.

and could you give me additional infomation?
1. Windows version (`ver` command output in `cmd`)
2. Shell you are using in Arch
3. VScode version
4. Does user has admin rights?

**Comment by ShinobiWPS** [comment]
🎉 Solved! and  I think the Readme should specify more info/pitfalls:

To make Arch WSL work WITHOUT Admin rights, you have to avoid `Program Files`-like or system folders and put it somewhere else so Windows will NOT request Admin rights to run it.

I found the expected way of making it work with WSL system INSIDE VS CODE as embedded terminal:

1. Install Arch in non-admin/system folder (it will register to WSL system
2. Make sure in CMD/PowerSHell you have ARCH as Default distro ( `wslconfig /l` )
3. IN VS Code, in your User Preferences instead of pointing to `C:\\full_path\to\bash.exe` set to: `"terminal.integrated.shell.windows": "wsl.exe"`

Explaination: you call distros in multiple ways one is obviously `bash.exe` or `ubuntu.exe` for Ubuntu, `debian.exe` for Debian , and so on...BUT there is also `wsl.exe` which :

-  launch a shell from the inside of the Default distro, AND 
- since wsl.exe is in Windows `PATH` you don't need to specify location in VS Code.


I now ahve moved my Arch WSL instalaltion and everything works in the way stated above, I Have not tried to call Arch.exe directly from VS Code.
@yuk7 Are you able to do so? if yes, I trust the issue can be closed, hoping it will be a solution for someone else :)

**Comment by ShinobiWPS** [comment]
since this is solved we can close the issue

**Comment by yuk7** [comment]
ok.
I'll close.

**Comment by yuk7** [comment]
Really?
I tried Arch.exe in VSCode shell when this issue opened,but it was working...
