### ISSUE TITLE
pacman failed after reboot

### ISSUE THREAD

**Issue by Karmenzind** [yuk7/ArchWSL#38]
Thanks for your job.

I installed ArchWSL yesterday. The update failed in this morning.
```
[root@pc-hz20097394 ~]# pacman -Sy
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
:: Synchronizing package databases...
 core                       0.0   B  0. core                     735.0   B   103K/s 00:00
 core.sig                   0.0   B  0. core.sig                 739.0   B  0.00B/s 00:00
error: GPGME error: No data
error: failed to update core (invalid or corrupted database (PGP signature))
 extra                      0.0   B  0. extra                    737.0   B  0.00B/s 00:00
 extra.sig                  0.0   B  0. extra.sig                741.0   B  0.00B/s 00:00
error: GPGME error: No data
error: failed to update extra (invalid or corrupted database (PGP signature))
 community                  0.0   B  0. community                745.0   B  0.00B/s 00:00
 community.sig              0.0   B  0. community.sig            749.0   B  0.00B/s 00:00
error: GPGME error: No data
error: failed to update community (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```
I've tried every method mentioned in this topic https://bbs.archlinux.org/viewtopic.php?id=142798&p=2 but none of them worked.
I think it might be something special with ArchWSL because I've never met this problem in pure ArchLinux.

**Comment by yuk7** [comment]
I don't confirm this issue yet,
but try this for refresh keys:
```
sudo rm -R /etc/pacman.d/gnupg
sudo pacman-key --init
sudo pacman-key --populate antergos archlinux
sudo pacman-key --refresh-keys
sudo pacman -Syyu
```

**Comment by Karmenzind** [comment]
Thank you. It recovered after reboot...

Here is another pacman problem that I've met twice on ArchWSL. I had to reboot several times to see if it disappears.
```
# pacman -S
error: libutf8proc: signature from "Alexander Rødseth <rodseth@gmail.com>" is invalid
:: File /var/cache/pacman/pkg/libutf8proc-2.1.1-4-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: apr: signature from "Anatol Pomozov <anatol.pomozov@gmail.com>" is invalid
:: File /var/cache/pacman/pkg/apr-1.6.3-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: apr-util: signature from "Bartlomiej Piotrowski <b@bpiotrowski.pl>" is invalid
:: File /var/cache/pacman/pkg/apr-util-1.6.1-3-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: serf: signature from "Jan de Groot <info@jandegrootict.nl>" is invalid
:: File /var/cache/pacman/pkg/serf-1.3.9-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: subversion: signature from "Evangelos Foutras <evangelos@foutrelis.com>" is invalid
:: File /var/cache/pacman/pkg/subversion-1.10.2-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
```

I've searched the wiki. https://wiki.archlinux.org/index.php/Pacman/Package_signing#Troubleshooting
But the time of ArchWSL is correct and the same with the time of win10. And WSL doesn't support the hwclock https://github.com/Microsoft/WSL/issues/193 so I don't know how to "correct the clock".
Do you have any idea to fix it?

**Comment by Karmenzind** [comment]
BTW, I put the ArchWSL rootfs in D:\somewhere, not C. Does it have any bad influence?

**Comment by yuk7** [comment]
I recommended to install to C:.,but I think that there is no problem if it starts up.

**Comment by yuk7** [comment]
Have you edited pacman.conf or mirrorlist? What kind of setting was Arch?
I cleanly installed the 18081100 release and run `pacman - Sy`, but it was working...

Please tell me more infomation?
* Windows build (`ver` commands output)
* ArchWSL version

**Comment by Karmenzind** [comment]
win10 \ 1709 \ 10.0.16299.98
ArchWSL is 18081100.

I replaced the mirrorlist with the one I sorted by speed. 
https://github.com/Karmenzind/dotfiles-and-scripts/blob/master/others/ranked_mirrorlist
When pacman failed, I tried restoring the original mirrorlist, but no luck.

-----

> I recommended to install to C:

Can I simply move the directory (including Arch.exe and rootfs) to C? 

> I cleanly installed the 18081100 release and run pacman -Sy

Maybe you can shutdown your pc before 0:00 and try again the next day.

> What kind of setting was Arch?

Sorry I don't understand what you mean.

-----

If I close the terminal and reopen it, it seems like the ArchWSL has been rebooted(the uptime turns to zero), not like the official WSLs which could run as daemon. So I have to keep the terminal on. Is there anyway to fix it?

**Comment by yuk7** [comment]
>When pacman failed, I tried restoring the original mirrorlist, but no luck.

Ok. It looks like it is not a mirror server problem 

>Can I simply move the directory (including Arch.exe and rootfs) to C?

No you can't. You must unregister.

>If I close the terminal and reopen it, it seems like the ArchWSL has been rebooted(the uptime turns to zero), not like the official WSLs which could run as daemon. So I have to keep the terminal on. Is there anyway to fix it?

hmm... I'll check it later...

**Comment by Karmenzind** [comment]
Thank you. 

```
No you can't. You must unregister.
```
So I just need to move the dir to C and relogin or reboot to make it work?

**Comment by Karmenzind** [comment]
...got it.

**Comment by YuyQuan** [comment]
I think I'm having the same issue with mirrors
Win 10 / 1803 / 17733.1000
ArchWSL 18081100

Here's what I get when I run pacman -Syu

```
[root@Quan /]# sudo pacman -Syu
:: Synchronizing package databases...
^[uerror: failed retrieving file 'core.db' from mirrors.evowise.com : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'core.db' from mirrors.kernel.org : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'core.db' from mirrors.kernel.org : Resolving timed out after 10000 milliseconds
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from mirrors.evowise.com : Resolving timed out after 10000 milliseconds
^C
Interrupt signal received
```

I followed 

> sudo rm -R /etc/pacman.d/gnupg
> sudo pacman-key --init
> sudo pacman-key --populate
> sudo pacman-key --refresh-keys
> sudo pacman -Syyu

but got stuck at --refresh-keys

```
[quan@Quan pacman.d]$ sudo pacman-key --refresh-keys
gpg: refreshing 104 keys from hkps://hkps.pool.sks-keyservers.net
gpg: keyserver refresh failed: Server indicated a failure
==> ERROR: A specified local key could not be updated from a keyserver.
[quan@Quan pacman.d]$
```

I think rinkmirrors isn't installed because I get

```
[root@Quan /]# rankmirrors -n 6 mirror.bak > /etc/pacman.d/mirrorlist
-bash: rankmirrors: command not found
[root@Quan /]#
```

**Comment by yuk7** [comment]
@YuyQuan 
It is separate issue... It does not seem to be connected to the Internet.
Please check Internet connection stability.

**Comment by yuk7** [comment]
@YuyQuan 
Does the nameservers work?
Have you launched `Arch.exe` while connected to the Internet?
WSL instances generates `resolv.conf` at them startup.

Please tell me `cat /etc/resolv.conf` output.

**Comment by YuyQuan** [comment]
![image](https://user-images.githubusercontent.com/15720568/44504852-d7f60d80-a663-11e8-9798-518a9178b234.png)

/etc/resolv.conf
```
# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.
nameserver 192.168.0.30
nameserver 2001:558:feed::1
nameserver 2001:558:feed::2
search hsd1.il.comcast.net.
```

Nothing  out of the ordinary as this looks like my arch VM. ping likes to hang, but windows is connected and stable.

**Comment by Karmenzind** [comment]
```
If I close the terminal and reopen it, it seems like the ArchWSL has been rebooted(the uptime turns to zero), not like the official WSLs which could run as daemon. So I have to keep the terminal on. Is there anyway to fix it?
```

I found a way to keep it running. https://github.com/goreliu/wsl-terminal/blob/master/src/etc/wsl-terminal.conf#L23
