### ISSUE TITLE
Reinstall WSL Arch Linux

### ISSUE THREAD

**Issue by thegospelofluke** [yuk7/ArchWSL#381]
How do I reinstall WSL Arch Linux? Is there such a possibility?

**Comment by yuk7** [comment]
yes, it's possible.
run `arch.exe clean` and `arch.exe install`.
this will remove all archwsl data and install from scratch.

**Comment by thegospelofluke** [comment]
> yes, it's possible. run `arch.exe clean` and `arch.exe install`. this will remove all archwsl data and install from scratch.

ty so much.
