### ISSUE TITLE
Cannot install ArchWSL

### ISSUE THREAD

**Issue by Infernion** [yuk7/ArchWSL#40]
I used to have Ubuntu installed to WLS, but cannot install Arch WSL. I've gotten HRESULT:0x8000000d error. Either run with root or not, which is strange.

**Comment by yuk7** [comment]
Please give me additional information:
1. Windows build version (output of `ver` command)
2. ArchWSL version

and Check these:
1. Is WSL fetuse enabled?
2. WSL instance can install on C: drive.
3. Do not extract to system directory(Program Files,etc...)
3. Does extracted folder has write permission?

**Comment by Infernion** [comment]
Thanks for fast anwser!

1. Microsoft Windows [Version 10.0.17134.228]
2. Latest one (But I've to tried previouse one someday ago, with previous Windows build and got error, but cannot remember if it had similar error code)

- WSL feature is enbaled. I currently use Ubuntu 18.04 image.
- WSL is installed to C:/Apps/Arch and this folder has write permission. Even I make it read only the error is steel similar. So I gues the error happens befor any writing.

**Comment by yuk7** [comment]
Ok. I think that there is no problem in your environment.
That HRESULT means E_ILLEGAL_STATE_CHANGE.
I first received a report of this error,I still don't know about it...

**Comment by yuk7** [comment]
Windows 10 1803's WSL service is unstable.
It may not be working properly, please restart the service and retry...
in admin prompt:
```
sc stop LxssManager
sc start LxssManager
```

**Comment by Infernion** [comment]
Restarting doesn't help. Will be waiting to Windows update, maybe it will help. Thanks for advices

**Comment by altercation** [comment]
Right click run as administrator seems to get past this same error here...

**Comment by Infernion** [comment]
Of course, I've used admin mode to run this app. The problem in the specific version of Windows

**Comment by jorpilo** [comment]
Hello.

I have windows version 10.0.19042 and I am facing the same error. I have also tried with and without root.

Using: C:\Arch\rootfs.tar.gz
Installing...
ERROR:Installation Failed!
HRESULT:0x8000000d
Press any key to continue...


Is there any way to get more detailed logs?

**Comment by escape0707** [comment]
@jorpilo This? https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-winapps-appscat_tools/0x8000000d-ubuntu-installation-fails-with-error/dde92478-bcaf-41a1-a204-8cbf31273ca2

**Comment by jorpilo** [comment]
I performed the actions in the link and tried to run the installer with root but I still get the same error

**Comment by escape0707** [comment]
@jorpilo Okay, then. I think the discussions should be guided here:

https://github.com/microsoft/WSL/issues/4084
