### ISSUE TITLE
ip addr failed

### ISSUE THREAD

**Issue by Karmenzind** [yuk7/ArchWSL#41]
win10 \ 1709 \ 10.0.16299.98
ArchWSL is 18081100.

I just found the ssh doesn't work. Then I checked the ip status.

```
k@pc-hz20097394 : ~ [0] % ip addr
DONE truncated
Dump terminated
```

**Comment by yuk7** [comment]
I think `ip addr` issue is WSL's. Probably, it was fixed in Windows 10 build 1803.
If you don't want to update the build you can use `ifconfig` (etc) instead.
