### ISSUE TITLE
ArchWSL Install not working under Windows 10 Enterprise 1803 - build 17134.228

### ISSUE THREAD

**Issue by mdwhitis** [yuk7/ArchWSL#43]
**Describe the issue**
After install and running pacman-key commands successfully.  I get:

[root@XFactor ~]# pacman-key --init
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key 7145C0492CFBCFDF marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/B9DB93F55496D48C90B3B56A7145C0492CFBCFDF.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
[root@XFactor ~]# pacman-key --populate
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key DDB867B92AA789C165EEFA799B729B06A680C281...
  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...
  -> Locally signing key 91FFE0700E80619CEB73235CA88E23E377514E00...
  -> Locally signing key AB19265E5D7D20687D303246BA1DFB64FFF979E7...
  -> Locally signing key 0E8B644079F599DFC1DDC3973348882F6AC6A4C2...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabling key 7FA647CD89891DEDC060287BB9113D1ED21E1A55...
  -> Disabling key D4DE5ABDE2A7287644EAC7E36D1A9E70E19DAA50...
  -> Disabling key 40440DC037C05620984379A6761FAD69BA06C6A9...
  -> Disabling key B1F2C889CB2CCB2ADA36D963097D629E437520BD...
  -> Disabling key BC1FBE4D2826A0B51E47ED62E2539214C6C11350...
  -> Disabling key 63F395DE2D6398BBE458F281F2DBB4931985A992...
  -> Disabling key 8F76BEEA0289F9E1D3E229C05F946DED983D4366...
  -> Disabling key 4FCF887689C41B09506BE8D5F3E1D5C5D30DB0AD...
  -> Disabling key FB871F0131FEA4FB5A9192B4C8880A6406361833...
  -> Disabling key 81D7F8241DB38BC759C80FCE3A726C6170E80477...
  -> Disabling key 5E7585ADFF106BFFBBA319DC654B877A0864983E...
  -> Disabling key 50F33E2E5B0C3D900424ABE89BDCF497A4BBCC7F...
  -> Disabling key E7210A59715F6940CF9A4E36A001876699AD6E84...
  -> Disabling key F5A361A3A13554B85E57DDDAAF7EF7873CFD4BB6...
  -> Disabling key 40776A5221EF5AD468A4906D42A1DB15EC133BAD...
  -> Disabling key 8CF934E339CAD8ABF342E822E711306E3C4F88BC...
  -> Disabling key 5696C003B0854206450C8E5BE613C09CB4440678...
  -> Disabling key 9515D8A8EAB88E49BB65EDBCE6B456CAF15447D5...
  -> Disabling key 4A8B17E20B88ACA61860009B5CED81B7C2E5C0D2...
  -> Disabling key 0B20CA1931F5DA3A70D0F8D2EA6836E1AB441196...
  -> Disabling key 34C5D94FE7E7913E86DC427E7FB1A3800C84C0A5...
  -> Disabling key 39F880E50E49A4D11341E8F939E4F17F295AFBF4...
  -> Disabling key 66BD74A036D522F51DD70A3C7F2A16726521E06D...
  -> Disabling key DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A...
  -> Disabling key 07DFD3A0BC213FA12EDC217559B3122E2FA915EC...
  -> Disabling key 44D4A033AC140143927397D47EFD567D4C7EA887...
  -> Disabling key 27FFC4769E19F096D41D9265A04F9397CDFD6BB0...
  -> Disabling key 8840BD07FC24CB7CE394A07CCF7037A4F27FB7DA...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: bad data signature from key 20E8A9C77716EB4F: Wrong key usage (0x19, 0x2)
gpg: depth: 0  valid:   1  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: bad data signature from key 20E8A9C77716EB4F: Wrong key usage (0x19, 0x2)
gpg: depth: 1  valid:   5  signed:  70  trust: 0-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:  70  signed:   8  trust: 70-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2018-12-13
[root@XFactor ~]# pacman -Syy
\:: Synchronizing package databases...
error: failed retrieving file 'core.db' from mirrors.evowise.com : Empty reply from server
error: failed retrieving file 'core.db' from mirrors.kernel.org : Empty reply from server
error: failed retrieving file 'core.db' from mirrors.kernel.org : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.kernel.org:443
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from mirrors.evowise.com : Empty reply from server
error: failed retrieving file 'extra.db' from mirrors.kernel.org : Empty reply from server
error: failed retrieving file 'extra.db' from mirrors.kernel.org : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.kernel.org:443
error: failed to update extra (download library error)
error: failed retrieving file 'community.db' from mirrors.evowise.com : Empty reply from server
error: failed retrieving file 'community.db' from mirrors.kernel.org : Empty reply from server
error: failed retrieving file 'community.db' from mirrors.kernel.org : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.kernel.org:443
error: failed to update community (download library error)
error: failed to synchronize all databases
[root@XFactor ~]# pacman -Syyu
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from mirrors.evowise.com : Empty reply from server
error: failed retrieving file 'core.db' from mirrors.kernel.org : Empty reply from server
error: failed retrieving file 'core.db' from mirrors.kernel.org : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.kernel.org:443
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from mirrors.evowise.com : Empty reply from server
error: failed retrieving file 'extra.db' from mirrors.kernel.org : Empty reply from server
error: failed retrieving file 'extra.db' from mirrors.kernel.org : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.kernel.org:443
error: failed to update extra (download library error)
error: failed retrieving file 'community.db' from mirrors.evowise.com : Empty reply from server
error: failed retrieving file 'community.db' from mirrors.kernel.org : Empty reply from server
error: failed retrieving file 'community.db' from mirrors.kernel.org : OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mirrors.kernel.org:443
error: failed to update community (download library error)
error: failed to synchronize all databases

**To Reproduce**

**Expected behavior**
Pacman to work

**Screenshots**

**Enviroment:**
 - Windows build number: [e.g. 10.0.17134.228] (Type `ver` at a Command Prompt)
 - ArchWSL version [e.g. 18081100] (version of zip)
 - Launcher version [e.g. 18080900] (Type `Arch.exe version` at a Command Prompt)

**Additional context**

**Comment by yuk7** [comment]
Does the nameservers work?
Have you launched `Arch.exe` while connected to the Internet?
WSL generates `resolv.conf` at startup.

Please tell me `cat /etc/resolv.conf` output.

Thanks.

**Comment by mdwhitis** [comment]
[root@XFactor ~]# cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic 
generation of this file, remove this line.
nameserver 10.128.128.128
nameserver fec0:0:0:ffff::1
nameserver fec0:0:0:ffff::2

**Comment by yuk7** [comment]
Ok. Probably,It seems that creation of resolv.conf is done.
Please also tell me the output of these commands to isolate the problem:
```
ping mirrors.kernel.org -c 4
curl https://mirrors.kernel.org -o /dev/null
```

**Comment by yuk7** [comment]
Ok. It seems that resolv.conf was generated correctly.
Is the computer connected to the internet?
Please excute these line in Arch shell
```
ping 8.8.8.8 -c 4
ping www.google.com -c 4
```

**Comment by mdwhitis** [comment]
[root@XFactor ~]# ping mirrors.kernel.org -c 4 ; curl 
https://mirrors.kernel.org -o /dev/null
PING mirrors.pdx.kernel.org (198.145.21.9) 56(84) bytes of data.
64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=1 ttl=54 
time=26.5 ms
64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=2 ttl=54 
time=28.2 ms
64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=3 ttl=54 
time=27.5 ms
64 bytes from mirrors.pdx.kernel.org (198.145.21.9): icmp_seq=4 ttl=54 
time=29.4 ms

--- mirrors.pdx.kernel.org ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 6ms
rtt min/avg/max/mdev = 26.514/27.901/29.354/1.045 ms
   % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                  Dload  Upload   Total   Spent Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- 
--:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 
mirrors.kernel.org:443
[root@XFactor ~]#

**Comment by mdwhitis** [comment]
I fixed it. Here's what I did, as root.

mkdir /mnt/c/ProgramData/ssh
cp /mnt/c/Windows/System32/OpenSSH/sshd_config_default /mnt/c/ProgramData/ssh/sshd_config
sshd.exe

**Comment by yuk7** [comment]
ok. got it.

**Comment by wim07101993** [comment]
Hello, I have the same problem. I copied the sshd config as stated in the solution, but now i get a "Privilege separation user sshd does not exist" from sshd.exe...
Still an empty response from server with pacman.

**Comment by wim07101993** [comment]
Never mind, Kaspersky is not happy with WSL

**Comment by amiralkizaru** [comment]
Had the same issue
Solved it with
`sudo pacman -Syu i3`
Putting that here in case someone needs it
