### ISSUE TITLE
how fix that?

### ISSUE THREAD

**Issue by NycuRO** [yuk7/ArchWSL#47]
When i open "Arch.exe" i got that: "Error: 0x80070002" ..

**Comment by yuk7** [comment]
Please fill the template contents.

**Comment by kingdevnl** [comment]
Same error

**Comment by unixfox** [comment]
If you get this error it's because you deleted `rootfs.tar.gz`.

**Comment by kingdevnl** [comment]
Nope I even get it when it's there

**Comment by omrisim210** [comment]
I also get this. I tried to delete the folders created by `Arch.exe` from explorer (stupid, I know) and now I can't uninstall or reinstall it. If you need any more info I'll gladly supply it
