### ISSUE TITLE
Auto Populate?

### ISSUE THREAD

**Issue by DovaMerith** [yuk7/ArchWSL#48]
I have an idea, that sounds/is complicated,

Have a script, that is temporarily in the AWSL System, that runs the `pacman-key` commands automatically, then removes itself on the first run?

I think it would be something like this

`#!/bin/bash`
`pacman-key --init`
`pacman-key --populate`
`rm -f /path/to/autostart/pacman-key.sh`

Or possibly have an alias setup like so
`alias pac-key="pacman-key --init && pacman-key --populate"`

So that they don't have to manually copy/paste two commands.

**Comment by yuk7** [comment]
Thank you for your feedback.
But personally I do not think that it is necessary...
Even if you automate the populate, it seems that time and effort does not change much...
