### ISSUE TITLE
Unable to reinstall `Error: 0x80070005`

### ISSUE THREAD

**Issue by abelsromero** [yuk7/ArchWSL#52]
**Describe the issue**
After a successful installation, if you delete the files and attempt to install again in the same or different path, the message `Error: 0x80070005` appears in the shell (using cmd) and nothing happens.

**To Reproduce**
1. Run "Arch.exe"
2. Delete created folders
3. Run "Arch.exe" again

**Expected behavior**
I would like to install a clean folder structure with a fresh installation

**Screenshots**

**Enviroment:**
- Microsoft Windows [Versión 10.0.16299.431]
- ArchWSL 18081100
- wsldl, version 18080900

**Comment by ShayBox** [comment]
You need to run `Arch.exe uninstall`

**Comment by abelsromero** [comment]
I run `clean` instead and it worked! Thanks for the hint
