### ISSUE TITLE
Process's not shared

### ISSUE THREAD

**Issue by ShayBox** [yuk7/ArchWSL#53]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
ArchWSL is not showing windows process's

**To Reproduce**
run "htop"

**Expected behavior**
Show windows process's

**Screenshots**
![image](https://user-images.githubusercontent.com/9505196/45534404-fb2a5d80-b7c8-11e8-9405-a8cf709ffaa1.png)

**Enviroment:**
 - Windows build number: [e.g. 10.0.17134.228] (Type `ver` at a Command Prompt)
Microsoft Windows [Version 10.0.17134.285]
![image](https://user-images.githubusercontent.com/9505196/45534413-067d8900-b7c9-11e8-87cf-4b9cc5ae0322.png)

 - ArchWSL version [e.g. 18081100] (version of zip)
18081100

 - Launcher version [e.g. 18080900] (Type `Arch.exe version` at a Command Prompt)
wsldl, version 18080900

**Additional context**

**Comment by yuk7** [comment]
Does that mean that the exe process does not appear?
I think that is the same for other WSL distributions.
I think it is not an issue...

**Comment by ShayBox** [comment]
Hmm, you're right, same thing in the ubuntu wsl, but I know at one point windows processes did show up in htop, and on archwsl

**Comment by ShinobiWPS** [comment]
> Hmm, you're right, same thing in the ubuntu wsl, but I know at one point windows processes did show up in htop, and on archwsl

Never seen that ever, and do not expect to see it.
Why would you want to see them?

**Comment by ShayBox** [comment]
I like using htop as my task manager, I used to do that

**Comment by ShinobiWPS** [comment]
> Hmm, you're right, same thing in the ubuntu wsl, but I know at one point windows processes did show up in htop, and on archwsl

Maybe they realized it wasn;t necessary and/or a good idea :D

**Comment by ShayBox** [comment]
Yeah, I suppose this isn't an issue with ArchWSL then, likely the windows kernel changed it
