### ISSUE TITLE
`config --default-user` does not change the user

### ISSUE THREAD

**Issue by abelsromero** [yuk7/ArchWSL#54]
**Describe the issue**
After creating a new user and setting it successfully with `config --default-user`, the shell still opens as `root`.

**To Reproduce**
1. Create user with `useradd` called "USER"
2. Setup use in sudoers file
3. Invoke Arch.exe with `Arch config --default-user` USER
4. Open new shell using only `Arch`.

**Expected behavior**
New shells should open with user USER.

**Enviroment:**

    Microsoft Windows [Versión 10.0.16299.431]
    ArchWSL 18081100
    wsldl, version 18080900

**Additional context**
Using `get --default-user` returns the correct uid, and I even debugged the code and everything seems fine, there was no error when calling `WslConfigureDistribution`. Could be a WSL or rootfs thing?

**Comment by yuk7** [comment]
That is a WSL problem.
Probably,Rebooting the computer will fix it.
Please see #7

**Comment by abelsromero** [comment]
Your totally right, rebooting works.

Seeing this is a typical issue, I'd suggest adding this to known issues or a FAQ in readme?

**Comment by yuk7** [comment]
In the past I wrote it in README, but moved to wiki...
Is it hard to find?

**Comment by abelsromero** [comment]
> Is it hard to find?

Not at all, adding it to the wiki is perfectly fine!
