### ISSUE TITLE
Fail to run the step 2 (install) from Windows 10 1809 (RS5) almost final version.

### ISSUE THREAD

**Issue by H0R1Z0N** [yuk7/ArchWSL#57]
So, i upgraded my 1703 build of Windows 10 to a clean install of 1809's lastest dev build iso, it's pretty good and stable on the other system i tested before.

Since i am an ex arch linux user (and if i return to linux, i use manjaro gnome 3 and remove the custom design to a classic vanilla gnome 3) and wanted to use the Arch WSL package. It simply won't do the normal install process.

Here's the error : 
`Installing...
ERROR:Installation Failed!
HRESULT:0x8007019e
Press any key to continue...

-I use the lastest release preview build
-Windows 10 Pro build 10.0.17758.1 (RS5)

Thank you for your great work, i am looking forward a working build of this WSL Arch build.

**Comment by yuk7** [comment]
Error 0x8007019e generally occurs when the WSL function is not enabled.
Make sure that the WSL function is enabled.

**Comment by H0R1Z0N** [comment]
I might had missed the basic step since i only enabled a tick box, if it work, gonna close it.
