### ISSUE TITLE
ERROR: LoadLibraryEx() failed to load wslapi.dll

### ISSUE THREAD

**Issue by onodera-punpun** [yuk7/ArchWSL#6]
See title, I get this when I run the .exe.

**Comment by yuk7** [comment]
@onodera-punpun 
Thank you for your reporting.

This software is supporting Windows 10 build 16251 64bit or later only.
Please check Windows version and make sure WSL is enabled.

**Comment by onodera-punpun** [comment]
Ah yes, I didn't have WSL enabled. Maybe you could add this as a step to the README.

**Comment by yuk7** [comment]
Ok,I'll add "Requirement" for README.

Thanks.

**Comment by marler8997** [comment]
I'm seeing this LoadLibrary error when I build the Launcher from source:
```
ERROR: LoadLibraryEx() failed to load wslapi.dll
```

 I'm on `Windows 10 Enterprise, version 1809" OS Build "17763.292".

I built from a visual studio 2017 command prompt with: 
```
cl /nologo /O2 /W4 /WX /Ob2 /Oi /Oy /Gs- /GF /Gy /Tc main.c /Fe:Launcher.exe Advapi32.lib Shell32.lib
main.c
```

If I use the launcher from here: https://github.com/yuk7/wsldl/releases/tag/19022600

I get don't get the dll LoadLibrary error, but I do get this error:

```
The specified network name is no longer available.
```

**Comment by marler8997** [comment]
By the way wsl is also enabled and I can launch other distros.

**Comment by marler8997** [comment]
Update.  I built in an x86 visual studio 2017 command prompt and load library error was resolved.  I'm going to see if there's a way to load `wslapi.dll` from a 32-bit program.

**Comment by yuk7** [comment]
Oh...really?
In 32bit mode, wslapi.dll should normally not exist ...🤔

**Comment by marler8997** [comment]
Oh I meant to say I was originally building in a x86 command prompt, but after switching to x64 it resolved the load library issue.

**Comment by yuk7** [comment]
I understood.
Thanks.
