### ISSUE TITLE
Cursor Slowly Blinking or Not Appearing Windows 1809

### ISSUE THREAD

**Issue by ZacharyATanenbaum** [yuk7/ArchWSL#60]
**Describe the issue**
The cursor blinks slower post update than it did pre-update. In some programs (vim) it simply does not appear at times. If you leave the cursor sitting in one spot in vim it will appear and stay appeared for a significant amount of time.

**To Reproduce**
Download gvim ``` sudo pacman -S gvim``` then open a new file ```vim test```. Go into insert mode and type a sentence ("i" then start typing). Exit insert mode (hit "esc") and move the cursor around with the arrow keys. It will disappear unless you hold down an arrow key. It will appear quickly but disappear if you stop moving when it is not on screen.

**Expected behavior**
The cursor should not disappear/blink at its original speed.

**Screenshots**
![image](https://user-images.githubusercontent.com/9688904/46591572-97264c80-ca89-11e8-9fca-c930de32c171.png)

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.18252.1000]
 - ArchWSL version: (I don't know for sure, but I'd imagine 18081100 as it matches the launcher)
 - Launcher version: wsldl, version 18080900

**Additional context**
I tried a few methods to have the cursor always appear. None have fixed the problem.

**Comment by yuk7** [comment]
Probably,That issue due to WSL's.
We can see the same problem in other distros.

**Comment by ZacharyATanenbaum** [comment]
Hey yuk!

Thanks for the great program! I actually am not seeing the same problem in the Ubuntu WSL install from the store. I would not be surprised if it's a problem with the new build. Should I upgrade to a faster track? It's a hugely deal breaking bug.

**Comment by yuk7** [comment]
Ok,I got it.
I'll check the problem later.

**Comment by ZacharyATanenbaum** [comment]
Nope, you're right. Now that I'm using Ubuntu some more the cursor seems to have slowed down. This is very weird. I guess it is a problem with the WSL layer. What fun...

On another note... Do you have any suggestions on tutorials so I can learn more about your implementation of Arch on WSL? I'd love to help contribute once I get some more free time.

**Comment by yuk7** [comment]
Ok.

I always welcome your suggestions and contributions :)
Thank you!
