### ISSUE TITLE
Is there a way to set terminal font?

### ISSUE THREAD

**Issue by roachsinai** [yuk7/ArchWSL#62]
**Describe the issue**
Use `Vim` open a file and the font will change.

**Expected behavior**
Keep the font not changed.

**Screenshots**
Just open a termianl.

![image](https://user-images.githubusercontent.com/9500049/47224010-18b49d80-d3ed-11e8-9404-1de1b87f5535.png)

Use `Vim` open a file and terminal change the font from `nerd mononoki` to `新宋体` itself.

![image](https://user-images.githubusercontent.com/9500049/47224151-67face00-d3ed-11e8-9d7d-a29b468847ad.png)

**Enviroment:**
 - Windows build number: `10.0.17763.104`
 - ArchWSL version: `18100800`
 - Launcher version: `wsldl, version 18100300`

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/47224662-a2b13600-d3ee-11e8-922f-e400190902aa.png)

I always start a terminal from **TaskBar**, and set the font property (screenshot above), but not work, font still change when use `Vim` open files.

**Comment by yuk7** [comment]
In my environment this problem did not reproduce...
win build: 17763.55
wsldl: 18102701

**Comment by Drachenkaetzchen** [comment]
I'm wondering: What happens if you use cat to put the document you edited in vim on the console? Does the font change as well?

You could also try to use the classic console or another terminal like terminus to see if the problem is the same. I'd suspect it has to do with windows choosing a font having the proper glyphs available.

**Comment by roachsinai** [comment]
Hi @Drachenkaetzchen What do you mean "use cat to put the document you edited in vim"? Would you please show me the command to do it?

Now, I'm using `WSLtty`.

**Comment by Drachenkaetzchen** [comment]
Instead of `vim yourfile.txt` to `cat yourfile.txt`
