### ISSUE TITLE
libfakeroot: connect: Resource temporarily unavailable

### ISSUE THREAD

**Issue by patrick330602** [yuk7/ArchWSL#63]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
`libfakeroot` throws `libfakeroot: connect: Resource temporarily unavailable` error when building package using `makepkg -si`

**To Reproduce**
1. install `base`, `base-devel` and `git`
2. install `fakeroot-tcp-1.23-1-x86_64.pkg.tar.xz` from https://github.com/yuk7/arch-prebuilt
3. run following code:
```
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```

**Expected behavior**
`yay` package should build properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/15316889/48621090-636e0900-e9dd-11e8-9609-d395a672537d.png)

**Enviroment:**
 - Windows build number: 10.0.18282.1000
 - ArchWSL version: 18102700
 - Launcher version: 18102701

**Additional context**
I don't know why but ArchWSL version 18102700 comes with fakeroot-tcp 1.22 but not 1.23

**Comment by patrick330602** [comment]
I do not know why but it seems to be fixed today.... so I will close this

**Comment by GXGOW** [comment]
Having this issue too now. Hopefully it'll be magically fixed too 🤔

**Comment by Coalpha** [comment]
I've got this issue as well. Maybe it has something to do with the Windows Firewall? It asked me to allow faked. Maybe reopen it?

**Comment by akitaonrails** [comment]
I'm having the same issue. I already checked that faked is allowed in the Windows Firewall settings (both incoming and outgoing). I tried to reinstall the fakeroot-tcp from the Wiki page. Still nothing.

**Comment by patrick330602** [comment]
Seems that I a lot of people experience same things I met... I will reopen this

**Comment by akitaonrails** [comment]
I've tried the fakeroot package in the Wiki, didn't work. I tried compiling fakeroot-tcp from the debiam source. Also didn't work. Not sure if this is a bug from the latest WSL permissions feature or something I still couldn't find, but even disabling the Windows Defender Firewall entirely didn't work.

**Comment by yuk7** [comment]
I tried it the same way, but it worked fine...
The Windows Firewall dialog for faked process is displayed.

on Windows 10 1809.

**Comment by altercation** [comment]
Happy to troubleshoot here as well. Same problem. What would be useful in terms of debug / repro?

**Comment by zqrren** [comment]
```
sudo pacman -Sy base-devel
fakeroot is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n] n
```
For me, selecting "no" on the second line is fine.

**Comment by ZhiZe-ZG** [comment]
try this:

```shell
sudo pacman -S fakeroot
```

when ask:

```
:: fakeroot is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n] 
```

choose Y

when ask:

```
:: fakeroot-1.34-1 and fakeroot-tcp-1.25.3-2 are in conflict. Remove fakeroot-tcp? [y/N] 
```

choose y.

it seem like the yay used a old version of fakeroot?
