### ISSUE TITLE
Upgrade process?

### ISSUE THREAD

**Issue by Ncage1974** [yuk7/ArchWSL#64]
Hi everyone just a very general question. So it looks like you are using kernel 4.4.0 that is created by Microsoft. So when Microsoft upgrades the kernel will i have to blow out what i have and  re-download the latest version or will it be upgraded by pacman? The ubuntu version of WSL was a pain because when i went from 16.04 to 18.04 i had redo everything. I'm hoping i won't ever have to re-download arch and have to setup everything again.

thanks....

**Comment by hdk5** [comment]
WSL works like chroot, and Arch is rolling release. Just keep your apps and linked libraries updated, and everything should be fine.

**Comment by yuk7** [comment]
When the WSL kernel is updated it will be updated with Windows update.
Since it is done automatically, no operation with WSL is necessary.

**Comment by Hoverbear** [comment]
Hi! Can this be closed then? Seems it's a solved issue.
