### ISSUE TITLE
Can't start services 

### ISSUE THREAD

**Issue by elswerky** [yuk7/ArchWSL#67]
why i can't start services in arch on wsl ?? 
for example if i run 
sudo sercie status ssh            in arch on wsl 
the output is service command not found 

but if i run the same command on ubuntu18.04 on wsl it works and gives me status of ssh

i mentioned ssh here as an example for any service  
can you help me please 
i know this may be not the place to report such problem ,hope you can help

these screenshots ,,one from arch on gui desktop 
and the other from ubuntu bash

![arch](https://user-images.githubusercontent.com/26687459/50555193-76107900-0cd1-11e9-9ce2-23ea7f1bfde5.PNG)

![ubuntu](https://user-images.githubusercontent.com/26687459/50555196-7e68b400-0cd1-11e9-9dd8-30c82c40d3f6.PNG)

**Comment by yuk7** [comment]
Arch uses systemd for service, but WSL does not support systemd...
There is no service command in the arch.

**Comment by elswerky** [comment]
> Arch uses systemd for service, but WSL does not support systemd...
> There is no service command in the arch.

so there is no hope in running such apps and tools on arch ??

**Comment by yuk7** [comment]
You can execute the command to start the service manually.
Or you can install a service manager such as OpenRC which is not officially supported by Arch.

**Comment by elswerky** [comment]
also i see another Arch for wsl  here on github 
https://github.com/bilguun0203/WSL-ArchLinux

also the one i posted its link is avilable on choclatey on windows  as it appears in this screenshot 

![choclatey gui](https://user-images.githubusercontent.com/26687459/50555321-29c63880-0cd3-11e9-8c11-1027496a4fc0.PNG)

**Comment by elswerky** [comment]
> You can execute the command to start the service manually.
> Or you can install a service manager such as OpenRC which is not officially supported by Arch.

how to execute the command to start the service manually 
say ssh ,, how to do this for it ? 


also another thing,, i installed xfce4 desktop on arch on wsl as in previous screenshots,,, but i can't type in arabic even if i choose arabic layout from xfce settings only ican type in english 

so this is a problem in wsl or the x11 server ( x410 ) or it needs more configuration in arch on wsl ?? 

arabic font appears in file managers and browsers well ,, but can't type  in arabic ,,,just english

**Comment by yuk7** [comment]
I think that services can not be used as well because it is WSL specification.
It seems that rootfs was forked from ArchWSL.

**Comment by elswerky** [comment]
last question (hopefully 😂
1-why don't you publish it on windows store ??? for better integration with windows as other distro 

( here i can get file and store it for offfline installation of arch on wsl ,,,unlike gettting it from store if i unistalled it i have to re--install it ) 

2- the other linux bash downloaded from ms store can be reset from windows settings as if you have fresh install of it without need to re-download it 
so my question is  how to do the same for arch on wsl ( i mean integration with windows like others ) 

and also this means that windows may keep downloaded files of other distro in  somewhere in windows files,,,,do you know where is this path on windows ???  because reset  returns the bash to fresh install without need to re-downlaod from store ,,, i ask for path of already downlaoded files which windows use to reset  )

**Comment by yuk7** [comment]
1,2  -
This project was started before the official store version launcher code was released.
To be published on the Windows store, it need to review by Microsoft.
Store applications do not have flexibility, multiple installations etc can not be done.

3 -
I dont know...
Please check the X server's font and locale

**Comment by elswerky** [comment]
> To be published on the Windows store, it need

thank you for answering me and for providing arch on wsl

**Comment by elswerky** [comment]
@yuk7 
sorry last thing and it is not related to arch specefically but in general 
i created a shorcut for opening gui desktop and like i open any app by simple click without opening the arch terminal 

the problem is that when i open terminal in arch gui xfce desktop it doesn't open at ~/ directory 
i tried to change location from shorcut  to home directory of user but  i found it opens at **/** directory  
now i ask if you can help me if there is a way to open it at home dirctory 

as in this screenshot ,the default location was \C:\Windows\system32
i changed it to C:\tmp   ,, i tried to set it to path of user directory /home of installed arch wsl but it always opens at **/**  not **/homw/username**   don't know why may be permession problem ,, 
do you know any idea that can help open home directory in terminal by default 

- i know that if i opened Arch.exe that comes with your files it open /home directory of user ,,but i talk about the shorcut ,,,,,,,,,,the shorcut way i get it from token2shell site 
![321](https://user-images.githubusercontent.com/26687459/50557655-f219b980-0cef-11e9-81de-fdd4e5a7f946.PNG)

**Comment by yuk7** [comment]
Related #20
