### ISSUE TITLE
Can't type in arabic in Gui apps like gedit 

### ISSUE THREAD

**Issue by elswerky** [yuk7/ArchWSL#69]
why i can't type in arabic in gui apps in arch on wsl ?? 
i use x410 as x11 server ,,, and sent them an email that i can't type in arabic 
they replied me by steps to enable typing in arabic which i already did before on arch on wsl ,,before sending  them the email,,, 
so i decided  to do the same steps on **ubuntu18.04** on wsl ,,,and surprisingly it workded 

so now i can type in arabic in _ubuntu18.04_ but when i use the same steps in arch on wsl ,,, i only can type in english 

so can you help me why i can't do this in arch ??
**Note that** every issue i report here ,, i confirm that this issue isn't present in ubuntu18.04 on wsl 
it appears to me that ubutntu18.04 is the best wsl bash uptill now ,,, although i prefer using Arch

i am running xfce desktop on both arch and ubuntu 18.04 on wsl ,,, and choose to enable both arabic and english from settings of xfce ,

_this_ _screenshot_ _is_ _from_ _ubuntu_ _18.04_ _on_ _wsl_
![arabic](https://user-images.githubusercontent.com/26687459/50681523-7fbd1800-1014-11e9-9116-10c0783cc6bd.PNG)

![2019-01-04_11-50-43](https://user-images.githubusercontent.com/26687459/50682285-083cb800-1017-11e9-9f31-b1783241f67d.jpg)

**Comment by elswerky** [comment]
@yuk7  plz see this ,,, it works fine on ubuntu 18.04 ,, i don't know why it doesn't work with me on arch

**Comment by yuk7** [comment]
I set Arabic Input with setxkbmap and tested gedit on LXDE.
But it was work...

I do not know about setting in DE so test later.

**Comment by yuk7** [comment]
ok,I'll test it.

**Comment by yuk7** [comment]
Please install `xfce4-xkb-plugin` and `xorg-xkbcomp`.
I confirmed that installing them will start working arabic input.

**Comment by elswerky** [comment]
> Please install `xfce4-xkb-plugin` and `xorg-xkbcomp`.
> I confirmed that installing them will start working keyboard switcher/Arabic input.

thank you 
yes i went to arch page of keyboard typing 
https://wiki.archlinux.org/index.php/X_keyboard_extension
and found that it talks about xorg 
so i installed xorg(all the group) because at this time i did't know which  pkg will enable it ,,,and found it working ,, and waited your reply to see if there is another way 

the xfce4-xkb-plugin isn't needed for it to change layout ,,it just provide a plugin in xfce panel to to show current keyboard layout and for changing layout ,,,,

so xorg-xkbcomp is enough to enable switching layout 

**_Thank__you__**   _now_it__works__


![xorg](https://user-images.githubusercontent.com/26687459/50703952-6a6cdb80-105e-11e9-92d4-66ea6722932b.jpg)

i think you shoud add **xorg-xkbcomp.** pkg to coming archWSL release
