### ISSUE TITLE
provide arch wsl in appx format 

### ISSUE THREAD

**Issue by elswerky** [yuk7/ArchWSL#72]
Can you please provide Arch wsl in **_appx_** format to install it by just one click on it and integrate it with Windows  like other wsl distro ?? 

the other arch version is present in chocolatey in appx format ,,,,,,this makes it easy to install and integrate it with windows apps in settings so that you can reset it or do repair it easily 

just see the requirements pls to create it in appx fomat and register it

**Comment by yuk7** [comment]
Ok.
I realized that many people want the AppX version of ArchWSL.

I'm preparing for that, but the update frequency may be low.

**Comment by yuk7** [comment]
Resolved in 55d8f7f !
I uploaded AppX.
https://github.com/yuk7/ArchWSL/releases/tag/19022400

**Comment by elswerky** [comment]
> Resolved in [55d8f7f](https://github.com/yuk7/ArchWSL/commit/55d8f7fb5d4fbf1a4c88eccf94174291ffdca082) !
> I uploaded AppX.
> https://github.com/yuk7/ArchWSL/releases/tag/19022400

 why you prefer the zip over appx ??
only because of low updates or what ??

also will be available in  ms store ??

**Comment by yuk7** [comment]
> why you prefer the zip over appx ??
only because of low updates or what ??

The zip build of ArchWSL is automated by CI, but its AppX build needs to be done manually.
Also, since my main PC does not installed Microsoft's SDK, I need to use another machine.

> also will be available in ms store ??

To distribute this I need the "company" account of the MS store.
It costs money, and it is unknown whether it will pass through judging from Microsoft...

**Comment by elswerky** [comment]
> > why you prefer the zip over appx ??
> > only because of low updates or what ??
> 
> The zip build of ArchWSL is automated by CI, but its AppX build needs to be done manually.
> Also, since my main PC does not installed Microsoft's SDK, I need to use another machine.
> 
> > also will be available in ms store ??
> 
> To distribute this I need the "company" account of the MS store.
> It costs money, and it is unknown whether it will pass through judging from Microsoft...

thanks for clarification

**Comment by yuk7** [comment]
Update: Added support for automatic build of appx.

**Comment by elswerky** [comment]
> Update: Added support for automatic build of appx.
thank you 
i am currently still running the zip version which i installed about 2 months ago ,, i will use appx version next time i re-install arch ,,just don't want to remove the zip version and re-install everything from the beginning
