### ISSUE TITLE
Failed to connect to the D-BUS session bus

### ISSUE THREAD

**Issue by elswerky** [yuk7/ArchWSL#73]
how to fix this error on arch wsl ?? 
it appears that ubutnu18.04 doesn't has this error 

sometimes i face crash in arch wsl especially when i use text editor like gedit (on closing it ,,sometimes not always ) ,,, i use x410 server ,, i reported this issue to x410 developers ,,, they helped me with a commad to prevent this crash ,,,, when i used it in ubuntu it worked fine ,,,

but on arch it doesn't work at all and i get failed to connect to dbus 

plz help me fix this 

https://token2shell.com/howto/x410/customizing-xfce-desktop-for-ubuntu-wsl/
here ,,they provided a fix for crash ,,but it doesn't work on arch_wsl with me ,,,but works with ubuntu1804

**Comment by Alia5** [comment]
~/.bashrc
```
export DISPLAY=:0.0
export LIBGL_ALWAYS_INDIRECT=1

export $(dbus-launch) # <----- that's the key here!
```
