### ISSUE TITLE
Installation Failed!

### ISSUE THREAD

**Issue by trashcluster** [yuk7/ArchWSL#74]
Installing...
ERROR:Installation Failed!
HRESULT:0x80070005
Press any key to continue...
Any idea what's the error?

**Comment by trashcluster** [comment]
put arch.exe and the tar.gz file on the desktop, tried admin and non admin and always the same error

**Comment by yuk7** [comment]
Please give me these information.

Screenshots If applicable, add screenshots to help explain your problem.

Enviroment:

Windows build number: [e.g. 10.0.17134.228] (Type ver at a Command Prompt)
ArchWSL version [e.g. 18081100] (version of zip)
Launcher version [e.g. 18080900] (Type Arch.exe version at a Command Prompt)

**Comment by trashcluster** [comment]
Windows 10 1803, latest release of arch.exe downloaded yesterday. (19010200)

**Comment by yuk7** [comment]
ok.
Where are you going to install it?

**Comment by trashcluster** [comment]
ohhhh i see. You're right, it's working right now :) Thanks
