### ISSUE TITLE
dbus is very slow/does not work

### ISSUE THREAD

**Issue by AngellusMortis** [yuk7/ArchWSL#75]
**Describe the issue**
`dbus` is very slow to start and any applications that use `dbus` (VS Code) seem to not work at all.

**To Reproduce**
1. Install an X server (I am using VcXsrv) on Windows 10.
2. Install `visual-studio-code-bin` from AUR (any app that uses X11/`dbus` should work as well?)
3. Open Arch WSL and run the following:
    ```shell
       $ sudo mkdir /run/dbus -p
       $ sudo dbus-daemon --system  # this takes ~90 seconds to start on my machine
       $ DISPLAY=:0.0 code # It is normal for this command to exit right away, 
       # check Task Manager/do `ps` to see process. It exits after ~5 minutes 
       # on my machine never launching VS Code properly. It *should* spawn 
       # ~5 `code` processes and start a window with VS Code.
   ```

**Expected behavior**
Starting `dbus` should be much faster. In the official Ubuntu WSL instance, it takes almost no time for it to start. Likewise, starting applications that use `dbus` should start and work. VS Code works fine in Ubuntu WSL and takes ~5 seconds to start on my machine. See https://github.com/Microsoft/WSL/issues/2293 for details about using VS Code in Ubuntu WSL. 

**Enviroment:**
 - Windows build number: 10.0.17763.253
 - ArchWSL version: 19010200
 - Launcher version: 18122700

**Additional context**
Not sure what you need to help track down the issue, let me know if you need anything else.

**Comment by yuk7** [comment]
I did the same, but I could not confirm the problem. . .

**Comment by AngellusMortis** [comment]
Are you able to actually VS Code to launch?

I still get the same issues with dbus when I try to run it on the system level (as above with `sudo dbus-daemon --system`), but I did see https://github.com/yuk7/ArchWSL/issues/73 which allows me to launch `dbus` in the user space and it run instantly, but VS Code still has the same problem where it never launches.

**Comment by ssolidus** [comment]
I reproduced this as well, with these commands:
```
   $ sudo mkdir /run/dbus -p
   $ sudo dbus-daemon --system
```

**Comment by hemanta212** [comment]
I confirm. I have release 19.3.19.1. Tried with administrator command prompt. 
           
           $ sudo mkdir /run/dbus -p
           $ sudo dbud-daemon --system

Took 1 minute after LXCORE.SYS failed.

**Comment by ssolidus** [comment]
Any update on this @yuk7? There are multiple repros in this thread, and currently this is preventing me from switching to ArchWSL.

**Comment by javashin** [comment]
Installed All from today and got same problem

**Comment by koumaza** [comment]
Replacing `libdbus` with `dbus-x11` may solve this problem.

**Comment by yuk7** [comment]
I think this issue was fixed in newest in systemd-libs.

**Comment by anandbhaskaran** [comment]
I got the same issue again

**Comment by koumaza** [comment]
We can try to use `dbus-x11`_aur_.
