### ISSUE TITLE
fakeroot-tcp does nothing

### ISSUE THREAD

**Issue by sHAsHiLx** [yuk7/ArchWSL#77]
[root@shashilx-pc ~]# localectl list-locales
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
[root@shashilx-pc ~]# pacman -Q|grep fake
fakeroot-tcp 1.23-1

Even tried install it from Known issues page. Nothing changes. Yes, I've changed locale from [this link](https://github.com/yuk7/ArchWSL/issues/76) but want to use native way.

**Comment by yuk7** [comment]
locale has nothing to do with fakeroot.
