### ISSUE TITLE
cant run pacman -Syu

### ISSUE THREAD

**Issue by MrMuttons** [yuk7/ArchWSL#78]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
Running pacman -Syu as root produces the following on a clean install.
`:: Proceed with installation? [Y/n] y
(110/110) checking keys in keyring                                       [########################################] 100%(110/110) checking package integrity                                     [########################################] 100%error: libxml2: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /var/cache/pacman/pkg/libxml2-2.9.9-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: vim-runtime: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /var/cache/pacman/pkg/vim-runtime-8.1.0877-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: vim: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /var/cache/pacman/pkg/vim-8.1.0877-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
[root@MoeMachine ~]#`
**To Reproduce**
fresh install
init keyring
run pacman -Syu as root
**Expected behavior**
Properly update the install 
**Screenshots**
![image](https://user-images.githubusercontent.com/34928493/53039595-20d92400-3445-11e9-8ffb-500bf9070b60.png)

**Enviroment:**
 - Windows build number: [e.g. 10.0.17134.228] (Type `ver` at a Command Prompt)
 - ArchWSL version [e.g. 18081100] (version of zip)
 - Launcher version [e.g. 18080900] (Type `Arch.exe version` at a Command Prompt)
Microsoft Windows [Version 10.0.17763.316]
18060300
running "Arch.exe version" gives invalid argument

**Additional context**

**Comment by yuk7** [comment]
It seems necessary to update the key ring.
Please execute these:
```
sudo pacman -S archlinux-keyring
sudo pacman -Syu
```

**Comment by MrMuttons** [comment]
> It seems necessary to update the key ring.
> Please execute these:
> 
> ```
> sudo pacman -S archlinux-keyring
> sudo pacman -Syu
> ```

this worked, thanks!
Should i also update the files from newest zip?

**Comment by yuk7** [comment]
Updates are not necessarily required.
There are not so important changes in the new version.

If you want to update, please overwrite existing ones with the new version of Arch.exe and rootfs.tar.gz.

**Comment by MrMuttons** [comment]
alright. closed. thanks
