### ISSUE TITLE
Error: 0x80070040 on reinstalation

### ISSUE THREAD

**Issue by Lite5h4dow** [yuk7/ArchWSL#79]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
while running Arch.exe again to install again it posts this error

**To Reproduce**
Install Arch linux via WSL then delete Arch Linux WSL files (i did his by accident like a tard.) then attempt to reinstall ArchWSL by extracting the files and running like before.

**Expected behavior**
Install Arch WSL

**Enviroment:**
 - Microsoft Windows [Version 10.0.17134.590]
 - ArchWSL version 19.3.7.0
 - arch (GNU coreutils) 8.30

**Additional context**
I know i was an idiot and deleted the files. please dont flog me.

**Comment by yuk7** [comment]
Have you completely deleted your registration from the system?

1. Please unregister from the system with the following command:
```
wslconfig /u Arch
```

2. re-install

**Comment by Lite5h4dow** [comment]
yup that worked, however the app install dosen't work.

**Comment by Lite5h4dow** [comment]
the APPX installer gives the following error ```Either a new certificate must be installed for this app package or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain was processed but terminated in a root certificate that isn't trusted (0x800B0109)```

**Comment by Lite5h4dow** [comment]
Yup this worked perfectly, thankyou!
