### ISSUE TITLE
Cannot start Arch as any user except root

### ISSUE THREAD

**Issue by godefroi** [yuk7/ArchWSL#8]
I have installed Arch, started it, and created a user with `useradd -u 1000 -m myuser`. I cannot, however, start Arch as this user:
```
myuser@computername ~\wsl_distros\Arch
$ ./arch get --default-uid
1000
myuser@computername ~\wsl_distros\Arch
$ ./arch
[root@computername Arch]# id myuser
uid=1000(myuser) gid=1000(myuser) groups=1000(myuser),990(adm),998(wheel)
[root@computername Arch]# 
```

I recreated the user with uid 1000 because I noticed that the command `./arch config --default-user myuser` set the DefaultUid registry entry to 1000, even though that wasn't the uid of the user I specified. That didn't make any difference, though.

**Comment by yuk7** [comment]
@godefroi 
Please see #7 
Try this:
1. Please close the command prompt, wait for a while, then re-open it again.(I solved the problem in this way)
2. Reboot the computer.
Please give me additional information if not resolved.

Thank you.

**Comment by godefroi** [comment]
Sorry; I looked for open issues, but not closed ones. Closing and re-opening the command prompt from which I started Arch solved the issue. Maybe WSL is caching the registry entry? We may want to open an issue with WSL...
