### ISSUE TITLE
Can't install appx version 

### ISSUE THREAD

**Issue by elswerky** [yuk7/ArchWSL#81]
i tried to install latest appx package version  ArchWSL-AppX_19.3.19.1_x64.appx
but i get this error 
```Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted ```

even i downlaoded cer file of this version and installed it in trusted root group but still get this error 

i am using windows insider version 18845.1001
this is  the first try of an appx package on arch_wsl on my machine

**Comment by elswerky** [comment]
it worked now after i choose local machine instead of current user in cer installation

**Comment by elswerky** [comment]
Yes, choosing local machine instead of current user fixed it

**Comment by ShayBox** [comment]
I installed it both ways, still doesn't work
![image](https://user-images.githubusercontent.com/9505196/54789192-e18e2680-4bee-11e9-8258-78d60244fb46.png)

**Comment by yuk7** [comment]
I'll write about it to wiki.
I'm sorry for my poor explanation...

**Comment by yuk7** [comment]
I wrote to [wiki/Install-Certificate](https://github.com/yuk7/ArchWSL/wiki/Install-Certificate) and added link to README.
