### ISSUE TITLE
窗口标题如何设置显示当前路径或者和README.md截图一样?

### ISSUE THREAD

**Issue by roachsinai** [yuk7/ArchWSL#82]
![image](https://user-images.githubusercontent.com/9500049/54874982-ae3ada00-4e30-11e9-99b4-1a994794009a.png)

我当前窗口标题如上图所示。

**Comment by yuk7** [comment]
It looks like you are using wslbridge.
I do not know about it.

Which shell do you use?
While bash dynamically rewrites the title bar, other shells (eg. zsh) may require additional configuration.

**Comment by roachsinai** [comment]
I'm using zsh.

**Comment by yuk7** [comment]
I am not a zsh user, so I do not know in detail, but I think that it is better to refer to this:
https://github.com/MrElendig/dotfiles-alice/blob/master/.zshrc#L115

**Comment by roachsinai** [comment]
Ok, thanks will check it and feedback later, as not using WIn10 right now.

**Comment by roachsinai** [comment]
Yes,

```
precmd () { 
      vcs_info
      print -Pn "\e]83;title \"$1\"\a" 
      print -Pn "\e]0;$TERM - (%L) [%n@%M]%# [%~]\a" 
    }
```

worked! thanks again!
