### ISSUE TITLE
Auto login as another user

### ISSUE THREAD

**Issue by Merith-TK** [yuk7/ArchWSL#84]
**Please fill out the below information:**
**Describe the issue**
Basicallu a Question on how to make it load a user other than root automatically?

**To Reproduce**
Install ArchWSL and run 

**Enviroment:**
 - Windows build number: `17763.379`
 - ArchWSL version `19.3.19.1`
 - ArchWSL Installer `zip`
 - Launcher version `wsldl, version 19031901`

**Additional context**
I literally just want to automatically open the user `merith` instead of `root`

**Comment by yuk7** [comment]
Please use `Arch.exe config --default-user [username]` command.
Please see the [wiki](https://github.com/yuk7/ArchWSL/wiki/How-to-Use(for-Installed-Instance)).

**Comment by Merith-TK** [comment]
that didnt work. 
```C:\opt\Arch>Arch.exe config --default-user merith

C:\opt\Arch>Arch.exe
[root@DESKTOP-IVHATFF ~]#
```

**Comment by Merith-TK** [comment]
even changed the default uid
 no luck

**Comment by yuk7** [comment]
Please reboot the computer?

**Comment by Merith-TK** [comment]
will try that when i get back to the PC, (at school right now)

**Comment by Merith-TK** [comment]
rebooting worked, new issue that i will make with another issue
