### ISSUE TITLE
Installation Failed: HRESULT:0x80080005

### ISSUE THREAD

**Issue by Dhs92** [yuk7/ArchWSL#87]
```
Installing...
ERROR:Installation Failed!
HRESULT:0x80080005
Press any key to continue...
```

**To Reproduce**
Run Arch.exe from the zip or install using the appx

**Expected behavior**
ArchWSL should install

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.17763.379]   
 - ArchWSL version 19.3.19.1
 - ArchWSL Installer type zip/appx
 - Launcher version wsldl, version 19031901

**Comment by Dhs92** [comment]
Issue corrected itself after a reboot

**Comment by yuk7** [comment]
Ok,close.

**Comment by Alexander-Huang** [comment]
After switching from wsl2 to wsl1 ,I suffered from the same issue.But reboot did help.
