### ISSUE TITLE
Cannot run Visual Studio Code

### ISSUE THREAD

**Issue by maghsk** [yuk7/ArchWSL#88]
I installed an desktop environment (XFCE4) and then I successfully started it and got perfect output in VCXSRV. However I failed to launch VSCode.

I tried it on "Debian" wsl-distro provided by Microsoft Store, and it DO launched, so it cannot be VSCode's problem.

What can I do?

**Comment by varemenos** [comment]
I'd recommend to use VSCode from Windows with the new VSCode Remote WSL extension
