### ISSUE TITLE
Error: 0x80070003

### ISSUE THREAD

**Issue by btmichalowic** [yuk7/ArchWSL#9]
I recently downloaded and installed your ArchWSL (where things worked successfully), uninstalled it using the Ubuntu bash terminal, and then tried installing it again, and when trying to run the application I end up receiving the error mentioned in the title; what can I do to fix this, as I understand this is a problem on my end?

**Comment by yuk7** [comment]
@btmichalowic 
Thank you for reporting!
I don't know about this issue, But could you try this:
1. run `wslconfig /u Arch` command for full uninstall instance.
2. WSL is can install C: drive only. Please check path.
3. (opt: Disable and re-enable WSL feature)

Please give me additional information if not resolved.
Thank you.

**Comment by btmichalowic** [comment]
Everything's been resolved! @yuk7 ; thank you so much!

**Comment by TheDoop** [comment]
PS C:\Windows\system32> wslconfig /u Arch
There is no distribution with the supplied name.

**Comment by yuk7** [comment]
@TheDoop 
I think the problem is not the same as this.
Please create a new issue.
