### ISSUE TITLE
Is custom fakeroot still needed with WSL2

### ISSUE THREAD

**Issue by arlllk** [yuk7/ArchWSL#92]
The need for a custom fakeroot in WSL, is also present when we use Arch in WSL2?

**Comment by yuk7** [comment]
Please download from here:
https://github.com/yuk7/arch-prebuilt/releases/tag/18082100

**Comment by yuk7** [comment]
I don't think so.
I think I do not need it.

**Comment by arlllk** [comment]
I just replace it with the default fakeroot and it's functioning normal
