### ISSUE TITLE
HRESULT:0x80370102

### ISSUE THREAD

**Issue by lengthmin** [yuk7/ArchWSL#93]
**IMPORTANT**
Please read [README](https://github.com/yuk7/ArchWSL/blob/master/README.md) and [Known issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) before creating the issue.

**Please fill out the below information:**
**Describe the issue**
Windows build 18932(Insider) install failed.
![image](https://user-images.githubusercontent.com/13938334/61052105-46c78b00-a41d-11e9-9d1b-a2b45d6cd409.png)

**To Reproduce**
download the zip, and extra to `C:/`
double click the `Arch.exe`.

**Expected behavior**
Install Success.

**Screenshots**
![image](https://user-images.githubusercontent.com/13938334/61052714-8b075b00-a41e-11e9-9204-9d41aa251446.png)

**Enviroment:**
 - Windows build number:  10.0.18932.1000
 - ArchWSL version: 19.7.2.0
 - ArchWSL Installer type zip/appx/other clean/update: zip clean and appx clean both failed.
 - Launcher version:  19070200

**Additional context**
None.

**Comment by lengthmin** [comment]
FAILED install all the wsl distributions... but I have already installed Ubuntu a few weeks ago..

**Comment by BennettStaley** [comment]
Whooops, figured it out. Intel VT-d was disabled in my bios on accident.

**Comment by sheeepdev** [comment]
I tried installing it several times with virtualization enabled and disabled, I tried installing it in different folders. I tried everything. Can't get it working.

**Comment by dylon** [comment]
I resolved this by downgrading my version of wsl from 2 to 1:
1. Open the Command Prompt as an administrator
2. Make sure you are running wsl 1: `wsl --set-default-version 1`
3. Run installer again

**Comment by 8BallDuVal** [comment]
> I resolved this by downgrading my version of wsl from 2 to 1:
> 
> 1. Open the Command Prompt as an administrator
> 2. Make sure you are running wsl 1: `wsl --set-default-version 1`
> 3. Run installer again

Thank you kind stranger. This worked.
