### ISSUE TITLE
keeps crashing in latest windows insider build 

### ISSUE THREAD

**Issue by elswerky** [yuk7/ArchWSL#94]
why arch wsl appx package keeps crashing with me on windows insider build 
18956.1000

whenever i open arch.exe ,it keeps crashing 

i tested ubuntu.exe and it didn't crash like arch one 

can you help me plz 

even i unistalled arch.exe and lost everything there and re-installed it but still crash when i open arch.exe 

any help plz

**Comment by xBLACKICEx** [comment]
same issues
win ver: 18950.1000
