### ISSUE TITLE
Can't run nginx

### ISSUE THREAD

**Issue by foisonocean** [yuk7/ArchWSL#95]
**To Reproduce**

1. `sudo pacman -S nginx`
1. `sudo nginx`

**Expected behavior**
Run nginx properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/15059605/64058303-7607a680-cbdb-11e9-8c39-fb8d8f0be90c.png)

**Enviroment:**
 - Windows build number: Microsoft Windows [Version 10.0.17763.195]
 - ArchWSL version 19.7.2.0
 - ArchWSL Installer type zip clean
 - Launcher version 19070200

**Comment by HUMORCE** [comment]
edit section **http** at config (like /etc/nginx.conf)
`
types_hash_max_size 2048;
`
you can also set it another **higher value** , and then
> sudo nginx -t

If can't solve the problem,
don't waste the time, try **Caddy**
