### ISSUE TITLE
PGP Signature getting corrupted when attempting to install any program

### ISSUE THREAD

**Issue by RetroProfessional** [yuk7/ArchWSL#96]
**Describe the issue**
PGP Signature gets corrupted when trying to install a program from pacman.

**To Reproduce**
no idea

**Expected behavior**
install a program

**Screenshots**
https://i.imgur.com/cZgSRua.png
https://i.imgur.com/GXJDWEF.png

**Enviroment:**
 - Windows build number: [Version 10.0.18362.329]
 - ArchWSL version 19.7.2.0
 - ArchWSL Installer type appx
 - Launcher version ?? i use appx, how do i acquire version of the launcher on appx? 

**Additional context**
cant install anything, and i mean nothing, cant even update packages

**Comment by yuk7** [comment]
Please initialize keyring.
https://github.com/yuk7/ArchWSL/wiki/How-to-Setup#3initialize-keyring

**Comment by RetroProfessional** [comment]
> Please initialize keyring.
> https://github.com/yuk7/ArchWSL/wiki/How-to-Setup#3initialize-keyring

looks like that worked...and stupid of me I didn't read the wiki
