### ISSUE TITLE
Not able to run sandbox mode in chromium

### ISSUE THREAD

**Issue by cristoferfb** [yuk7/ArchWSL#99]
**Describe the issue**
This more than a problem is a question, if I'm not in error, the sandbox that Chromium uses depends on the Linux kernel security modules, apparently they are not enabled in this Arch for WSL, so is it a WSL limitation?

**To Reproduce**
1.- Install brave (I install the brave-bin package from AUR)
2.- Open brave
3.- Check the sandbox status in chrome://sandbox/
(Any chromium browser should give the same result)

**Expected behavior**
A correct sandboxed startup

**Screenshots**
![image](https://user-images.githubusercontent.com/28372608/69903187-2751e000-1375-11ea-89c0-df1d3ee471aa.png)

**Enviroment:**
 - Windows build number: 10.0.18363.476
 - Security Software: Windows defender
 - ArchWSL version 19.11.16.0
 - ArchWSL Installer type zip
 - Launcher version 19111602

**Comment by arlllk** [comment]
In WSL2 the kernel is in windows side, currently they use a custom kernel that can be modified and installed for all the distros installed, and can't be fixed from each distro, [This is the kernel](https://github.com/microsoft/WSL2-Linux-Kernel) that is currently in use, you can edit it and recompile it with the flags that you want to use, from [this](https://github.com/MicrosoftDocs/WSL/releases/tag/18947) release you can use a specific kernel easily creating the config file

**Comment by yuk7** [comment]
https://github.com/microsoft/WSL/issues/3282

**Comment by yuk7** [comment]
WSL2 fixes this issue...
